{
  "compatibilityLevel": 1200,
  "name": "SemanticModel",
  "model": {
    "relationships": [
      {
        "relyOnReferentialIntegrity": true,
        "name": "e4b79f28-4bc9-49ab-a43c-3fec85a3acaa",
        "fromColumn": "Business Date",
        "toTable": "D Time",
        "toColumn": "Calendar Date",
        "fromTable": "F GWB Cross Border"
      },
      {
        "relyOnReferentialIntegrity": true,
        "name": "57e9385d-35c2-4b40-83dc-db1aded65e62",
        "fromColumn": "Currency Type Code",
        "toTable": "D Currency Filter",
        "toColumn": "Currency Type Code",
        "fromTable": "F GWB Cross Border"
      },
      {
        "relyOnReferentialIntegrity": true,
        "name": "db574f82-ab03-4d78-a20d-5f0177ce5e80",
        "fromColumn": "Currency Code",
        "toTable": "D Currency",
        "toColumn": "Currency Code",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "1a9d4f02-bcc3-4132-898e-4c404eb123fc",
        "fromColumn": "Product COA ID",
        "toTable": "H Product Group",
        "toColumn": "Leaf Node",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "8b6a2fb3-4cce-4877-8e43-6e608def2418",
        "fromColumn": "Product COA ID",
        "toTable": "H Product Org",
        "toColumn": "Leaf Node",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "e31ebd46-f5c4-4bfc-893b-4e8c2371d311",
        "fromColumn": "FRM Cost Centre",
        "toTable": "H Group Org FRM",
        "toColumn": "Leaf Node",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "b8f31e30-4c60-49e5-94f8-8b8d9257c7ad",
        "fromColumn": "Reporting Cost Centre",
        "toTable": "H Group Segment Reporting",
        "toColumn": "Leaf Node",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "aa4e3c46-30d4-4d9e-a936-a41449be4f6c",
        "fromColumn": "GRM Country Code",
        "toTable": "D Country GRM",
        "toColumn": "Site ID",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "4f8c975f-eed5-48e0-9708-1bffc678e62d",
        "fromColumn": "FRM CTO OFFICER EDW ID",
        "toTable": "D CTO Officer",
        "toColumn": "CTO Officer EDW ID",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "ed0042e5-a604-4141-bfb6-fc0536a8ca11",
        "fromColumn": "BUSS_DT_FRM_CTO_OFICR_EDW_ID",
        "toTable": "X D CTO Officer Dated",
        "toColumn": "BUSN_DT_CTO_OFICR_EDW_ID",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "23ca38a2-4c27-4b30-90b3-e0287719c3b6",
        "fromColumn": "Scenario Cd",
        "toTable": "D Scenario Type",
        "toColumn": "Scenario Code",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "ff6c2dac-14c0-4d95-97d2-0ccf8bf351bb",
        "fromColumn": "Scenario Sub Category",
        "toTable": "D Scenario Sub Category",
        "toColumn": "Scenario Sub Category",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "6389792a-cbe4-48ef-b803-ecd812e9212f",
        "fromColumn": "GRM OFFICER EDW Id",
        "toTable": "D GRM Officer",
        "toColumn": "GRM Officer EDW ID",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "e0c75e78-6b5d-4a2a-8299-8197fef4533f",
        "fromColumn": "PARTY EDW ID",
        "toTable": "R GWB Party Group",
        "toColumn": "CIF Party EDW ID",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "c513f383-1bdf-4987-ba92-f30653eb4d59",
        "fromColumn": "BUSS_DT_GRM_OFICR_EDW_ID",
        "toTable": "X D GRM Officer Dated",
        "toColumn": "BUSS_DT_GRM_OFICR_EDW_ID",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "d44afd55-3f32-4f7a-a405-971dfe9d7970",
        "fromColumn": "FRM Country Code",
        "toTable": "D Country FRM",
        "toColumn": "Site ID",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "d10a4790-3597-431b-b041-dab62c4519d6",
        "fromColumn": "GRM Cost Centre",
        "toTable": "H Group Segment GRM",
        "toColumn": "Leaf Node",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "0bbfa24d-a694-4ead-a321-2ac4fc3d10e0",
        "fromColumn": "FRM Cost Centre",
        "toTable": "H Group Segment FRM",
        "toColumn": "Leaf Node",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "f7976ea2-53d8-46d4-8ad8-03ab57cf1e19",
        "fromColumn": "Enterprise Product Leaf Node",
        "toTable": "H Product Reporting",
        "toColumn": "Leaf Node",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "2203d5f9-5bec-48b4-864c-c9e6bc151ff5",
        "fromColumn": "FRM Cost Centre",
        "toTable": "H Reporting Hierarchy Corp Cost Center GRM",
        "toColumn": "Leaf Node",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "d2944bf2-2e57-47f7-a3a3-56e6bad05f5c",
        "fromColumn": "GRM Cost Centre",
        "toTable": "H Reporting Hierarchy Corp Cost Center FRM",
        "toColumn": "Leaf Node",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "84f85ba7-b696-4c7a-8f5d-2bb1d1b5f989",
        "fromColumn": "PARTY EDW ID",
        "toTable": "D Party GWB",
        "toColumn": "PARTY EDW ID",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "fa5ceb91-f01c-4ea5-ab08-dfd7812cd9ce",
        "fromColumn": "MAS industrial classification",
        "toTable": "H MAS Industry",
        "toColumn": "Industry Code",
        "fromTable": "D Party GWB"
      },
      {
        "name": "c603eb5a-6ea1-4c41-92d3-f805a84761be",
        "fromColumn": "GRM Cost Centre",
        "toTable": "H Group Org GRM",
        "toColumn": "Leaf Node",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "24d191af-efd3-45cf-bdaa-73e55bad7d2c",
        "fromColumn": "MAS industrial classification",
        "toTable": "H Apex Industry",
        "toColumn": "Industry Code",
        "fromTable": "D Party GWB"
      },
      {
        "name": "6123d52d-e978-40cb-b7fc-9a5a7a7cdee3",
        "fromColumn": "Cross Border Category",
        "toTable": "D Cross Border Category",
        "toColumn": "Cross Border Category Code",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "f2ada862-b5ad-4fa1-ba5c-4d5b16e691cd",
        "fromColumn": "Asis Aswas Category",
        "toTable": "D Asis Aswas Category",
        "toColumn": "Asis Aswas Category Code",
        "fromTable": "F GWB Cross Border"
      },
      {
        "relyOnReferentialIntegrity": true,
        "name": "3005eac5-4297-48d2-bb0d-39453ad3f058",
        "fromColumn": "Business Date",
        "toTable": "D Time",
        "toColumn": "Calendar Date",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "relyOnReferentialIntegrity": true,
        "name": "1d25ab96-ab7c-46d2-b541-3028b76e4045",
        "fromColumn": "Currency Type Code",
        "toTable": "D Currency Filter",
        "toColumn": "Currency Type Code",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "relyOnReferentialIntegrity": true,
        "name": "2f91a647-7208-459e-a71c-f11676022218",
        "fromColumn": "Currency Code",
        "toTable": "D Currency",
        "toColumn": "Currency Code",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "10072c28-287e-4f13-a648-f054c24bd795",
        "fromColumn": "Product COA ID",
        "toTable": "H Product Group",
        "toColumn": "Leaf Node",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "119590ee-e365-4c95-af1c-886adf37a735",
        "fromColumn": "Product COA ID",
        "toTable": "H Product Org",
        "toColumn": "Leaf Node",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "0d07bacd-d0e1-4566-b61e-dbe47b04802c",
        "fromColumn": "FRM Cost Centre",
        "toTable": "H Group Org FRM",
        "toColumn": "Leaf Node",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "72127b2c-68e7-4952-8786-1f3f0c3b672a",
        "fromColumn": "Reporting Cost Centre",
        "toTable": "H Group Segment Reporting",
        "toColumn": "Leaf Node",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "236e8c12-0940-49bf-bf94-6c8930dd6b3e",
        "fromColumn": "GRM Country Code",
        "toTable": "D Country GRM",
        "toColumn": "Site ID",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "a597b6af-e9b5-416b-8689-105053a110c4",
        "fromColumn": "FRM CTO OFFICER EDW ID",
        "toTable": "D CTO Officer",
        "toColumn": "CTO Officer EDW ID",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "8cf1128a-0449-4823-8808-461666faba2d",
        "fromColumn": "BUSS_DT_FRM_CTO_OFICR_EDW_ID",
        "toTable": "X D CTO Officer Dated",
        "toColumn": "BUSN_DT_CTO_OFICR_EDW_ID",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "b3403dd4-3d25-44ac-9def-cfc57dd94d82",
        "fromColumn": "Scenario Cd",
        "toTable": "D Scenario Type",
        "toColumn": "Scenario Code",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "090d04ea-a1a7-412c-9dd0-88eb5f502212",
        "fromColumn": "Scenario Sub Category",
        "toTable": "D Scenario Sub Category",
        "toColumn": "Scenario Sub Category",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "dabd004a-04ca-4aba-94e1-12bd3e194125",
        "fromColumn": "GRM OFFICER EDW Id",
        "toTable": "D GRM Officer",
        "toColumn": "GRM Officer EDW ID",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "12079c9b-a607-493c-b1e3-5e41471611ad",
        "fromColumn": "PARTY EDW ID",
        "toTable": "R GWB Party Group",
        "toColumn": "CIF Party EDW ID",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "a44df113-1253-4e72-af81-92a89c23e0fa",
        "fromColumn": "BUSS_DT_GRM_OFICR_EDW_ID",
        "toTable": "X D GRM Officer Dated",
        "toColumn": "BUSS_DT_GRM_OFICR_EDW_ID",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "9804d53c-23dc-4ce1-9f10-dd7d1f7b128d",
        "fromColumn": "FRM Country Code",
        "toTable": "D Country FRM",
        "toColumn": "Site ID",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "f3b6d409-33f8-4cab-8664-16e5de7fb3b3",
        "fromColumn": "GRM Cost Centre",
        "toTable": "H Group Segment GRM",
        "toColumn": "Leaf Node",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "29894039-5051-4223-9fb6-79c6147132e2",
        "fromColumn": "FRM Cost Centre",
        "toTable": "H Group Segment FRM",
        "toColumn": "Leaf Node",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "e75299f5-4116-4c07-abf3-f8940e12e625",
        "fromColumn": "Enterprise Product Leaf Node",
        "toTable": "H Product Reporting",
        "toColumn": "Leaf Node",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "51259b09-ecdb-41c9-bf42-de26f8f66827",
        "fromColumn": "FRM Cost Centre",
        "toTable": "H Reporting Hierarchy Corp Cost Center GRM",
        "toColumn": "Leaf Node",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "68366d5f-fe58-4aee-874d-a84f3212f42f",
        "fromColumn": "GRM Cost Centre",
        "toTable": "H Reporting Hierarchy Corp Cost Center FRM",
        "toColumn": "Leaf Node",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "48d36bea-e702-4321-9578-c6f9b3eb567c",
        "fromColumn": "PARTY EDW ID",
        "toTable": "D Party GWB",
        "toColumn": "PARTY EDW ID",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "acb433d1-253d-42d2-a992-43bec6df9e22",
        "fromColumn": "GRM Cost Centre",
        "toTable": "H Group Org GRM",
        "toColumn": "Leaf Node",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "c0df2c90-d757-4ff5-b756-8272b727088f",
        "fromColumn": "Cross Border Category",
        "toTable": "D Cross Border Category",
        "toColumn": "Cross Border Category Code",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "429146f0-2fa4-4f23-a7bf-19c64995f0f5",
        "fromColumn": "Asis Aswas Category",
        "toTable": "D Asis Aswas Category",
        "toColumn": "Asis Aswas Category Code",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "57c28695-fcb4-46d7-885d-ca43124c1d8b",
        "fromColumn": "GRM Country Code",
        "toTable": "D Country Inbound Outbound",
        "toColumn": "Site ID",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "65d86887-45bd-40c4-a324-b3e68e13b624",
        "fromColumn": "GRM Cost Centre",
        "toTable": "H Group Org Inbound Outbound",
        "toColumn": "Leaf Node",
        "fromTable": "F GWB Cross Border Profitibality"
      },
      {
        "name": "e0f387f4-2b53-4256-bbf0-8827830b8c0d",
        "fromColumn": "FRM Country Code",
        "toTable": "D Country Inbound Outbound",
        "toColumn": "Site ID",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "23933ea8-e9db-46bf-860c-389cd7249705",
        "fromColumn": "FRM Cost Centre",
        "toTable": "H Group Org Inbound Outbound",
        "toColumn": "Leaf Node",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "419ed087-d923-4674-8fd7-0dcea8cc77f9",
        "fromColumn": "Valuation Type",
        "toTable": "D Valuation Type",
        "toColumn": "Valuation Type",
        "fromTable": "F GWB Cross Border"
      },
      {
        "name": "e544e6b8-533c-4636-9ac9-eefadb471a96",
        "fromColumn": "Valuation Type",
        "toTable": "D Valuation Type",
        "toColumn": "Valuation Type",
        "fromTable": "F GWB Cross Border Profitibality"
      }
    ],
    "tables": [
      {
        "partitions": [{
          "name": "H_GRP_SEGMT_C",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_GRP_SEGMT_C\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_GRP_SEGMT_C\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [
          {
            "name": "H Group Segment - Code",
            "levels": [
              {
                "name": "Level 01 Code",
                "column": "Level 01 Code",
                "ordinal": 0
              },
              {
                "name": "Level 02 Code",
                "column": "Level 02 Code",
                "ordinal": 1
              },
              {
                "name": "Level 03 Code",
                "column": "Level 03 Code",
                "ordinal": 2
              },
              {
                "name": "Level 04 Code",
                "column": "Level 04 Code",
                "ordinal": 3
              },
              {
                "name": "Level 05 Code",
                "column": "Level 05 Code",
                "ordinal": 4
              }
            ]
          },
          {
            "name": "H Group Segment - Description",
            "levels": [
              {
                "name": "Level 01 Description",
                "column": "Level 01 Description",
                "ordinal": 0
              },
              {
                "name": "Level 02 Description",
                "column": "Level 02 Description",
                "ordinal": 1
              },
              {
                "name": "Level 03 Description",
                "column": "Level 03 Description",
                "ordinal": 2
              },
              {
                "name": "Level 04 Description",
                "column": "Level 04 Description",
                "ordinal": 3
              },
              {
                "name": "Level 05 Description",
                "column": "Level 05 Description",
                "ordinal": 4
              }
            ]
          }
        ],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 01 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_01_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 01 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_01_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 02 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_02_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 02 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_02_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 03 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_03_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 03 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_03_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 04 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_04_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 04 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_04_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 05 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_05_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 05 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_05_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Node",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_NODE"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Node Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_NODE_DESC"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Effective Date",
            "displayFolder": "Attributes",
            "sourceColumn": "EFF_DT"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Closed Date",
            "displayFolder": "Attributes",
            "sourceColumn": "CLS_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Closed Indicator",
            "displayFolder": "Attributes",
            "sourceColumn": "CLS_IND"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag1",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG1"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag2",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG2"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag3",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG3"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Business Date",
            "displayFolder": "Attributes",
            "sourceColumn": "BUSN_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CORPCC",
            "displayFolder": "Attributes",
            "sourceColumn": "CORPCC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CORPCC Description",
            "displayFolder": "Attributes",
            "sourceColumn": "CORPCC_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "H Group Segment Reporting",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_GRP_SEGMT_C\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_GRP_SEGMT_C\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "H_GRP_SEGMT_C"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "H_GRP_SEGMT_C",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_GRP_SEGMT_C\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_GRP_SEGMT_C\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [
          {
            "name": "H Group Segment - Code",
            "levels": [
              {
                "name": "Level 01 Code",
                "column": "Level 01 Code",
                "ordinal": 0
              },
              {
                "name": "Level 02 Code",
                "column": "Level 02 Code",
                "ordinal": 1
              },
              {
                "name": "Level 03 Code",
                "column": "Level 03 Code",
                "ordinal": 2
              },
              {
                "name": "Level 04 Code",
                "column": "Level 04 Code",
                "ordinal": 3
              },
              {
                "name": "Level 05 Code",
                "column": "Level 05 Code",
                "ordinal": 4
              }
            ]
          },
          {
            "name": "H Group Segment - Description",
            "levels": [
              {
                "name": "Level 01 Description",
                "column": "Level 01 Description",
                "ordinal": 0
              },
              {
                "name": "Level 02 Description",
                "column": "Level 02 Description",
                "ordinal": 1
              },
              {
                "name": "Level 03 Description",
                "column": "Level 03 Description",
                "ordinal": 2
              },
              {
                "name": "Level 04 Description",
                "column": "Level 04 Description",
                "ordinal": 3
              },
              {
                "name": "Level 05 Description",
                "column": "Level 05 Description",
                "ordinal": 4
              }
            ]
          }
        ],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 01 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_01_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 01 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_01_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 02 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_02_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 02 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_02_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 03 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_03_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 03 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_03_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 04 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_04_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 04 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_04_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 05 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_05_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 05 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_05_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Node",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_NODE"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Node Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_NODE_DESC"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Effective Date",
            "displayFolder": "Attributes",
            "sourceColumn": "EFF_DT"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Closed Date",
            "displayFolder": "Attributes",
            "sourceColumn": "CLS_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Closed Indicator",
            "displayFolder": "Attributes",
            "sourceColumn": "CLS_IND"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag1",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG1"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag2",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG2"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag3",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG3"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Business Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "BUSN_DT",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CORPCC",
            "displayFolder": "Attributes",
            "sourceColumn": "CORPCC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CORPCC Description",
            "displayFolder": "Attributes",
            "sourceColumn": "CORPCC_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "H Group Segment GRM",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_GRP_SEGMT_C\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_GRP_SEGMT_C\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "H_GRP_SEGMT_C"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "H_GRP_SEGMT_C",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_GRP_SEGMT_C\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_GRP_SEGMT_C\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [
          {
            "name": "H Group Segment - Code",
            "levels": [
              {
                "name": "Level 01 Code",
                "column": "Level 01 Code",
                "ordinal": 0
              },
              {
                "name": "Level 02 Code",
                "column": "Level 02 Code",
                "ordinal": 1
              },
              {
                "name": "Level 03 Code",
                "column": "Level 03 Code",
                "ordinal": 2
              },
              {
                "name": "Level 04 Code",
                "column": "Level 04 Code",
                "ordinal": 3
              },
              {
                "name": "Level 05 Code",
                "column": "Level 05 Code",
                "ordinal": 4
              }
            ]
          },
          {
            "name": "H Group Segment - Description",
            "levels": [
              {
                "name": "Level 01 Description",
                "column": "Level 01 Description",
                "ordinal": 0
              },
              {
                "name": "Level 02 Description",
                "column": "Level 02 Description",
                "ordinal": 1
              },
              {
                "name": "Level 03 Description",
                "column": "Level 03 Description",
                "ordinal": 2
              },
              {
                "name": "Level 04 Description",
                "column": "Level 04 Description",
                "ordinal": 3
              },
              {
                "name": "Level 05 Description",
                "column": "Level 05 Description",
                "ordinal": 4
              }
            ]
          }
        ],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 01 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_01_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 01 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_01_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 02 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_02_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 02 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_02_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 03 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_03_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 03 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_03_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 04 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_04_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 04 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_04_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 05 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_05_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 05 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_05_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Node",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_NODE"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Node Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_NODE_DESC"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Effective Date",
            "displayFolder": "Attributes",
            "sourceColumn": "EFF_DT"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Closed Date",
            "displayFolder": "Attributes",
            "sourceColumn": "CLS_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Closed Indicator",
            "displayFolder": "Attributes",
            "sourceColumn": "CLS_IND"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag1",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG1"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag2",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG2"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag3",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG3"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Business Date",
            "displayFolder": "Attributes",
            "sourceColumn": "BUSN_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CORPCC",
            "displayFolder": "Attributes",
            "sourceColumn": "CORPCC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CORPCC Description",
            "displayFolder": "Attributes",
            "sourceColumn": "CORPCC_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "H Group Segment FRM",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_GRP_SEGMT_C\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_GRP_SEGMT_C\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "H_GRP_SEGMT_C"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "GWB_CROSS_BORDER_COUNTRY",
          "annotations": [{
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT VALUE_ID AS SITE_ID,CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS CTRY_CD,",
              "CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS SORT_ID,",
              "CASE WHEN VALUE_ID IN ('U1','U2') ",
              "THEN 'UNITED STATES' WHEN VALUE_ID='M2' ",
              "THEN 'MALAYSIA' ELSE DESCRIPTION END AS CTRY_NM ",
              "FROM U01_EDW_SEM_OTH_V.MST_REFERENCE_CODE_FRR WHERE CODE_NAME='Country Code'<\/RSQueryCommandText><RSQueryCommandType>Text<\/RSQueryCommandType><RSQueryDesignState><\/RSQueryDesignState>]]><\/AnnotationContent><\/Gemini>"
            ]
          }],
          "source": {
            "query": [
              "SELECT VALUE_ID AS SITE_ID,CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS CTRY_CD,",
              "CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS SORT_ID,",
              "CASE WHEN VALUE_ID IN ('U1','U2') ",
              "THEN 'UNITED STATES' WHEN VALUE_ID='M2' ",
              "THEN 'MALAYSIA' ELSE DESCRIPTION END AS CTRY_NM ",
              "FROM U01_EDW_SEM_OTH_V.MST_REFERENCE_CODE_FRR WHERE CODE_NAME='Country Code'"
            ],
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "sortByColumn": "GRM Country Sort",
            "displayFolder": "Attributes",
            "sourceColumn": "SITE_ID"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Country Code",
            "sortByColumn": "GRM Country Sort",
            "displayFolder": "Attributes",
            "sourceColumn": "CTRY_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Sort ID",
            "displayFolder": "Attributes",
            "sourceColumn": "SORT_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Country Name",
            "sortByColumn": "GRM Country Sort",
            "displayFolder": "Attributes",
            "sourceColumn": "CTRY_NM"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SWITCH ('D Country GRM'[Sort ID], \"SG\" ,1,\"MY\" ,2,\"ID\" ,3,\"TH\" ,4,\"VN\" ,5,\"CN\" ,6,\"HK\" ,7,\"TW\" ,8,\"GB\" ,9,\"US\" ,10,\"CA\" ,11,\"AU\" ,12,\"JP\" ,13,\"KR\" ,14,\"IN\" ,15,\"MM\" ,16,\"PH\" ,17,\"BN\" ,18,123456 )",
            "name": "GRM Country Sort",
            "type": "calculated",
            "displayFolder": "Attributes"
          }
        ],
        "dataCategory": "",
        "name": "D Country GRM",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT VALUE_ID AS SITE_ID,CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS CTRY_CD,",
              "CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS SORT_ID,",
              "CASE WHEN VALUE_ID IN ('U1','U2') ",
              "THEN 'UNITED STATES' WHEN VALUE_ID='M2' ",
              "THEN 'MALAYSIA' ELSE DESCRIPTION END AS CTRY_NM ",
              "FROM U01_EDW_SEM_OTH_V.MST_REFERENCE_CODE_FRR WHERE CODE_NAME='Country Code'"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "GWB_CROSS_BORDER_COUNTRY"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT VALUE_ID AS SITE_ID,CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS CTRY_CD,",
              "CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS SORT_ID,",
              "CASE WHEN VALUE_ID IN ('U1','U2') ",
              "THEN 'UNITED STATES' WHEN VALUE_ID='M2' ",
              "THEN 'MALAYSIA' ELSE DESCRIPTION END AS CTRY_NM ",
              "FROM U01_EDW_SEM_OTH_V.MST_REFERENCE_CODE_FRR WHERE CODE_NAME='Country Code'<\/RSQueryCommandText><RSQueryCommandType>Text<\/RSQueryCommandType><RSQueryDesignState><\/RSQueryDesignState>]]><\/AnnotationContent><\/Gemini>"
            ]
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "GWB_CROSS_BORDER_COUNTRY",
          "annotations": [{
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT VALUE_ID AS SITE_ID,CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS CTRY_CD,",
              "CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS SORT_ID,",
              "CASE WHEN VALUE_ID IN ('U1','U2') ",
              "THEN 'UNITED STATES' WHEN VALUE_ID='M2' ",
              "THEN 'MALAYSIA' ELSE DESCRIPTION END AS CTRY_NM ",
              "FROM U01_EDW_SEM_OTH_V.MST_REFERENCE_CODE_FRR WHERE CODE_NAME='Country Code'<\/RSQueryCommandText><RSQueryCommandType>Text<\/RSQueryCommandType><RSQueryDesignState><\/RSQueryDesignState>]]><\/AnnotationContent><\/Gemini>"
            ]
          }],
          "source": {
            "query": [
              "SELECT VALUE_ID AS SITE_ID,CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS CTRY_CD,",
              "CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS SORT_ID,",
              "CASE WHEN VALUE_ID IN ('U1','U2') ",
              "THEN 'UNITED STATES' WHEN VALUE_ID='M2' ",
              "THEN 'MALAYSIA' ELSE DESCRIPTION END AS CTRY_NM ",
              "FROM U01_EDW_SEM_OTH_V.MST_REFERENCE_CODE_FRR WHERE CODE_NAME='Country Code'"
            ],
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "sortByColumn": "FRM Country Sort",
            "displayFolder": "Attributes",
            "sourceColumn": "SITE_ID"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Country Code",
            "sortByColumn": "FRM Country Sort",
            "displayFolder": "Attributes",
            "sourceColumn": "CTRY_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Sort ID",
            "displayFolder": "Attributes",
            "sourceColumn": "SORT_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Country Name",
            "sortByColumn": "FRM Country Sort",
            "displayFolder": "Attributes",
            "sourceColumn": "CTRY_NM"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SWITCH ('D Country FRM'[Sort ID], \"SG\" ,1,\"MY\" ,2,\"ID\" ,3,\"TH\" ,4,\"VN\" ,5,\"CN\" ,6,\"HK\" ,7,\"TW\" ,8,\"GB\" ,9,\"US\" ,10,\"CA\" ,11,\"AU\" ,12,\"JP\" ,13,\"KR\" ,14,\"IN\" ,15,\"MM\" ,16,\"PH\" ,17,\"BN\" ,18,123456 )",
            "name": "FRM Country Sort",
            "type": "calculated",
            "displayFolder": "Attributes"
          }
        ],
        "dataCategory": "",
        "name": "D Country FRM",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT VALUE_ID AS SITE_ID,CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS CTRY_CD,",
              "CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS SORT_ID,",
              "CASE WHEN VALUE_ID IN ('U1','U2') ",
              "THEN 'UNITED STATES' WHEN VALUE_ID='M2' ",
              "THEN 'MALAYSIA' ELSE DESCRIPTION END AS CTRY_NM ",
              "FROM U01_EDW_SEM_OTH_V.MST_REFERENCE_CODE_FRR WHERE CODE_NAME='Country Code'"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "GWB_CROSS_BORDER_COUNTRY"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT VALUE_ID AS SITE_ID,CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS CTRY_CD,",
              "CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS SORT_ID,",
              "CASE WHEN VALUE_ID IN ('U1','U2') ",
              "THEN 'UNITED STATES' WHEN VALUE_ID='M2' ",
              "THEN 'MALAYSIA' ELSE DESCRIPTION END AS CTRY_NM ",
              "FROM U01_EDW_SEM_OTH_V.MST_REFERENCE_CODE_FRR WHERE CODE_NAME='Country Code'<\/RSQueryCommandText><RSQueryCommandType>Text<\/RSQueryCommandType><RSQueryDesignState><\/RSQueryDesignState>]]><\/AnnotationContent><\/Gemini>"
            ]
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "H_REP_HIER_CORP_COST_CENTER",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_REP_HIER_CORP_COST_CENTER\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_REP_HIER_CORP_COST_CENTER\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [{
          "name": "H Reporting Hierarchy Corp Cost Center - Description FRM",
          "levels": [
            {
              "name": "Level 01 Name",
              "column": "Level 01 Name",
              "ordinal": 0
            },
            {
              "name": "Level 02 Name",
              "column": "Level 02 Name",
              "ordinal": 1
            },
            {
              "name": "Drill 01 Description",
              "column": "Drill 01 Description",
              "ordinal": 2
            },
            {
              "name": "Drill 02 Description",
              "column": "Drill 02 Description",
              "ordinal": 3
            },
            {
              "name": "Drill 03 Description",
              "column": "Drill 03 Description",
              "ordinal": 4
            },
            {
              "name": "Drill 04 Description",
              "column": "Drill 04 Description",
              "ordinal": 5
            },
            {
              "name": "Drill 05 Description",
              "column": "Drill 05 Description",
              "ordinal": 6
            },
            {
              "name": "Drill 06 Description",
              "column": "Drill 06 Description",
              "ordinal": 7
            },
            {
              "name": "Drill 07 Description",
              "column": "Drill 07 Description",
              "ordinal": 8
            },
            {
              "name": "Drill 08 Description",
              "column": "Drill 08 Description",
              "ordinal": 9
            }
          ]
        }],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Reporting Hierarchy Name",
            "displayFolder": "Attributes",
            "sourceColumn": "REP_HIER_NAME"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Enterprise Hierarchy Name",
            "displayFolder": "Attributes",
            "sourceColumn": "ENT_HIER_NAME"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 01 Name",
            "sortByColumn": "Level 01 Sort",
            "displayFolder": "Attributes",
            "sourceColumn": "L1_NAME"
          },
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "Level 01 Sort",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "L1_SORT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 02 Name",
            "sortByColumn": "Level 02 Sort",
            "displayFolder": "Attributes",
            "sourceColumn": "L2_NAME"
          },
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "Level 02 Sort",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "L2_SORT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 01 Name",
            "displayFolder": "Attributes",
            "sourceColumn": "D1_NAME"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 01 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "D1_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 01 Level",
            "displayFolder": "Attributes",
            "sourceColumn": "D1_LEV"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 02 Name",
            "displayFolder": "Attributes",
            "sourceColumn": "D2_NAME"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 02 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "D2_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 02 Level",
            "displayFolder": "Attributes",
            "sourceColumn": "D2_LEV"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 03 Name",
            "displayFolder": "Attributes",
            "sourceColumn": "D3_NAME"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 03 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "D3_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 03 Level",
            "displayFolder": "Attributes",
            "sourceColumn": "D3_LEV"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 04 Name",
            "displayFolder": "Attributes",
            "sourceColumn": "D4_NAME"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 04 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "D4_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 04 Level",
            "displayFolder": "Attributes",
            "sourceColumn": "D4_LEV"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 05 Name",
            "displayFolder": "Attributes",
            "sourceColumn": "D5_NAME"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 05 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "D5_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 05 Level",
            "displayFolder": "Attributes",
            "sourceColumn": "D5_LEV"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 06 Name",
            "displayFolder": "Attributes",
            "sourceColumn": "D6_NAME"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 06 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "D6_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 06 Level",
            "displayFolder": "Attributes",
            "sourceColumn": "D6_LEV"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 07 Name",
            "displayFolder": "Attributes",
            "sourceColumn": "D7_NAME"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 07 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "D7_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 07 Level",
            "displayFolder": "Attributes",
            "sourceColumn": "D7_LEV"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 08 Name",
            "displayFolder": "Attributes",
            "sourceColumn": "D8_NAME"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 08 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "D8_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 08 Level",
            "displayFolder": "Attributes",
            "sourceColumn": "D8_LEV"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Node",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_NODE"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Node Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_NODE_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Snapshot Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "START_DATE",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "End Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "END_DATE",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Record Deleted Flag",
            "summarizeBy": "none",
            "displayFolder": "Tech Fields",
            "sourceColumn": "RECORD_DELETED_FLAG",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Control ID",
            "summarizeBy": "none",
            "displayFolder": "Tech Fields",
            "sourceColumn": "CTL_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Process Name",
            "displayFolder": "Tech Fields",
            "sourceColumn": "PROCESS_NAME",
            "isHidden": true
          },
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "Process ID",
            "summarizeBy": "none",
            "displayFolder": "Tech Fields",
            "sourceColumn": "PROCESS_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Update Process Name",
            "displayFolder": "Tech Fields",
            "sourceColumn": "UPDATE_PROCESS_NAME",
            "isHidden": true
          },
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "Update Process ID",
            "summarizeBy": "none",
            "displayFolder": "Tech Fields",
            "sourceColumn": "UPDATE_PROCESS_ID",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Start Timestamp",
            "displayFolder": "Tech Fields",
            "sourceColumn": "START_TS",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "End Timestamp",
            "displayFolder": "Tech Fields",
            "sourceColumn": "END_TS",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "H Reporting Hierarchy Corp Cost Center GRM",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_REP_HIER_CORP_COST_CENTER\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_REP_HIER_CORP_COST_CENTER\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "H_REP_HIER_CORP_COST_CENTER"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "H_REP_HIER_CORP_COST_CENTER",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_REP_HIER_CORP_COST_CENTER\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_REP_HIER_CORP_COST_CENTER\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [{
          "name": "H Reporting Hierarchy Corp Cost Center - Description GRM",
          "levels": [
            {
              "name": "Level 01 Name",
              "column": "Level 01 Name",
              "ordinal": 0
            },
            {
              "name": "Level 02 Name",
              "column": "Level 02 Name",
              "ordinal": 1
            },
            {
              "name": "Drill 01 Description",
              "column": "Drill 01 Description",
              "ordinal": 2
            },
            {
              "name": "Drill 02 Description",
              "column": "Drill 02 Description",
              "ordinal": 3
            },
            {
              "name": "Drill 03 Description",
              "column": "Drill 03 Description",
              "ordinal": 4
            },
            {
              "name": "Drill 04 Description",
              "column": "Drill 04 Description",
              "ordinal": 5
            },
            {
              "name": "Drill 05 Description",
              "column": "Drill 05 Description",
              "ordinal": 6
            },
            {
              "name": "Drill 06 Description",
              "column": "Drill 06 Description",
              "ordinal": 7
            },
            {
              "name": "Drill 07 Description",
              "column": "Drill 07 Description",
              "ordinal": 8
            },
            {
              "name": "Drill 08 Description",
              "column": "Drill 08 Description",
              "ordinal": 9
            }
          ]
        }],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Reporting Hierarchy Name",
            "displayFolder": "Attributes",
            "sourceColumn": "REP_HIER_NAME"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Enterprise Hierarchy Name",
            "displayFolder": "Attributes",
            "sourceColumn": "ENT_HIER_NAME"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 01 Name",
            "sortByColumn": "Level 01 Sort",
            "displayFolder": "Attributes",
            "sourceColumn": "L1_NAME"
          },
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "Level 01 Sort",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "L1_SORT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 02 Name",
            "sortByColumn": "Level 02 Sort",
            "displayFolder": "Attributes",
            "sourceColumn": "L2_NAME"
          },
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "Level 02 Sort",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "L2_SORT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 01 Name",
            "displayFolder": "Attributes",
            "sourceColumn": "D1_NAME"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 01 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "D1_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 01 Level",
            "displayFolder": "Attributes",
            "sourceColumn": "D1_LEV"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 02 Name",
            "displayFolder": "Attributes",
            "sourceColumn": "D2_NAME"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 02 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "D2_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 02 Level",
            "displayFolder": "Attributes",
            "sourceColumn": "D2_LEV"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 03 Name",
            "displayFolder": "Attributes",
            "sourceColumn": "D3_NAME"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 03 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "D3_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 03 Level",
            "displayFolder": "Attributes",
            "sourceColumn": "D3_LEV"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 04 Name",
            "displayFolder": "Attributes",
            "sourceColumn": "D4_NAME"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 04 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "D4_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 04 Level",
            "displayFolder": "Attributes",
            "sourceColumn": "D4_LEV"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 05 Name",
            "displayFolder": "Attributes",
            "sourceColumn": "D5_NAME"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 05 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "D5_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 05 Level",
            "displayFolder": "Attributes",
            "sourceColumn": "D5_LEV"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 06 Name",
            "displayFolder": "Attributes",
            "sourceColumn": "D6_NAME"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 06 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "D6_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 06 Level",
            "displayFolder": "Attributes",
            "sourceColumn": "D6_LEV"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 07 Name",
            "displayFolder": "Attributes",
            "sourceColumn": "D7_NAME"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 07 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "D7_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 07 Level",
            "displayFolder": "Attributes",
            "sourceColumn": "D7_LEV"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 08 Name",
            "displayFolder": "Attributes",
            "sourceColumn": "D8_NAME"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 08 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "D8_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Drill 08 Level",
            "displayFolder": "Attributes",
            "sourceColumn": "D8_LEV"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Node",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_NODE"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Node Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_NODE_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Snapshot Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "START_DATE",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "End Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "END_DATE",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Record Deleted Flag",
            "summarizeBy": "none",
            "displayFolder": "Tech Fields",
            "sourceColumn": "RECORD_DELETED_FLAG",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Control ID",
            "summarizeBy": "none",
            "displayFolder": "Tech Fields",
            "sourceColumn": "CTL_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Process Name",
            "displayFolder": "Tech Fields",
            "sourceColumn": "PROCESS_NAME",
            "isHidden": true
          },
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "Process ID",
            "summarizeBy": "none",
            "displayFolder": "Tech Fields",
            "sourceColumn": "PROCESS_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Update Process Name",
            "displayFolder": "Tech Fields",
            "sourceColumn": "UPDATE_PROCESS_NAME",
            "isHidden": true
          },
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "Update Process ID",
            "summarizeBy": "none",
            "displayFolder": "Tech Fields",
            "sourceColumn": "UPDATE_PROCESS_ID",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Start Timestamp",
            "displayFolder": "Tech Fields",
            "sourceColumn": "START_TS",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "End Timestamp",
            "displayFolder": "Tech Fields",
            "sourceColumn": "END_TS",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "H Reporting Hierarchy Corp Cost Center FRM",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_REP_HIER_CORP_COST_CENTER\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_REP_HIER_CORP_COST_CENTER\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "H_REP_HIER_CORP_COST_CENTER"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "H_GRP_ORG_C",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_GRP_ORG_C\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_GRP_ORG_C\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [
          {
            "name": "H Group Org - Description",
            "levels": [
              {
                "name": "Level 01 Description",
                "column": "Level 01 Description",
                "ordinal": 0
              },
              {
                "name": "Level 02 Description",
                "column": "Level 02 Description",
                "ordinal": 1
              },
              {
                "name": "Level 03 Description",
                "column": "Level 03 Description",
                "ordinal": 2
              },
              {
                "name": "Level 04 Description",
                "column": "Level 04 Description",
                "ordinal": 3
              },
              {
                "name": "Level 05 Description",
                "column": "Level 05 Description",
                "ordinal": 4
              },
              {
                "name": "Level 06 Description",
                "column": "Level 06 Description",
                "ordinal": 5
              },
              {
                "name": "Level 07 Description",
                "column": "Level 07 Description",
                "ordinal": 6
              },
              {
                "name": "Level 08 Description",
                "column": "Level 08 Description",
                "ordinal": 7
              }
            ]
          },
          {
            "name": "H Group Org - Code",
            "levels": [
              {
                "name": "Level 01 Code",
                "column": "Level 01 Code",
                "ordinal": 0
              },
              {
                "name": "Level 02 Code",
                "column": "Level 02 Code",
                "ordinal": 1
              },
              {
                "name": "Level 03 Code",
                "column": "Level 03 Code",
                "ordinal": 2
              },
              {
                "name": "Level 04 Code",
                "column": "Level 04 Code",
                "ordinal": 3
              },
              {
                "name": "Level 05 Code",
                "column": "Level 05 Code",
                "ordinal": 4
              },
              {
                "name": "Level 06 Code",
                "column": "Level 06 Code",
                "ordinal": 5
              },
              {
                "name": "Level 07 Code",
                "column": "Level 07 Code",
                "ordinal": 6
              },
              {
                "name": "Level 08 Code",
                "column": "Level 08 Code",
                "ordinal": 7
              }
            ]
          }
        ],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 01 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_01_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 01 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_01_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 02 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_02_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 02 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_02_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 03 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_03_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 03 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_03_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 04 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_04_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 04 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_04_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 05 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_05_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 05 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_05_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 06 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_06_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 06 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_06_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 07 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_07_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 07 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_07_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 08 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_08_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 08 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_08_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Node",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_NODE"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Node Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_NODE_DESC"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Effective Date",
            "displayFolder": "Attributes",
            "sourceColumn": "EFF_DT"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Closed Date",
            "displayFolder": "Attributes",
            "sourceColumn": "CLS_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Closed Indicator",
            "displayFolder": "Attributes",
            "sourceColumn": "CLS_IND"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GW SEG DER",
            "displayFolder": "Attributes",
            "sourceColumn": "GW_SEG_DER"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GW SEG Description",
            "displayFolder": "Attributes",
            "sourceColumn": "GW_SEG_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Home Currency Code",
            "displayFolder": "Attributes",
            "sourceColumn": "HOME_CCY_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Trading Indicator",
            "displayFolder": "Attributes",
            "sourceColumn": "TRDG_IND"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag1",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG1"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag2",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG2"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag3",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG3"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Business Date",
            "displayFolder": "Attributes",
            "sourceColumn": "BUSN_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CORPCC",
            "displayFolder": "Attributes",
            "sourceColumn": "CORPCC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CORPCC Description",
            "displayFolder": "Attributes",
            "sourceColumn": "CORPCC_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "SEG DER Leaf",
            "displayFolder": "Attributes",
            "sourceColumn": "SEG_DER_LEAF"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "SEG Description",
            "displayFolder": "Attributes",
            "sourceColumn": "SEG_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "H Group Org FRM",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_GRP_ORG_C\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_GRP_ORG_C\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "H_GRP_ORG_C"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "H_GRP_ORG_C",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_GRP_ORG_C\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_GRP_ORG_C\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [
          {
            "name": "H Group Org - Description",
            "levels": [
              {
                "name": "Level 01 Description",
                "column": "Level 01 Description",
                "ordinal": 0
              },
              {
                "name": "Level 02 Description",
                "column": "Level 02 Description",
                "ordinal": 1
              },
              {
                "name": "Level 03 Description",
                "column": "Level 03 Description",
                "ordinal": 2
              },
              {
                "name": "Level 04 Description",
                "column": "Level 04 Description",
                "ordinal": 3
              },
              {
                "name": "Level 05 Description",
                "column": "Level 05 Description",
                "ordinal": 4
              },
              {
                "name": "Level 06 Description",
                "column": "Level 06 Description",
                "ordinal": 5
              },
              {
                "name": "Level 07 Description",
                "column": "Level 07 Description",
                "ordinal": 6
              },
              {
                "name": "Level 08 Description",
                "column": "Level 08 Description",
                "ordinal": 7
              }
            ]
          },
          {
            "name": "H Group Org - Code",
            "levels": [
              {
                "name": "Level 01 Code",
                "column": "Level 01 Code",
                "ordinal": 0
              },
              {
                "name": "Level 02 Code",
                "column": "Level 02 Code",
                "ordinal": 1
              },
              {
                "name": "Level 03 Code",
                "column": "Level 03 Code",
                "ordinal": 2
              },
              {
                "name": "Level 04 Code",
                "column": "Level 04 Code",
                "ordinal": 3
              },
              {
                "name": "Level 05 Code",
                "column": "Level 05 Code",
                "ordinal": 4
              },
              {
                "name": "Level 06 Code",
                "column": "Level 06 Code",
                "ordinal": 5
              },
              {
                "name": "Level 07 Code",
                "column": "Level 07 Code",
                "ordinal": 6
              },
              {
                "name": "Level 08 Code",
                "column": "Level 08 Code",
                "ordinal": 7
              }
            ]
          }
        ],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 01 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_01_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 01 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_01_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 02 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_02_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 02 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_02_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 03 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_03_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 03 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_03_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 04 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_04_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 04 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_04_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 05 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_05_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 05 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_05_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 06 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_06_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 06 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_06_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 07 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_07_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 07 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_07_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 08 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_08_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 08 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_08_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Node",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_NODE"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Node Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_NODE_DESC"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Effective Date",
            "displayFolder": "Attributes",
            "sourceColumn": "EFF_DT"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Closed Date",
            "displayFolder": "Attributes",
            "sourceColumn": "CLS_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Closed Indicator",
            "displayFolder": "Attributes",
            "sourceColumn": "CLS_IND"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GW SEG DER",
            "displayFolder": "Attributes",
            "sourceColumn": "GW_SEG_DER"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GW SEG Description",
            "displayFolder": "Attributes",
            "sourceColumn": "GW_SEG_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Home Currency Code",
            "displayFolder": "Attributes",
            "sourceColumn": "HOME_CCY_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Trading Indicator",
            "displayFolder": "Attributes",
            "sourceColumn": "TRDG_IND"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag1",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG1"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag2",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG2"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag3",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG3"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Business Date",
            "displayFolder": "Attributes",
            "sourceColumn": "BUSN_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CORPCC",
            "displayFolder": "Attributes",
            "sourceColumn": "CORPCC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CORPCC Description",
            "displayFolder": "Attributes",
            "sourceColumn": "CORPCC_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "SEG DER Leaf",
            "displayFolder": "Attributes",
            "sourceColumn": "SEG_DER_LEAF"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "SEG Description",
            "displayFolder": "Attributes",
            "sourceColumn": "SEG_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "H Group Org GRM",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_GRP_ORG_C\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_GRP_ORG_C\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "H_GRP_ORG_C"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "GWB_CROSS_BORDER_COUNTRY",
          "annotations": [{
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT VALUE_ID AS SITE_ID,CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS CTRY_CD,",
              "CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS SORT_ID,",
              "CASE WHEN VALUE_ID IN ('U1','U2') ",
              "THEN 'UNITED STATES' WHEN VALUE_ID='M2' ",
              "THEN 'MALAYSIA' ELSE DESCRIPTION END AS CTRY_NM ",
              "FROM U01_EDW_SEM_OTH_V.MST_REFERENCE_CODE_FRR WHERE CODE_NAME='Country Code'<\/RSQueryCommandText><RSQueryCommandType>Text<\/RSQueryCommandType><RSQueryDesignState><\/RSQueryDesignState>]]><\/AnnotationContent><\/Gemini>"
            ]
          }],
          "source": {
            "query": [
              "SELECT VALUE_ID AS SITE_ID,CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS CTRY_CD,",
              "CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS SORT_ID,",
              "CASE WHEN VALUE_ID IN ('U1','U2') ",
              "THEN 'UNITED STATES' WHEN VALUE_ID='M2' ",
              "THEN 'MALAYSIA' ELSE DESCRIPTION END AS CTRY_NM ",
              "FROM U01_EDW_SEM_OTH_V.MST_REFERENCE_CODE_FRR WHERE CODE_NAME='Country Code'"
            ],
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "sortByColumn": "GRM Country Sort (inout)",
            "displayFolder": "Attributes",
            "sourceColumn": "SITE_ID"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Country Code",
            "sortByColumn": "GRM Country Sort (inout)",
            "displayFolder": "Attributes",
            "sourceColumn": "CTRY_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Sort ID",
            "displayFolder": "Attributes",
            "sourceColumn": "SORT_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Country Name",
            "sortByColumn": "GRM Country Sort (inout)",
            "displayFolder": "Attributes",
            "sourceColumn": "CTRY_NM"
          },
          {
            "expression": "SWITCH ('D Country Inbound Outbound'[Sort ID], \"SG\" ,1,\"MY\" ,2,\"ID\" ,3,\"TH\" ,4,\"VN\" ,5,\"CN\" ,6,\"HK\" ,7,\"TW\" ,8,\"GB\" ,9,\"US\" ,10,\"CA\" ,11,\"AU\" ,12,\"JP\" ,13,\"KR\" ,14,\"IN\" ,15,\"MM\" ,16,\"PH\" ,17,\"BN\" ,18,123456 )",
            "name": "GRM Country Sort (inout)",
            "type": "calculated",
            "displayFolder": "Attributes",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "D Country Inbound Outbound",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": [
              "SELECT VALUE_ID AS SITE_ID,CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS CTRY_CD,",
              "CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS SORT_ID,",
              "CASE WHEN VALUE_ID IN ('U1','U2') ",
              "THEN 'UNITED STATES' WHEN VALUE_ID='M2' ",
              "THEN 'MALAYSIA' ELSE DESCRIPTION END AS CTRY_NM ",
              "FROM U01_EDW_SEM_OTH_V.MST_REFERENCE_CODE_FRR WHERE CODE_NAME='Country Code'"
            ]
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "GWB_CROSS_BORDER_COUNTRY"
          },
          {
            "name": "QueryEditorSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT VALUE_ID AS SITE_ID,CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS CTRY_CD,",
              "CASE WHEN VALUE_ID IN ('U1','U2') THEN 'US' ",
              "WHEN VALUE_ID='M2' THEN 'MY' ELSE VALUE_ID END AS SORT_ID,",
              "CASE WHEN VALUE_ID IN ('U1','U2') ",
              "THEN 'UNITED STATES' WHEN VALUE_ID='M2' ",
              "THEN 'MALAYSIA' ELSE DESCRIPTION END AS CTRY_NM ",
              "FROM U01_EDW_SEM_OTH_V.MST_REFERENCE_CODE_FRR WHERE CODE_NAME='Country Code'<\/RSQueryCommandText><RSQueryCommandType>Text<\/RSQueryCommandType><RSQueryDesignState><\/RSQueryDesignState>]]><\/AnnotationContent><\/Gemini>"
            ]
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "H_GRP_ORG_C",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_GRP_ORG_C\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_GRP_ORG_C\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 01 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_01_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 01 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_01_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 02 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_02_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 02 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_02_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 03 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_03_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 03 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_03_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 04 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_04_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 04 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_04_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 05 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_05_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 05 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_05_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 06 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_06_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 06 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_06_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 07 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_07_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 07 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_07_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 08 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_08_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 08 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_08_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Node",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_NODE"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Node Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_NODE_DESC"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Effective Date",
            "displayFolder": "Attributes",
            "sourceColumn": "EFF_DT"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Closed Date",
            "displayFolder": "Attributes",
            "sourceColumn": "CLS_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Closed Indicator",
            "displayFolder": "Attributes",
            "sourceColumn": "CLS_IND"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GW SEG DER",
            "displayFolder": "Attributes",
            "sourceColumn": "GW_SEG_DER"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GW SEG Description",
            "displayFolder": "Attributes",
            "sourceColumn": "GW_SEG_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Home Currency Code",
            "displayFolder": "Attributes",
            "sourceColumn": "HOME_CCY_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Trading Indicator",
            "displayFolder": "Attributes",
            "sourceColumn": "TRDG_IND"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag1",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG1"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag2",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG2"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag3",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG3"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Business Date",
            "displayFolder": "Attributes",
            "sourceColumn": "BUSN_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CORPCC",
            "displayFolder": "Attributes",
            "sourceColumn": "CORPCC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CORPCC Description",
            "displayFolder": "Attributes",
            "sourceColumn": "CORPCC_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "SEG DER Leaf",
            "displayFolder": "Attributes",
            "sourceColumn": "SEG_DER_LEAF"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "SEG Description",
            "displayFolder": "Attributes",
            "sourceColumn": "SEG_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "H Group Org Inbound Outbound",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_GRP_ORG_C\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_GRP_ORG_C\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "H_GRP_ORG_C"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "F_GWB_CROSS_BORDR_RPTG",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_GWB_V\".\"F_GWB_CROSS_BORDR_RPTG\".* FROM \"U01_EDW_SEM_GWB_V\".\"F_GWB_CROSS_BORDR_RPTG\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [],
        "columns": [
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "PARTY EDW ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "PRTY_EDW_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Customer Source Number",
            "displayFolder": "Attributes",
            "sourceColumn": "CUST_SRC_NUM",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Customer Source Type",
            "displayFolder": "Attributes",
            "sourceColumn": "CUST_SRC_TYPE",
            "isHidden": true
          },
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "GRM OFFICER EDW Id",
            "displayFolder": "Tech Fields",
            "sourceColumn": "GRM_OFICR_EDW_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM Country Code",
            "displayFolder": "Tech Fields",
            "sourceColumn": "GRM_CTRY_CD",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM CTO Code",
            "displayFolder": "Attributes",
            "sourceColumn": "GRM_CTO_CD",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM Group Name",
            "displayFolder": "Attributes",
            "sourceColumn": "GRM_GRP_NM",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM Cost Centre",
            "displayFolder": "Tech Fields",
            "sourceColumn": "GRM_COST_CTR",
            "isHidden": true
          },
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "FRM CTO OFFICER EDW ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "FRM_CTO_OFICR_EDW_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "FRM Country Code",
            "displayFolder": "Tech Fields",
            "sourceColumn": "FRM_CTRY_CD",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "FRM CTO Code",
            "displayFolder": "Attributes",
            "sourceColumn": "FRM_CTO_CD",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "FRM Cost Centre",
            "displayFolder": "Tech Fields",
            "sourceColumn": "FRM_COST_CTR",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Cross Border Category",
            "displayFolder": "Tech Fields",
            "sourceColumn": "CROSS_BORDR_CAT",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Scenario Cd",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SCNRO_CD",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Scenario Sub Category",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SCNRO_SUB_CAT",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Balance Type",
            "displayFolder": "Attributes",
            "sourceColumn": "BAL_TYPE",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Valuation Type",
            "displayFolder": "Tech Fields",
            "sourceColumn": "VALUT_TYPE",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Reporting Branch",
            "displayFolder": "Attributes",
            "sourceColumn": "RPTG_BR",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Reporting Cost Centre",
            "displayFolder": "Tech Fields",
            "sourceColumn": "RPTG_COST_CTR",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Currency Type Code",
            "displayFolder": "Tech Fields",
            "sourceColumn": "CCY_TYPE_CD",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Currency Code",
            "displayFolder": "Tech Fields",
            "sourceColumn": "CCY_CD",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Product COA ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "PROD_COAID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Enterprise Product Leaf Node",
            "displayFolder": "Tech Fields",
            "sourceColumn": "ENTRP_PROD_LEAf_NODE",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "Date",
            "dataType": "dateTime",
            "name": "Business Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "BUSN_DT",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "Date",
            "dataType": "dateTime",
            "name": "As of Date",
            "displayFolder": "Attributes",
            "sourceColumn": "AS_OF_DT",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Asis Aswas Category",
            "displayFolder": "Tech Fields",
            "sourceColumn": "ASIS_ASWAS_CAT",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Workspace Id",
            "displayFolder": "Attributes",
            "sourceColumn": "WRKSPC_ID",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Allowances For Credit and Other Losses",
            "displayFolder": "Measures",
            "sourceColumn": "ALLWS_FOR_CR_AND_OTH_LOSS",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Allowances For Credit and Other Losses QTD",
            "displayFolder": "Measures",
            "sourceColumn": "ALLWS_FOR_CR_AND_OTH_LOSS_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Allowances For Credit and Other Losses YTD",
            "displayFolder": "Measures",
            "sourceColumn": "ALLWS_FOR_CR_AND_OTH_LOSS_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Deposit and Balances of Non Bank Customer",
            "displayFolder": "Measures",
            "sourceColumn": "DEP_AND_BAL_OF_NON_BANK_CUST",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Deposit and Balances of Non Bank Customer QTD",
            "displayFolder": "Measures",
            "sourceColumn": "DEP_AND_BAL_OF_NON_BANK_CUST_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Deposit and Balances of Non Bank Customer YTD",
            "displayFolder": "Measures",
            "sourceColumn": "DEP_AND_BAL_OF_NON_BANK_CUST_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Deposit and Balances of Bank and Agent",
            "displayFolder": "Measures",
            "sourceColumn": "DEP_AND_BAL_OF_BANK_AND_AGN",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Deposit and Balances of Bank and Agent QTD",
            "displayFolder": "Measures",
            "sourceColumn": "DEP_AND_BAL_OF_BANK_AND_AGN_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Deposit and Balances of Bank and Agent YTD",
            "displayFolder": "Measures",
            "sourceColumn": "DEP_AND_BAL_OF_BANK_AND_AGN_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "EAD",
            "displayFolder": "Measures",
            "sourceColumn": "EAD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "EAD QTD",
            "displayFolder": "Measures",
            "sourceColumn": "EAD_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "EAD YTD",
            "displayFolder": "Measures",
            "sourceColumn": "EAD_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "ECL Stage1 and 2",
            "displayFolder": "Measures",
            "sourceColumn": "ECL_STAGE1_AND_2",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "ECL Stage1 and 2 QTD",
            "displayFolder": "Measures",
            "sourceColumn": "ECL_STAGE1_AND_2_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "ECL Stage1 and 2 YTD",
            "displayFolder": "Measures",
            "sourceColumn": "ECL_STAGE1_AND_2_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "ECL Stage3",
            "displayFolder": "Measures",
            "sourceColumn": "ECL_STAGE3",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "ECL Stage3 QTD",
            "displayFolder": "Measures",
            "sourceColumn": "ECL_STAGE3_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "ECL Stage3 YTD",
            "displayFolder": "Measures",
            "sourceColumn": "ECL_STAGE3_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "EL (P&L)",
            "displayFolder": "Measures",
            "sourceColumn": "EL_PL",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "EL (P&L) QTD",
            "displayFolder": "Measures",
            "sourceColumn": "EL_PL_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "EL (P&L) YTD",
            "displayFolder": "Measures",
            "sourceColumn": "EL_PL_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Funds Charge",
            "displayFolder": "Measures",
            "sourceColumn": "FUNDS_CHRG",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Funds Charge QTD",
            "displayFolder": "Measures",
            "sourceColumn": "FUNDS_CHRG_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Funds Charge YTD",
            "displayFolder": "Measures",
            "sourceColumn": "FUNDS_CHRG_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Funds Credit",
            "displayFolder": "Measures",
            "sourceColumn": "FUNDS_CR",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Funds Credit QTD",
            "displayFolder": "Measures",
            "sourceColumn": "FUNDS_CR_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Funds Credit YTD",
            "displayFolder": "Measures",
            "sourceColumn": "FUNDS_CR_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Gross Interest Income",
            "displayFolder": "Measures",
            "sourceColumn": "GRS_INT_INCM",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Gross Interest Income QTD",
            "displayFolder": "Measures",
            "sourceColumn": "GRS_INT_INCM_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Gross Interest Income YTD",
            "displayFolder": "Measures",
            "sourceColumn": "GRS_INT_INCM_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Gross Interest Expense",
            "displayFolder": "Measures",
            "sourceColumn": "GRS_INT_EXP",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Gross Interest Expense QTD",
            "displayFolder": "Measures",
            "sourceColumn": "GRS_INT_EXP_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Gross Interest Expense YTD",
            "displayFolder": "Measures",
            "sourceColumn": "GRS_INT_EXP_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Gross Loan",
            "displayFolder": "Measures",
            "sourceColumn": "GRS_LN",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Gross Loan QTD",
            "displayFolder": "Measures",
            "sourceColumn": "GRS_LN_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Gross Loan YTD",
            "displayFolder": "Measures",
            "sourceColumn": "GRS_LN_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Income Tax",
            "displayFolder": "Measures",
            "sourceColumn": "INCM_TAX",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Income Tax QTD",
            "displayFolder": "Measures",
            "sourceColumn": "INCM_TAX_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Income Tax YTD",
            "displayFolder": "Measures",
            "sourceColumn": "INCM_TAX_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Profit After Tax",
            "displayFolder": "Measures",
            "sourceColumn": "PRFT_AFTER_TAX",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Profit After Tax YTD",
            "displayFolder": "Measures",
            "sourceColumn": "PRFT_AFTER_TAX_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Profit After Tax QTD",
            "displayFolder": "Measures",
            "sourceColumn": "PRFT_AFTER_TAX_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Bearing Liability",
            "displayFolder": "Measures",
            "sourceColumn": "INT_BEAR_LIAB",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Bearing Liability QTD",
            "displayFolder": "Measures",
            "sourceColumn": "INT_BEAR_LIAB_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Bearing Liability YTD",
            "displayFolder": "Measures",
            "sourceColumn": "INT_BEAR_LIAB_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Bearing Asset",
            "displayFolder": "Measures",
            "sourceColumn": "INT_BEAR_ASSET",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Bearing Asset QTD",
            "displayFolder": "Measures",
            "sourceColumn": "INT_BEAR_ASSET_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Bearing Asset YTD",
            "displayFolder": "Measures",
            "sourceColumn": "INT_BEAR_ASSET_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Income",
            "displayFolder": "Measures",
            "sourceColumn": "INT_INCM",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Income QTD",
            "displayFolder": "Measures",
            "sourceColumn": "INT_INCM_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Income YTD",
            "displayFolder": "Measures",
            "sourceColumn": "INT_INCM_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Net Interest Income",
            "displayFolder": "Measures",
            "sourceColumn": "NET_INT_INCM",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Net Interest Income QTD",
            "displayFolder": "Measures",
            "sourceColumn": "NET_INT_INCM_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Net Interest Income YTD",
            "displayFolder": "Measures",
            "sourceColumn": "NET_INT_INCM_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Non Interest Income",
            "displayFolder": "Measures",
            "sourceColumn": "NON_INT_INCM",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Non Interest Income QTD",
            "displayFolder": "Measures",
            "sourceColumn": "NON_INT_INCM_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Non Interest Income YTD",
            "displayFolder": "Measures",
            "sourceColumn": "NON_INT_INCM_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Income",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_INCM",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Income QTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_INCM_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Income YTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_INCM_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Expense",
            "displayFolder": "Measures",
            "sourceColumn": "INT_EXP",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Expense QTD",
            "displayFolder": "Measures",
            "sourceColumn": "INT_EXP_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Expense YTD",
            "displayFolder": "Measures",
            "sourceColumn": "INT_EXP_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Expense",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_EXP",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Expense QTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_EXP_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Expense YTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_EXP_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Operating Profit",
            "displayFolder": "Measures",
            "sourceColumn": "OPRT_PRFT",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Operating Profit QTD",
            "displayFolder": "Measures",
            "sourceColumn": "OPRT_PRFT_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Operating Profit YTD",
            "displayFolder": "Measures",
            "sourceColumn": "OPRT_PRFT_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Placement and Balance With Bank and Agent",
            "displayFolder": "Measures",
            "sourceColumn": "PLCMT_AND_BAL_WTH_BANK_AND_AGN",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Placement and Balance With Bank and Agent QTD",
            "displayFolder": "Measures",
            "sourceColumn": "PLCMT_AND_BAL_WTH_BANK_AND_AGN_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Placement and Balance With Bank and Agent YTD",
            "displayFolder": "Measures",
            "sourceColumn": "PLCMT_AND_BAL_WTH_BANK_AND_AGN_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Profit Before Tax",
            "displayFolder": "Measures",
            "sourceColumn": "PRFT_BEF_TAX",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Profit Before Tax QTD",
            "displayFolder": "Measures",
            "sourceColumn": "PRFT_BEF_TAX_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Profit Before Tax YTD",
            "displayFolder": "Measures",
            "sourceColumn": "PRFT_BEF_TAX_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Share of Profit of Associate",
            "displayFolder": "Measures",
            "sourceColumn": "SHR_OF_PRFT_OF_ASSC",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Share of Profit of Associate QTD",
            "displayFolder": "Measures",
            "sourceColumn": "SHR_OF_PRFT_OF_ASSC_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Share of Profit of Associate YTD",
            "displayFolder": "Measures",
            "sourceColumn": "SHR_OF_PRFT_OF_ASSC_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Allowance Loan",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_ALLW_LN",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Allowance Loan QTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_ALLW_LN_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Allowance Loan YTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_ALLW_LN_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Asset",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_ASSET",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Asset QTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_ASSET_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Asset YTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_ASSET_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Liability",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_LIAB",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Liability QTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_LIAB_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Liability YTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_LIAB_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total RWA",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_RWA",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total RWA QTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_RWA_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total RWA YTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_RWA_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Market Risk RWA",
            "displayFolder": "Measures",
            "sourceColumn": "MKT_RISK_RWA",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Market Risk RWA QTD",
            "displayFolder": "Measures",
            "sourceColumn": "MKT_RISK_RWA_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Market Risk RWA YTD",
            "displayFolder": "Measures",
            "sourceColumn": "MKT_RISK_RWA_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Operation Risk RWA",
            "displayFolder": "Measures",
            "sourceColumn": "OPR_RISK_RWA",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Operation Risk RWA QTD",
            "displayFolder": "Measures",
            "sourceColumn": "OPR_RISK_RWA_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Operation Risk RWA YTD",
            "displayFolder": "Measures",
            "sourceColumn": "OPR_RISK_RWA_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Credit Risk RWA",
            "displayFolder": "Measures",
            "sourceColumn": "CR_RISK_RWA",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Credit Risk RWA QTD",
            "displayFolder": "Measures",
            "sourceColumn": "CR_RISK_RWA_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Credit Risk RWA YTD",
            "displayFolder": "Measures",
            "sourceColumn": "CR_RISK_RWA_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "RWA BBIRR",
            "displayFolder": "Measures",
            "sourceColumn": "RWA_BBIRR",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "RWA BBIRR QTD",
            "displayFolder": "Measures",
            "sourceColumn": "RWA_BBIRR_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "RWA BBIRR YTD",
            "displayFolder": "Measures",
            "sourceColumn": "RWA_BBIRR_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Core Capital Deduction RWA",
            "displayFolder": "Measures",
            "sourceColumn": "CORE_CAP_DED_RWA",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Core Capital Deduction RWA QTD",
            "displayFolder": "Measures",
            "sourceColumn": "CORE_CAP_DED_RWA_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Core Capital Deduction RWA YTD",
            "displayFolder": "Measures",
            "sourceColumn": "CORE_CAP_DED_RWA_YTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "CVA RWA",
            "displayFolder": "Measures",
            "sourceColumn": "CVA_RWA",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "CVA RWA QTD",
            "displayFolder": "Measures",
            "sourceColumn": "CVA_RWA_QTD",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "CVA RWA YTD",
            "displayFolder": "Measures",
            "sourceColumn": "CVA_RWA_YTD",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Attributes",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Attributes",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "Date",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Attributes",
            "sourceColumn": "START_DATE",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "Date",
            "dataType": "dateTime",
            "name": "End Date",
            "displayFolder": "Attributes",
            "sourceColumn": "END_DATE",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Record Deleted Flag",
            "displayFolder": "Attributes",
            "sourceColumn": "RECORD_DELETED_FLAG",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Control ID",
            "displayFolder": "Attributes",
            "sourceColumn": "CTL_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "PROCESS_NAME",
            "displayFolder": "Attributes",
            "sourceColumn": "PROCESS_NAME",
            "isHidden": true
          },
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "PROCESS_ID",
            "displayFolder": "Attributes",
            "sourceColumn": "PROCESS_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Update Process Name",
            "displayFolder": "Attributes",
            "sourceColumn": "UPDATE_PROCESS_NAME",
            "isHidden": true
          },
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "Update Process ID",
            "displayFolder": "Attributes",
            "sourceColumn": "UPDATE_PROCESS_ID",
            "isHidden": true
          },
          {
            "formatString": "Timestamp",
            "sourceProviderType": "Date",
            "dataType": "dateTime",
            "name": "Start Timestamp",
            "displayFolder": "Attributes",
            "sourceColumn": "START_TS",
            "isHidden": true
          },
          {
            "formatString": "Timestamp",
            "sourceProviderType": "Date",
            "dataType": "dateTime",
            "name": "End Timestamp",
            "displayFolder": "Attributes",
            "sourceColumn": "END_TS",
            "isHidden": true
          },
          {
            "expression": "'F GWB Cross Border Profitibality'[As of Date] & \"~\" &'F GWB Cross Border Profitibality'[GRM OFFICER EDW Id]",
            "name": "BUSS_DT_GRM_OFICR_EDW_ID",
            "type": "calculated",
            "displayFolder": "Tech Fields",
            "isHidden": true
          },
          {
            "expression": "'F GWB Cross Border Profitibality'[As of Date] & \"~\" & 'F GWB Cross Border Profitibality'[FRM CTO OFFICER EDW ID]",
            "name": "BUSS_DT_FRM_CTO_OFICR_EDW_ID",
            "type": "calculated",
            "displayFolder": "Tech Fields",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "F GWB Cross Border Profitibality",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_GWB_V\".\"F_GWB_CROSS_BORDR_RPTG\".* FROM \"U01_EDW_SEM_GWB_V\".\"F_GWB_CROSS_BORDR_RPTG\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "F_GWB_CROSS_BORDR_RPTG"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "F_GWB_CROSS_BORDR_RPTG",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_GWB_V\".\"F_GWB_CROSS_BORDR_RPTG\".* FROM \"U01_EDW_SEM_GWB_V\".\"F_GWB_CROSS_BORDR_RPTG\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM( 'F GWB Cross Border'[Total Income YTD]   )",
            "name": "YTD Total Income",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM ( [YTD Funds Charge (non- trade)] ) + SUM( [YTD Funds Charge (trade)] )",
            "name": "YTD Net Interest Income (Lending)",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM( [QTD Funds Charge (non- trade)] ) + SUM( [QTD Funds Charge (trade)] )",
            "name": "QTD Net Interest Income (Lending)",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM( [MTD Funds Charge (non- trade)]  ) +  SUM( [MTD Funds Charge (trade)] )",
            "name": "MTD Net Interest Income (Lending)",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM( [YTD Gross Interest Expense (CASA)] ) + SUM( [YTD Net Interest Income (FD & others)] )",
            "name": "YTD Net Interest Income (Funding)",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM ( [QTD Gross Interest Expense (CASA)] ) + SUM( [QTD Net Interest Income (FD & others)] )",
            "name": "QTD Net Interest Income (Funding)",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM( [MTD Gross Interest Expense (CASA)] )+  SUM( [MTD Net Interest Income (FD & others)] )",
            "name": "MTD Net Interest Income (Funding)",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM ('F GWB Cross Border'[Net Interest Income])",
            "name": "MTD Net Interest Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM ('F GWB Cross Border'[Total Income])",
            "name": "MTD Total Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM([MTD Total Loan (Gross End)]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Total Loan (Gross End)",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "sum([MTD Total Loan (Gross End)]) - [LM MTD Total Loan (Gross End)]",
            "name": "MoM MTD Total Loan (Gross End)",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM([MTD Total Deposit (End)]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Total Deposit (End)",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM([MTD Total Deposit (End)]) - [LM MTD Total Deposit (End)]",
            "name": "MoM MTD Total Deposit (End)",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM ('F GWB Cross Border'[Non Interest Income])",
            "name": "MTD Non Interest Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE( SUM ( [YTD Total RWA Average] ) ,DATEADD('D Time'[Month End Date],-12,MONTH),'D Time'[Month End Indicator]=\"Y\", ALL('D Time'))",
            "name": "LY YTD Total RWA Average",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM( 'F GWB Cross Border'[Total Income QTD] ),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Total Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Allowances For Credit and Other Losses]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Allowances For Credit and Other Losses",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Allowances For Credit and Other Losses QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Allowances For Credit and Other Losses",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Allowances For Credit and Other Losses YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Allowances For Credit and Other Losses",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Deposit and Balances of Non Bank Customer]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Deposit and Balances of Non Bank Customer",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Deposit and Balances of Non Bank Customer QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Deposit and Balances of Non Bank Customer",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Deposit and Balances of Non Bank Customer YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Deposit and Balances of Non Bank Customer",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Deposit and Balances of Bank and Agent]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Deposit and Balances of Bank and Agent",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Deposit and Balances of Bank and Agent QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Deposit and Balances of Bank and Agent",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Deposit and Balances of Bank and Agent YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Deposit and Balances of Bank and Agent",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[EAD]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD EAD",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[EAD QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD EAD",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[EAD YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD EAD",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[ECL Stage1 and 2]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD ECL Stage1 and 2",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[ECL Stage1 and 2 QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD ECL Stage1 and 2",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[ECL Stage1 and 2 YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD ECL Stage1 and 2",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[ECL Stage3]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD ECL Stage3",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[ECL Stage3 QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD ECL Stage3",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[ECL Stage3 YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD ECL Stage3",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[EL (P&L)]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD EL (P&L)",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[EL (P&L) QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD EL (P&L)",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[EL (P&L) YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD EL (P&L)",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Funds Charge]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Funds Charge",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Funds Charge QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Funds Charge",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Funds Charge YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Funds Charge",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Funds Credit]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Funds Credit",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Funds Credit QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Funds Credit",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Funds Credit YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Funds Credit",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Gross Interest Income]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Gross Interest Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Gross Interest Income QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Gross Interest Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Gross Interest Income YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Gross Interest Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Gross Interest Expense]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Gross Interest Expense",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Gross Interest Expense QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Gross Interest Expense",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Gross Interest Expense YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Gross Interest Expense",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Gross Loan]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Gross Loan",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Gross Loan QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Gross Loan",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Gross Loan YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Gross Loan",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Income Tax]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Income Tax",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Income Tax QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Income Tax",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Income Tax YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Income Tax",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Profit After Tax]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Profit After Tax",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Profit After Tax YTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Profit After Tax",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Profit After Tax QTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Profit After Tax",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Interest Bearing Liability]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Interest Bearing Liability",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Interest Bearing Liability QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Interest Bearing Liability",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Interest Bearing Liability YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Interest Bearing Liability",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Interest Bearing Asset]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Interest Bearing Asset",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Interest Bearing Asset QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Interest Bearing Asset",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Interest Bearing Asset YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Interest Bearing Asset",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Interest Income]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Interest Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Interest Income QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Interest Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Interest Income YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Interest Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Net Interest Income]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Net Interest Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Net Interest Income QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Net Interest Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Net Interest Income YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Net Interest Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Non Interest Income]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Non Interest Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Non Interest Income QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Non Interest Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Non Interest Income YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Non Interest Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Total Income]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Total Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Total Income YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Total Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Interest Expense]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Interest Expense",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Interest Expense QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Interest Expense",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Interest Expense YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Interest Expense",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Total Expense]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Total Expense",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Total Expense QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Total Expense",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Total Expense YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Total Expense",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Operating Profit]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Operating Profit",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Operating Profit QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Operating Profit",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Operating Profit YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Operating Profit",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Placement and Balance With Bank and Agent]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Placement and Balance With Bank and Agent",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Placement and Balance With Bank and Agent QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Placement and Balance With Bank and Agent",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Placement and Balance With Bank and Agent YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Placement and Balance With Bank and Agent",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Profit Before Tax]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Profit Before Tax",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Profit Before Tax QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Profit Before Tax",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Profit Before Tax YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Profit Before Tax",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Share of Profit of Associate]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Share of Profit of Associate",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Share of Profit of Associate QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Share of Profit of Associate",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Share of Profit of Associate YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Share of Profit of Associate",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Total Allowance Loan]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Total Allowance Loan",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Total Allowance Loan QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Total Allowance Loan",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Total Allowance Loan YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Total Allowance Loan",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Total Asset]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Total Asset",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Total Asset QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Total Asset",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Total Asset YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Total Asset",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Total Liability]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Total Liability",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Total Liability QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Total Liability",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Total Liability YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Total Liability",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Total RWA]),'D Time'[Calendar Date]=MTH_DT,'F GWB Cross Border'[Balance Type]=\"AVE\",'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Total RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Total RWA QTD]),'D Time'[Calendar Date]=QTR_DT,'F GWB Cross Border'[Balance Type]=\"AVE\",'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Total RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Total RWA YTD]),'D Time'[Calendar Date]=LY_DT,'F GWB Cross Border'[Balance Type]=\"AVE\",'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Total RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Market Risk RWA]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Market Risk RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Market Risk RWA QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Market Risk RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Market Risk RWA YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Market Risk RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Operation Risk RWA]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Operation Risk RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Operation Risk RWA QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Operation Risk RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Operation Risk RWA YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Operation Risk RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Credit Risk RWA]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Credit Risk RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Credit Risk RWA QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Credit Risk RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Credit Risk RWA YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Credit Risk RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[RWA BBIRR]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD RWA BBIRR",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[RWA BBIRR QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD RWA BBIRR",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[RWA BBIRR YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD RWA BBIRR",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[Core Capital Deduction RWA]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Core Capital Deduction RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Core Capital Deduction RWA QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Core Capital Deduction RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[Core Capital Deduction RWA YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Core Capital Deduction RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[CVA RWA]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD CVA RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[CVA RWA QTD]),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD CVA RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border'[CVA RWA YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD CVA RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Allowances For Credit and Other Losses]) -[LM MTD Allowances For Credit and Other Losses]",
            "name": "MoM MTD Allowances For Credit and Other Losses",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Allowances For Credit and Other Losses QTD]) - [LQ QTD Allowances For Credit and Other Losses]",
            "name": "QoQ QTD Allowances For Credit and Other Losses",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Allowances For Credit and Other Losses YTD]) - [LY YTD Allowances For Credit and Other Losses]",
            "name": "YoY YTD Allowances For Credit and Other Losses",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Deposit and Balances of Non Bank Customer]) -[LM MTD Deposit and Balances of Non Bank Customer]",
            "name": "MoM MTD Deposit and Balances of Non Bank Customer",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Deposit and Balances of Non Bank Customer QTD]) - [LQ QTD Deposit and Balances of Non Bank Customer]",
            "name": "QoQ QTD Deposit and Balances of Non Bank Customer",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Deposit and Balances of Non Bank Customer YTD]) - [LY YTD Deposit and Balances of Non Bank Customer]",
            "name": "YoY YTD Deposit and Balances of Non Bank Customer",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Deposit and Balances of Bank and Agent]) -[LM MTD Deposit and Balances of Bank and Agent]",
            "name": "MoM MTD Deposit and Balances of Bank and Agent",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Deposit and Balances of Bank and Agent QTD]) - [LQ QTD Deposit and Balances of Bank and Agent]",
            "name": "QoQ QTD Deposit and Balances of Bank and Agent",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Deposit and Balances of Bank and Agent YTD]) - [LY YTD Deposit and Balances of Bank and Agent]",
            "name": "YoY YTD Deposit and Balances of Bank and Agent",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[EAD]) -[LM MTD EAD]",
            "name": "MoM MTD EAD",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[EAD QTD]) - [LQ QTD EAD]",
            "name": "QoQ QTD EAD",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[EAD YTD]) - [LY YTD EAD]",
            "name": "YoY YTD EAD",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[ECL Stage1 and 2]) -[LM MTD ECL Stage1 and 2]",
            "name": "MoM MTD ECL Stage1 and 2",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[ECL Stage1 and 2 QTD]) - [LQ QTD ECL Stage1 and 2]",
            "name": "QoQ QTD ECL Stage1 and 2",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[ECL Stage1 and 2 YTD]) - [LY YTD ECL Stage1 and 2]",
            "name": "YoY YTD ECL Stage1 and 2",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[ECL Stage3]) -[LM MTD ECL Stage3]",
            "name": "MoM MTD ECL Stage3",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[ECL Stage3 QTD]) - [LQ QTD ECL Stage3]",
            "name": "QoQ QTD ECL Stage3",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[ECL Stage3 YTD]) - [LY YTD ECL Stage3]",
            "name": "YoY YTD ECL Stage3",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[EL (P&L)]) - [LM MTD EL (P&L)]",
            "name": "MoM MTD EL (P&L)",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[EL (P&L) QTD]) - [LQ QTD EL (P&L)]",
            "name": "QoQ QTD EL (P&L)",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[EL (P&L) YTD]) - [LY YTD EL (P&L)]",
            "name": "YoY YTD EL (P&L)",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Funds Charge]) -[LM MTD Funds Charge]",
            "name": "MoM MTD Funds Charge",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Funds Charge QTD]) - [LQ QTD Funds Charge]",
            "name": "QoQ QTD Funds Charge",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Funds Charge YTD]) - [LY YTD Funds Charge]",
            "name": "YoY YTD Funds Charge",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Funds Credit]) -[LM MTD Funds Credit]",
            "name": "MoM MTD Funds Credit",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Funds Credit QTD]) - [LQ QTD Funds Credit]",
            "name": "QoQ QTD Funds Credit",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Funds Credit YTD]) - [LY YTD Funds Credit]",
            "name": "YoY YTD Funds Credit",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Gross Interest Income]) -[LM MTD Gross Interest Income]",
            "name": "MoM MTD Gross Interest Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Gross Interest Income QTD]) - [LQ QTD Gross Interest Income]",
            "name": "QoQ QTD Gross Interest Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Gross Interest Income YTD]) - [LY YTD Gross Interest Income]",
            "name": "YoY YTD Gross Interest Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Gross Interest Expense]) -[LM MTD Gross Interest Expense]",
            "name": "MoM MTD Gross Interest Expense",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Gross Interest Expense QTD]) - [LQ QTD Gross Interest Expense]",
            "name": "QoQ QTD Gross Interest Expense",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Gross Interest Expense YTD]) - [LY YTD Gross Interest Expense]",
            "name": "YoY YTD Gross Interest Expense",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Gross Loan]) -[LM MTD Gross Loan]",
            "name": "MoM MTD Gross Loan",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Gross Loan QTD]) - [LQ QTD Gross Loan]",
            "name": "QoQ QTD Gross Loan",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Gross Loan YTD]) - [LY YTD Gross Loan]",
            "name": "YoY YTD Gross Loan",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Income Tax]) -[LM MTD Income Tax]",
            "name": "MoM MTD Income Tax",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Income Tax QTD]) -[LQ QTD Income Tax]",
            "name": "QoQ QTD Income Tax",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Income Tax YTD]) -[LY YTD Income Tax]",
            "name": "YoY YTD Income Tax",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Profit After Tax]) -[LM MTD Profit After Tax]",
            "name": "MoM MTD Profit After Tax",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Profit After Tax QTD]) - [LQ QTD Profit After Tax]",
            "name": "QoQ QTD Profit After Tax",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Profit After Tax YTD]) - [LY YTD Profit After Tax]",
            "name": "YoY YTD Profit After Tax",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Interest Bearing Liability]) -[LM MTD Interest Bearing Liability]",
            "name": "MoM MTD Interest Bearing Liability",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Interest Bearing Liability QTD]) - [LQ QTD Interest Bearing Liability]",
            "name": "QoQ QTD Interest Bearing Liability",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Interest Bearing Liability YTD]) - [LY YTD Interest Bearing Liability]",
            "name": "YoY YTD Interest Bearing Liability",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Interest Bearing Asset]) -[LM MTD Interest Bearing Asset]",
            "name": "MoM MTD Interest Bearing Asset",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Interest Bearing Asset QTD]) - [LQ QTD Interest Bearing Asset]",
            "name": "QoQ QTD Interest Bearing Asset",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Interest Bearing Asset YTD]) - [LY YTD Interest Bearing Asset]",
            "name": "YoY YTD Interest Bearing Asset",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Interest Income]) -[LM MTD Interest Income]",
            "name": "MoM MTD Interest Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Interest Income QTD]) - [LQ QTD Interest Income]",
            "name": "QoQ QTD Interest Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Interest Income YTD]) - [LY YTD Interest Income]",
            "name": "YoY YTD Interest Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Net Interest Income]) -[LM MTD Net Interest Income]",
            "name": "MoM MTD Net Interest Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Net Interest Income QTD]) - [LQ QTD Net Interest Income]",
            "name": "QoQ QTD Net Interest Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Net Interest Income YTD]) - [LY YTD Net Interest Income]",
            "name": "YoY YTD Net Interest Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Non Interest Income]) -[LM MTD Non Interest Income]",
            "name": "MoM MTD Non Interest Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Non Interest Income QTD]) - [LQ QTD Non Interest Income]",
            "name": "QoQ QTD Non Interest Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Non Interest Income YTD]) - [LY YTD Non Interest Income]",
            "name": "YoY YTD Non Interest Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Total Income]) -[LM MTD Total Income]",
            "name": "MoM MTD Total Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Total Income QTD]) - [LQ QTD Total Income]",
            "name": "QoQ QTD Total Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Total Income YTD]) - [LY YTD Total Income]",
            "name": "YoY YTD Total Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Interest Expense]) -[LM MTD Interest Expense]",
            "name": "MoM MTD Interest Expense",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Interest Expense QTD]) - [LQ QTD Interest Expense]",
            "name": "QoQ QTD Interest Expense",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Interest Expense YTD]) - [LY YTD Interest Expense]",
            "name": "YoY YTD Interest Expense",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Total Expense]) -[LM MTD Total Expense]",
            "name": "MoM MTD Total Expense",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Total Expense QTD]) - [LQ QTD Total Expense]",
            "name": "QoQ QTD Total Expense",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Total Expense YTD]) - [LY YTD Total Expense]",
            "name": "YoY YTD Total Expense",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Operating Profit]) -[LM MTD Operating Profit]",
            "name": "MoM MTD Operating Profit",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Operating Profit QTD]) -[LQ QTD Operating Profit]",
            "name": "QoQ QTD Operating Profit",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Operating Profit YTD]) - [LY YTD Operating Profit]",
            "name": "YoY YTD Operating Profit",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Placement and Balance With Bank and Agent]) -[LM MTD Placement and Balance With Bank and Agent]",
            "name": "MoM MTD Placement and Balance With Bank and Agent",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Placement and Balance With Bank and Agent QTD]) - [LQ QTD Placement and Balance With Bank and Agent]",
            "name": "QoQ QTD Placement and Balance With Bank and Agent",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Placement and Balance With Bank and Agent YTD]) - [LY YTD Placement and Balance With Bank and Agent]",
            "name": "YoY YTD Placement and Balance With Bank and Agent",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Profit Before Tax]) -[LM MTD Profit Before Tax]",
            "name": "MoM MTD Profit Before Tax",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Profit Before Tax QTD]) - [LQ QTD Profit Before Tax]",
            "name": "QoQ QTD Profit Before Tax",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Profit Before Tax YTD]) - [LY YTD Profit Before Tax]",
            "name": "YoY YTD Profit Before Tax",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Share of Profit of Associate]) -[LM MTD Share of Profit of Associate]",
            "name": "MoM MTD Share of Profit of Associate",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Share of Profit of Associate QTD]) -[LQ QTD Share of Profit of Associate]",
            "name": "QoQ QTD Share of Profit of Associate",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Share of Profit of Associate YTD]) - [LY YTD Share of Profit of Associate]",
            "name": "YoY YTD Share of Profit of Associate",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Total Allowance Loan]) -[LM MTD Total Allowance Loan]",
            "name": "MoM MTD Total Allowance Loan",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Total Allowance Loan QTD]) - [LQ QTD Total Allowance Loan]",
            "name": "QoQ QTD Total Allowance Loan",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Total Allowance Loan YTD]) - [LY YTD Total Allowance Loan]",
            "name": "YoY YTD Total Allowance Loan",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Total Asset]) -[LM MTD Total Asset]",
            "name": "MoM MTD Total Asset",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Total Asset QTD]) - [LQ QTD Total Asset]",
            "name": "QoQ QTD Total Asset",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Total Asset YTD]) - [LY YTD Total Asset]",
            "name": "YoY YTD Total Asset",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Total Liability]) -[LM MTD Total Liability]",
            "name": "MoM MTD Total Liability",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Total Liability QTD]) - [LQ QTD Total Liability]",
            "name": "QoQ QTD Total Liability",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Total Liability YTD]) - [LY YTD Total Liability]",
            "name": "YoY YTD Total Liability",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(SUM('F GWB Cross Border'[Total RWA]),'F GWB Cross Border'[Balance Type]=\"AVE\") -[LM MTD Total RWA]",
            "name": "MoM MTD Total RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(SUM('F GWB Cross Border'[Total RWA QTD]),'F GWB Cross Border'[Balance Type]=\"AVE\") - [LQ QTD Total RWA]",
            "name": "QoQ QTD Total RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(SUM('F GWB Cross Border'[Total RWA YTD]),'F GWB Cross Border'[Balance Type]=\"AVE\") - [LY YTD Total RWA]",
            "name": "YoY YTD Total RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Market Risk RWA]) -[LM MTD Market Risk RWA]",
            "name": "MoM MTD Market Risk RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Market Risk RWA QTD]) - [LQ QTD Market Risk RWA]",
            "name": "QoQ QTD Market Risk RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Market Risk RWA YTD]) - [LY YTD Market Risk RWA]",
            "name": "YoY YTD Market Risk RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Operation Risk RWA]) -[LM MTD Operation Risk RWA]",
            "name": "MoM MTD Operation Risk RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Operation Risk RWA QTD]) - [LQ QTD Operation Risk RWA]",
            "name": "QoQ QTD Operation Risk RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Operation Risk RWA YTD]) - [LY YTD Operation Risk RWA]",
            "name": "YoY YTD Operation Risk RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Credit Risk RWA]) -[LM MTD Credit Risk RWA]",
            "name": "MoM MTD Credit Risk RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Credit Risk RWA QTD]) - [LQ QTD Credit Risk RWA]",
            "name": "QoQ QTD Credit Risk RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Credit Risk RWA YTD]) - [LY YTD Credit Risk RWA]",
            "name": "YoY YTD Credit Risk RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[RWA BBIRR]) -[LM MTD RWA BBIRR]",
            "name": "MoM MTD RWA BBIRR",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[RWA BBIRR QTD]) - [LQ QTD RWA BBIRR]",
            "name": "QoQ QTD RWA BBIRR",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[RWA BBIRR YTD]) - [LY YTD RWA BBIRR]",
            "name": "YoY YTD RWA BBIRR",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Core Capital Deduction RWA]) -[LM MTD Core Capital Deduction RWA]",
            "name": "MoM MTD Core Capital Deduction RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Core Capital Deduction RWA QTD]) - [LQ QTD Core Capital Deduction RWA]",
            "name": "QoQ QTD Core Capital Deduction RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Core Capital Deduction RWA YTD]) - [LY YTD Core Capital Deduction RWA]",
            "name": "YoY YTD Core Capital Deduction RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[CVA RWA]) -[LM MTD CVA RWA]",
            "name": "MoM MTD CVA RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[CVA RWA QTD]) - [LQ QTD CVA RWA]",
            "name": "QoQ QTD CVA RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[CVA RWA YTD]) - [LY YTD CVA RWA]",
            "name": "YoY YTD CVA RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Allowances For Credit and Other Losses]) - [LM MTD Allowances For Credit and Other Losses] , [LM MTD Allowances For Credit and Other Losses])",
            "name": "MoM % MTD Allowances For Credit and Other Losses",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Allowances For Credit and Other Losses QTD]) - [LQ QTD Allowances For Credit and Other Losses] , [LQ QTD Allowances For Credit and Other Losses])",
            "name": "QoQ % QTD Allowances For Credit and Other Losses",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Allowances For Credit and Other Losses YTD]) - [LY YTD Allowances For Credit and Other Losses] , [LY YTD Allowances For Credit and Other Losses])",
            "name": "YoY % YTD Allowances For Credit and Other Losses",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Deposit and Balances of Non Bank Customer]) - [LM MTD Deposit and Balances of Non Bank Customer] , [LM MTD Deposit and Balances of Non Bank Customer])",
            "name": "MoM % MTD Deposit and Balances of Non Bank Customer",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Deposit and Balances of Non Bank Customer QTD]) - [LQ QTD Deposit and Balances of Non Bank Customer] , [LQ QTD Deposit and Balances of Non Bank Customer])",
            "name": "QoQ % QTD Deposit and Balances of Non Bank Customer",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Deposit and Balances of Non Bank Customer YTD]) - [LY YTD Deposit and Balances of Non Bank Customer] , [LY YTD Deposit and Balances of Non Bank Customer])",
            "name": "YoY % YTD Deposit and Balances of Non Bank Customer",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Deposit and Balances of Bank and Agent]) - [LM MTD Deposit and Balances of Bank and Agent] , [LM MTD Deposit and Balances of Bank and Agent])",
            "name": "MoM % MTD Deposit and Balances of Bank and Agent",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Deposit and Balances of Bank and Agent QTD]) - [LQ QTD Deposit and Balances of Bank and Agent] , [LQ QTD Deposit and Balances of Bank and Agent])",
            "name": "QoQ % QTD Deposit and Balances of Bank and Agent",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Deposit and Balances of Bank and Agent YTD]) - [LY YTD Deposit and Balances of Bank and Agent] , [LY YTD Deposit and Balances of Bank and Agent])",
            "name": "YoY % YTD Deposit and Balances of Bank and Agent",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([EAD]) - [LM MTD EAD] , [LM MTD EAD])",
            "name": "MoM % MTD EAD",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([EAD QTD]) - [LQ QTD EAD] , [LQ QTD EAD])",
            "name": "QoQ % QTD EAD",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([EAD YTD]) - [LY YTD EAD] , [LY YTD EAD])",
            "name": "YoY % YTD EAD",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([ECL Stage1 and 2]) - [LM MTD ECL Stage1 and 2] , [LM MTD ECL Stage1 and 2])",
            "name": "MoM % MTD ECL Stage1 and 2",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([ECL Stage1 and 2 QTD]) - [LQ QTD ECL Stage1 and 2] , [LQ QTD ECL Stage1 and 2])",
            "name": "QoQ % QTD ECL Stage1 and 2",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([ECL Stage1 and 2 YTD]) - [LY YTD ECL Stage1 and 2] , [LY YTD ECL Stage1 and 2])",
            "name": "YoY % YTD ECL Stage1 and 2",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([ECL Stage3]) - [LM MTD ECL Stage3] , [LM MTD ECL Stage3])",
            "name": "MoM % MTD ECL Stage3",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([ECL Stage3 QTD]) - [LQ QTD ECL Stage3] , [LQ QTD ECL Stage3])",
            "name": "QoQ % QTD ECL Stage3",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([ECL Stage3 YTD]) - [LY YTD ECL Stage3] , [LY YTD ECL Stage3])",
            "name": "YoY % YTD ECL Stage3",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([EL (P&L)]) - [LM MTD EL (P&L)] , [LM MTD EL (P&L)])",
            "name": "MoM % MTD EL (P&L)",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([EL (P&L) QTD]) - [LQ QTD EL (P&L)] , [LQ QTD EL (P&L)])",
            "name": "QoQ % QTD EL (P&L)",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([EL (P&L) YTD]) - [LY YTD EL (P&L)] , [LY YTD EL (P&L)])",
            "name": "YoY % YTD EL (P&L)",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Funds Charge]) - [LM MTD Funds Charge] , [LM MTD Funds Charge])",
            "name": "MoM % MTD Funds Charge",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Funds Charge QTD]) - [LQ QTD Funds Charge] , [LQ QTD Funds Charge])",
            "name": "QoQ % QTD Funds Charge",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Funds Charge YTD]) - [LY YTD Funds Charge] , [LY YTD Funds Charge])",
            "name": "YoY % YTD Funds Charge",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Funds Credit]) - [LM MTD Funds Credit] , [LM MTD Funds Credit])",
            "name": "MoM % MTD Funds Credit",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Funds Credit QTD]) - [LQ QTD Funds Credit] , [LQ QTD Funds Credit])",
            "name": "QoQ % QTD Funds Credit",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Funds Credit YTD]) - [LY YTD Funds Credit] , [LY YTD Funds Credit])",
            "name": "YoY % YTD Funds Credit",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Gross Interest Income]) - [LM MTD Gross Interest Income] , [LM MTD Gross Interest Income])",
            "name": "MoM % MTD Gross Interest Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Gross Interest Income QTD]) - [LQ QTD Gross Interest Income] , [LQ QTD Gross Interest Income])",
            "name": "QoQ % QTD Gross Interest Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Gross Interest Income YTD]) - [LY YTD Gross Interest Income] , [LY YTD Gross Interest Income])",
            "name": "YoY % YTD Gross Interest Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Gross Interest Expense]) - [LM MTD Gross Interest Expense] , [LM MTD Gross Interest Expense])",
            "name": "MoM % MTD Gross Interest Expense",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Gross Interest Expense QTD]) - [LQ QTD Gross Interest Expense] , [LQ QTD Gross Interest Expense])",
            "name": "QoQ % QTD Gross Interest Expense",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Gross Interest Expense YTD]) - [LY YTD Gross Interest Expense] , [LY YTD Gross Interest Expense])",
            "name": "YoY % YTD Gross Interest Expense",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Gross Loan]) - [LM MTD Gross Loan] , [LM MTD Gross Loan])",
            "name": "MoM % MTD Gross Loan",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Gross Loan QTD]) - [LQ QTD Gross Loan] , [LQ QTD Gross Loan])",
            "name": "QoQ % QTD Gross Loan",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Gross Loan YTD]) - [LY YTD Gross Loan] , [LY YTD Gross Loan])",
            "name": "YoY % YTD Gross Loan",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Income Tax]) - [LM MTD Income Tax] , [LM MTD Income Tax])",
            "name": "MoM % MTD Income Tax",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Income Tax QTD]) - [LQ QTD Income Tax] , [LQ QTD Income Tax])",
            "name": "QoQ % QTD Income Tax",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Income Tax YTD]) - [LY YTD Income Tax] , [LY YTD Income Tax])",
            "name": "YoY % YTD Income Tax",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Profit After Tax]) - [LM MTD Profit After Tax] , [LM MTD Profit After Tax])",
            "name": "MoM % MTD Profit After Tax",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Profit After Tax YTD]) - [LY YTD Profit After Tax] , [LY YTD Profit After Tax])",
            "name": "QoQ % QTD Profit After Tax",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Profit After Tax QTD]) - [LQ QTD Profit After Tax] , [LQ QTD Profit After Tax])",
            "name": "YoY % YTD Profit After Tax",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Interest Bearing Liability]) - [LM MTD Interest Bearing Liability] , [LM MTD Interest Bearing Liability])",
            "name": "MoM % MTD Interest Bearing Liability",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Interest Bearing Liability QTD]) - [LQ QTD Interest Bearing Liability] , [LQ QTD Interest Bearing Liability])",
            "name": "QoQ % QTD Interest Bearing Liability",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Interest Bearing Liability YTD]) - [LY YTD Interest Bearing Liability] , [LY YTD Interest Bearing Liability])",
            "name": "YoY % YTD Interest Bearing Liability",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Interest Bearing Asset]) - [LM MTD Interest Bearing Asset] , [LM MTD Interest Bearing Asset])",
            "name": "MoM % MTD Interest Bearing Asset",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Interest Bearing Asset QTD]) - [LQ QTD Interest Bearing Asset] , [LQ QTD Interest Bearing Asset])",
            "name": "QoQ % QTD Interest Bearing Asset",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Interest Bearing Asset YTD]) - [LY YTD Interest Bearing Asset] , [LY YTD Interest Bearing Asset])",
            "name": "YoY % YTD Interest Bearing Asset",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Interest Income]) - [LM MTD Interest Income] , [LM MTD Interest Income])",
            "name": "MoM % MTD Interest Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Interest Income QTD]) - [LQ QTD Interest Income] , [LQ QTD Interest Income])",
            "name": "QoQ % QTD Interest Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Interest Income YTD]) - [LY YTD Interest Income] , [LY YTD Interest Income])",
            "name": "YoY % YTD Interest Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Net Interest Income]) - [LM MTD Net Interest Income] , [LM MTD Net Interest Income])",
            "name": "MoM % MTD Net Interest Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Net Interest Income QTD]) - [LQ QTD Net Interest Income] , [LQ QTD Net Interest Income])",
            "name": "QoQ % QTD Net Interest Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Net Interest Income YTD]) - [LY YTD Net Interest Income] , [LY YTD Net Interest Income])",
            "name": "YoY % YTD Net Interest Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Non Interest Income]) - [LM MTD Non Interest Income] , [LM MTD Non Interest Income])",
            "name": "MoM % MTD Non Interest Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Non Interest Income QTD]) - [LQ QTD Non Interest Income] , [LQ QTD Non Interest Income])",
            "name": "QoQ % QTD Non Interest Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Non Interest Income YTD]) - [LY YTD Non Interest Income] , [LY YTD Non Interest Income])",
            "name": "YoY % YTD Non Interest Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Total Income]) - [LM MTD Total Income] , [LM MTD Total Income])",
            "name": "MoM % MTD Total Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Total Income QTD]) - [LQ QTD Total Income] , [LQ QTD Total Income])",
            "name": "QoQ % QTD Total Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Total Income YTD]) - [LY YTD Total Income] , [LY YTD Total Income])",
            "name": "YoY % YTD Total Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Interest Expense]) - [LM MTD Interest Expense] , [LM MTD Interest Expense])",
            "name": "MoM % MTD Interest Expense",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Interest Expense QTD]) - [LQ QTD Interest Expense] , [LQ QTD Interest Expense])",
            "name": "QoQ % QTD Interest Expense",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Interest Expense YTD]) - [LY YTD Interest Expense] , [LY YTD Interest Expense])",
            "name": "YoY % YTD Interest Expense",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Total Expense]) - [LM MTD Total Expense] , [LM MTD Total Expense])",
            "name": "MoM % MTD Total Expense",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Total Expense QTD]) - [LQ QTD Total Expense] , [LQ QTD Total Expense])",
            "name": "QoQ % QTD Total Expense",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Total Expense YTD]) - [LY YTD Total Expense] , [LY YTD Total Expense])",
            "name": "YoY % YTD Total Expense",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Operating Profit]) - [LM MTD Operating Profit] , [LM MTD Operating Profit])",
            "name": "MoM % MTD Operating Profit",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Operating Profit QTD]) - [LQ QTD Operating Profit] , [LQ QTD Operating Profit])",
            "name": "QoQ % QTD Operating Profit",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Operating Profit YTD]) - [LY YTD Operating Profit] , [LY YTD Operating Profit])",
            "name": "YoY % YTD Operating Profit",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Placement and Balance With Bank and Agent]) - [LM MTD Placement and Balance With Bank and Agent] , [LM MTD Placement and Balance With Bank and Agent])",
            "name": "MoM % MTD Placement and Balance With Bank and Agent",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Placement and Balance With Bank and Agent QTD]) - [LQ QTD Placement and Balance With Bank and Agent] , [LQ QTD Placement and Balance With Bank and Agent])",
            "name": "QoQ % QTD Placement and Balance With Bank and Agent",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Placement and Balance With Bank and Agent YTD]) - [LY YTD Placement and Balance With Bank and Agent] , [LY YTD Placement and Balance With Bank and Agent])",
            "name": "YoY % YTD Placement and Balance With Bank and Agent",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Profit Before Tax]) - [LM MTD Profit Before Tax] , [LM MTD Profit Before Tax])",
            "name": "MoM % MTD Profit Before Tax",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Profit Before Tax QTD]) - [LQ QTD Profit Before Tax] , [LQ QTD Profit Before Tax])",
            "name": "QoQ % QTD Profit Before Tax",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Profit Before Tax YTD]) - [LY YTD Profit Before Tax] , [LY YTD Profit Before Tax])",
            "name": "YoY % YTD Profit Before Tax",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Share of Profit of Associate]) - [LM MTD Share of Profit of Associate] , [LM MTD Share of Profit of Associate])",
            "name": "MoM % MTD Share of Profit of Associate",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Share of Profit of Associate QTD]) - [LQ QTD Share of Profit of Associate] , [LQ QTD Share of Profit of Associate])",
            "name": "QoQ % QTD Share of Profit of Associate",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Share of Profit of Associate YTD]) - [LY YTD Share of Profit of Associate] , [LY YTD Share of Profit of Associate])",
            "name": "YoY % YTD Share of Profit of Associate",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Total Allowance Loan]) - [LM MTD Total Allowance Loan] , [LM MTD Total Allowance Loan])",
            "name": "MoM % MTD Total Allowance Loan",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Total Allowance Loan QTD]) - [LQ QTD Total Allowance Loan] , [LQ QTD Total Allowance Loan])",
            "name": "QoQ % QTD Total Allowance Loan",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Total Allowance Loan YTD]) - [LY YTD Total Allowance Loan] , [LY YTD Total Allowance Loan])",
            "name": "YoY % YTD Total Allowance Loan",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Total Asset]) - [LM MTD Total Asset] , [LM MTD Total Asset])",
            "name": "MoM % MTD Total Asset",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Total Asset QTD]) - [LQ QTD Total Asset] , [LQ QTD Total Asset])",
            "name": "QoQ % QTD Total Asset",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Total Asset YTD]) - [LY YTD Total Asset] , [LY YTD Total Asset])",
            "name": "YoY % YTD Total Asset",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Total Liability]) - [LM MTD Total Liability] , [LM MTD Total Liability])",
            "name": "MoM % MTD Total Liability",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Total Liability QTD]) - [LQ QTD Total Liability] , [LQ QTD Total Liability])",
            "name": "QoQ % QTD Total Liability",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Total Liability YTD]) - [LY YTD Total Liability] , [LY YTD Total Liability])",
            "name": "YoY % YTD Total Liability",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(CALCULATE(SUM([Total RWA]),'F GWB Cross Border'[Balance Type]=\"AVE\") - [LM MTD Total RWA] , [LM MTD Total RWA])",
            "name": "MoM % MTD Total RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(CALCULATE(SUM([Total RWA QTD]),'F GWB Cross Border'[Balance Type]=\"AVE\") - [LQ QTD Total RWA] , [LQ QTD Total RWA])",
            "name": "QoQ % QTD Total RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(CALCULATE(SUM([Total RWA YTD]),'F GWB Cross Border'[Balance Type]=\"AVE\") - [LY YTD Total RWA] , [LY YTD Total RWA])",
            "name": "YoY % YTD Total RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Market Risk RWA]) - [LM MTD Market Risk RWA] , [LM MTD Market Risk RWA])",
            "name": "MoM % MTD Market Risk RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Market Risk RWA QTD]) - [LQ QTD Market Risk RWA] , [LQ QTD Market Risk RWA])",
            "name": "QoQ % QTD Market Risk RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Market Risk RWA YTD]) - [LY YTD Market Risk RWA] , [LY YTD Market Risk RWA])",
            "name": "YoY % YTD Market Risk RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Operation Risk RWA]) - [LM MTD Operation Risk RWA] , [LM MTD Operation Risk RWA])",
            "name": "MoM % MTD Operation Risk RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Operation Risk RWA QTD]) - [LQ QTD Operation Risk RWA] , [LQ QTD Operation Risk RWA])",
            "name": "QoQ % QTD Operation Risk RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Operation Risk RWA YTD]) - [LY YTD Operation Risk RWA] , [LY YTD Operation Risk RWA])",
            "name": "YoY % YTD Operation Risk RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Credit Risk RWA]) - [LM MTD Credit Risk RWA] , [LM MTD Credit Risk RWA])",
            "name": "MoM % MTD Credit Risk RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Credit Risk RWA QTD]) - [LQ QTD Credit Risk RWA] , [LQ QTD Credit Risk RWA])",
            "name": "QoQ % QTD Credit Risk RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Credit Risk RWA YTD]) - [LY YTD Credit Risk RWA] , [LY YTD Credit Risk RWA])",
            "name": "YoY % YTD Credit Risk RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([RWA BBIRR]) - [LM MTD RWA BBIRR] , [LM MTD RWA BBIRR])",
            "name": "MoM % MTD RWA BBIRR",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([RWA BBIRR QTD]) - [LQ QTD RWA BBIRR] , [LQ QTD RWA BBIRR])",
            "name": "QoQ % QTD RWA BBIRR",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([RWA BBIRR YTD]) - [LY YTD RWA BBIRR] , [LY YTD RWA BBIRR])",
            "name": "YoY % YTD RWA BBIRR",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Core Capital Deduction RWA]) - [LM MTD Core Capital Deduction RWA] , [LM MTD Core Capital Deduction RWA])",
            "name": "MoM % MTD Core Capital Deduction RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Core Capital Deduction RWA QTD]) - [LQ QTD Core Capital Deduction RWA] , [LQ QTD Core Capital Deduction RWA])",
            "name": "QoQ % QTD Core Capital Deduction RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([Core Capital Deduction RWA YTD]) - [LY YTD Core Capital Deduction RWA] , [LY YTD Core Capital Deduction RWA])",
            "name": "YoY % YTD Core Capital Deduction RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([CVA RWA]) - [LM MTD CVA RWA] , [LM MTD CVA RWA])",
            "name": "MoM % MTD CVA RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([CVA RWA QTD]) - [LQ QTD CVA RWA] , [LQ QTD CVA RWA])",
            "name": "QoQ % QTD CVA RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM([CVA RWA YTD]) - [LY YTD CVA RWA] , [LY YTD CVA RWA])",
            "name": "YoY % YTD CVA RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[MTD Total Income]*[MTD Annualizing Factor]",
            "name": "MTD Annualized Total Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE([MTD Annualized Total Income],'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Annualized Total Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[MTD Annualized Total Income] -[LM MTD Annualized Total Income]",
            "name": "MoM MTD Annualized Total Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([MTD Annualized Total Income] - [LM MTD Annualized Total Income] , [LM MTD Annualized Total Income])",
            "name": "MoM % MTD Annualized Total Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Total Income QTD])*[QTD Annualizing Factor]",
            "name": "QTD Annualized Total Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE([QTD Annualized Total Income],'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Annualized Total Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[QTD Annualized Total Income] -[LQ QTD Annualized Total Income]",
            "name": "QoQ QTD Annualized Total Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([QTD Annualized Total Income] - [LQ QTD Annualized Total Income] , [LQ QTD Annualized Total Income])",
            "name": "QoQ % QTD Annualized Total Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[YTD Total Income]*[YTD Annualizing Factor]",
            "name": "YTD Annualized Total Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE([YTD Annualized Total Income],'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Annualized Total Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[YTD Annualized Total Income] -[LY YTD Annualized Total Income]",
            "name": "YoY YTD Annualized Total Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([YTD Annualized Total Income] - [LY YTD Annualized Total Income] , [LY YTD Annualized Total Income])",
            "name": "YoY % YTD Annualized Total Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(SUM('F GWB Cross Border'[Total RWA]),'F GWB Cross Border'[Balance Type]=\"AVE\")*[MTD Annualizing Factor]",
            "name": "MTD Annualized Total RWA",
            "displayFolder": "Derived Measures\\1. Monthly",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE([MTD Annualized Total RWA],'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Annualized Total RWA",
            "displayFolder": "Derived Measures\\1. Monthly",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[MTD Annualized Total RWA] -[LM MTD Annualized Total RWA]",
            "name": "MoM MTD Annualized Total RWA",
            "displayFolder": "Derived Measures\\1. Monthly",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([MTD Annualized Total RWA] - [LM MTD Annualized Total RWA] , [LM MTD Annualized Total RWA])",
            "name": "MoM % MTD Annualized Total RWA",
            "displayFolder": "Derived Measures\\1. Monthly",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(SUM([Total RWA QTD]),'F GWB Cross Border'[Balance Type]=\"AVE\")*[QTD Annualizing Factor]",
            "name": "QTD Annualized Total RWA",
            "displayFolder": "Derived Measures\\2. Quarterly",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE([QTD Annualized Total RWA],'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Annualized Total RWA",
            "displayFolder": "Derived Measures\\2. Quarterly",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[QTD Annualized Total RWA] -[LQ QTD Annualized Total RWA]",
            "name": "QoQ QTD Annualized Total RWA",
            "displayFolder": "Derived Measures\\2. Quarterly",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([QTD Annualized Total RWA] - [LQ QTD Annualized Total RWA] , [LQ QTD Annualized Total RWA])",
            "name": "QoQ % QTD Annualized Total RWA",
            "displayFolder": "Derived Measures\\2. Quarterly",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(SUM([Total RWA YTD]),'F GWB Cross Border'[Balance Type]=\"AVE\")*[YTD Annualizing Factor]",
            "name": "YTD Annualized Total RWA",
            "displayFolder": "Derived Measures\\3. Yearly",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE([YTD Annualized Total RWA],'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Annualized Total RWA",
            "displayFolder": "Derived Measures\\3. Yearly",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[YTD Annualized Total RWA] -[LY YTD Annualized Total RWA]",
            "name": "YoY YTD Annualized Total RWA",
            "displayFolder": "Derived Measures\\3. Yearly",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([YTD Annualized Total RWA] - [LY YTD Annualized Total RWA] , [LY YTD Annualized Total RWA])",
            "name": "YoY % YTD Annualized Total RWA",
            "displayFolder": "Derived Measures\\3. Yearly",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([YTD Annualized Total Income],CALCULATE(SUM('F GWB Cross Border'[Total RWA YTD]),'F GWB Cross Border'[Balance Type]=\"AVE\"))",
            "name": "YTD Annualized Income over RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([QTD Annualized Total Income],CALCULATE(SUM('F GWB Cross Border'[Total RWA QTD]),'F GWB Cross Border'[Balance Type]=\"AVE\"))",
            "name": "QTD Annualized Income over RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([MTD Annualized Total Income],CALCULATE(SUM('F GWB Cross Border'[Total RWA]),'F GWB Cross Border'[Balance Type]=\"AVE\"))",
            "name": "MTD Annualized Income over RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([LY YTD Annualized Total Income],[LY YTD Total RWA])",
            "name": "LY YTD Annualized Income over RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([LQ QTD Annualized Total Income],[LQ QTD Total RWA])",
            "name": "LQ QTD Annualized Income over RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([LM MTD Annualized Total Income],[LM MTD Total RWA])",
            "name": "LM MTD Annualized Income over RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(sum('F GWB Cross Border'[YTD Total Loan (Gross Avg)]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Total Loan (Gross Avg)",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "sum('F GWB Cross Border'[YTD Total Loan (Gross Avg)]) -[LY YTD Total Loan (Gross Avg)]",
            "name": "YoY YTD Total Loan (Gross Avg)",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(sum('F GWB Cross Border'[YTD Total Loan (Gross Avg)]) - [LY YTD Total Loan (Gross Avg)] , [LY YTD Total Loan (Gross Avg)])",
            "name": "YoY % YTD Total Loan (Gross Avg)",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(sum('F GWB Cross Border'[YTD Total Deposit (Avg)]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Total Deposit (Avg)",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "sum('F GWB Cross Border'[YTD Total Deposit (Avg)]) -[LY YTD Total Deposit (Avg)]",
            "name": "YoY YTD Total Deposit (Avg)",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(sum('F GWB Cross Border'[YTD Total Deposit (Avg)]) - [LY YTD Total Deposit (Avg)] , [LY YTD Total Deposit (Avg)])",
            "name": "YoY % YTD Total Deposit (Avg)",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(sum('F GWB Cross Border'[MTD Total Loan (Gross Avg)]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Total Loan (Gross Avg)",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "sum('F GWB Cross Border'[MTD Total Loan (Gross Avg)]) - [LM MTD Total Loan (Gross Avg)]",
            "name": "MoM MTD Total Loan (Gross Avg)",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(sum('F GWB Cross Border'[MTD Total Loan (Gross Avg)]) -[LM MTD Total Loan (Gross Avg)] , [LM MTD Total Loan (Gross Avg)])",
            "name": "MoM % MTD Total Loan (Gross Avg)",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border'[MTD Total Deposit (Avg)]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Total Deposit (Avg)",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[MTD Total Deposit (Avg)]) - [LM MTD Total Deposit (Avg)]",
            "name": "MoM MTD Total Deposit (Avg)",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE(SUM('F GWB Cross Border'[MTD Total Deposit (Avg)]) -[LM MTD Total Deposit (Avg)] , [LM MTD Total Deposit (Avg)])",
            "name": "MoM % MTD Total Deposit (Avg)",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border Profitibality'[Total RWA]),'F GWB Cross Border Profitibality'[Balance Type]=\"AVE\",'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Total RWA (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM('F GWB Cross Border Profitibality'[Total RWA QTD]),'F GWB Cross Border Profitibality'[Balance Type]=\"AVE\",'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Total RWA (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border Profitibality'[Total RWA YTD]),'F GWB Cross Border Profitibality'[Balance Type]=\"AVE\",'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Total RWA (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM ('F GWB Cross Border Profitibality'[Total Income])",
            "name": "MTD Total Income (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[MTD Total Income (Outbound)]*[MTD Annualizing Factor]",
            "name": "MTD Annualized Total Income (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE([MTD Annualized Total Income (Outbound)],'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Annualized Total Income (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border Profitibality'[Total Income QTD])*[QTD Annualizing Factor]",
            "name": "QTD Annualized Total Income (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE([QTD Annualized Total Income (Outbound)],'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Annualized Total Income (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM( 'F GWB Cross Border Profitibality'[Total Income YTD]   )",
            "name": "YTD Total Income (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[YTD Total Income (Outbound)]*[YTD Annualizing Factor]",
            "name": "YTD Annualized Total Income (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE([YTD Annualized Total Income (Outbound)],'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Annualized Total Income (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([YTD Annualized Total Income (Outbound)],[YTD Total RWA (Outbound)])",
            "name": "YTD Annualized Income over RWA (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([QTD Annualized Total Income (Outbound)],[QTD Total RWA (Outbound)])",
            "name": "QTD Annualized Income over RWA (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([MTD Annualized Total Income (Outbound)],[MTD Total RWA (Outbound)])",
            "name": "MTD Annualized Income over RWA (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([LY YTD Annualized Total Income (Outbound)],[LY YTD Total RWA (Outbound)])",
            "name": "LY YTD Annualized Income over RWA (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([LQ QTD Annualized Total Income (Outbound)],[LQ QTD Total RWA (Outbound)])",
            "name": "LQ QTD Annualized Income over RWA (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([LM MTD Annualized Total Income (Outbound)],[LM MTD Total RWA (Outbound)])",
            "name": "LM MTD Annualized Income over RWA (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(SUM('F GWB Cross Border Profitibality'[Total RWA YTD]),'F GWB Cross Border Profitibality'[Balance Type]=\"AVE\")",
            "name": "YTD Total RWA (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(SUM('F GWB Cross Border Profitibality'[Total RWA]),'F GWB Cross Border Profitibality'[Balance Type]=\"AVE\")",
            "name": "MTD Total RWA (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(SUM('F GWB Cross Border Profitibality'[Total RWA QTD]),'F GWB Cross Border Profitibality'[Balance Type]=\"AVE\")",
            "name": "QTD Total RWA (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE(SUM('F GWB Cross Border Profitibality'[Total Income YTD]),'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Total Income (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE(SUM('F GWB Cross Border Profitibality'[Total Income]),'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Total Income (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border Profitibality'[Total Income QTD])",
            "name": "QTD Total Income (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE(SUM( 'F GWB Cross Border Profitibality'[Total Income QTD] ),'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Total Income (Outbound)",
            "displayFolder": "Derived Measures\\Outbound"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(sum('F GWB Cross Border'[Total Income YTD]),'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "YTD Total X-Border Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(sum('F GWB Cross Border Profitibality'[Total Income YTD]),'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "YTD Total X-Border Income GRM persp",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Total Income YTD])",
            "name": "YTD Total In-country Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[YTD Total In-country Income]+[YTD Total X-Border Income GRM persp]",
            "name": "YTD Total In-country & X-Border Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([YTD Total X-Border Income GRM persp],[YTD Total In-country & X-Border Income])",
            "name": "YTD Total X-Border Income as a % of Total In-country & X-Border Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "CALCULATE([YTD Annualized Income over RWA (Outbound)],'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "YTD Total X-Border Income / Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "CALCULATE([YTD Annualized Income over RWA],'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "YTD Total X-Border Income / Avg RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(sum('F GWB Cross Border Profitibality'[Total RWA YTD]),'F GWB Cross Border Profitibality'[Balance Type]=\"AVE\",'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "YTD Total X-Border Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([YTD Total X-Border Avg RWA GRM persp],[YTD Total In-country & X-Border Avg RWA])",
            "name": "YTD Total X-Border Avg RWA as a % of Total In-country & X-Border Avg RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(sum('F GWB Cross Border'[Total RWA YTD]),'F GWB Cross Border'[Balance Type]=\"AVE\",'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "YTD Total X-Border Avg RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE([YTD Annualized Total Income],'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "YTD Total X-Border Annualized Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "[YTD Annualized Income over RWA (Avg)]",
            "name": "YTD Total In-country Income / Avg RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE((CALCULATE([YTD Annualized Total Income (Outbound)],'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\"||'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")+[YTD Annualized Total Income]),[YTD Total In-country & X-Border Avg RWA])",
            "name": "YTD Total In-country & X-Border Income / Avg RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "[YTD Total In-country Income / Avg RWA] - [YTD Total In-country & X-Border Income / Avg RWA]",
            "name": "YTD Total In-country Return vs. Total In-country & X-Border Return",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[YTD Total X-Border Income] - [YTD Total X-Border Income GRM persp]",
            "name": "YTD In-country Income from GRM Franchise (In-Bound) less: X-Border Income (Outbound)",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "[YTD Total X-Border Income / Avg RWA] - [YTD Total X-Border Income / Avg RWA GRM persp]",
            "name": "YTD In-country Income / Avg RWA from GRM Franchise (In-Bound) less: X-Border Income / Avg RWA (Outbound)",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[YTD Total X-Border Avg RWA] -[YTD Total X-Border Avg RWA GRM persp]",
            "name": "YTD In-country Avg RWA from GRM Franchise (In-Bound) less: X-Border Avg RWA (Outbound)",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([YTD Total X-Border Income], [YTD Total In-country Income])",
            "name": "YTD % of In-country Income from GRM Franchise",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([YTD Total X-Border Avg RWA] , CALCULATE(sum('F GWB Cross Border'[Total RWA YTD]),'F GWB Cross Border'[Balance Type]=\"AVE\"))",
            "name": "YTD % of In-country Avg RWA from GRM Franchise",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([YTD Total X-Border Income GRM persp],[LY YTD Total X-Border Income GRM persp])",
            "name": "YoY % Total X-Border Income GRM persp",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([YTD Total X-Border Income / Avg RWA GRM persp],[LY YTD Total X-Border Income / Avg RWA GRM persp])",
            "name": "YoY % Total X-Border Income / Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "CALCULATE([YoY % YTD Total Income] , 'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "YoY % Total X-Border Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([YTD Total X-Border Avg RWA GRM persp],[LY YTD Total X-Border Avg RWA GRM persp])",
            "name": "YoY % Total X-Border Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "CALCULATE([YoY % YTD Total RWA] ,'F GWB Cross Border'[Balance Type]=\"AVE\",'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "YoY % Total X-Border Avg RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "CALCULATE(DIVIDE([YoY % YTD Annualized Total Income] , [YoY % YTD Total RWA (Avg)]),'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "YoY % YTD Income / RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(sum('F GWB Cross Border'[Total Income QTD]),'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "QTD Total X-Border Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(sum('F GWB Cross Border Profitibality'[Total Income QTD]),'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "QTD Total X-Border Income GRM persp",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Total Income QTD])",
            "name": "QTD Total In-country Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(sum('F GWB Cross Border Profitibality'[Total Income QTD]),'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")+SUM('F GWB Cross Border'[Total Income QTD])",
            "name": "QTD Total In-country & X-Border Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([QTD Total X-Border Income GRM persp],[QTD Total In-country & X-Border Income])",
            "name": "QTD Total X-Border Income as a % of Total In-country & X-Border Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "CALCULATE([QTD Annualized Income over RWA (Outbound)],'F GWB Cross Border Profitibality'[Balance Type]=\"AVE\",'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "QTD Total X-Border Income / Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "CALCULATE([QTD Annualized Income over RWA],'F GWB Cross Border'[Balance Type]=\"AVE\",'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "QTD Total X-Border Income / Avg RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(sum('F GWB Cross Border Profitibality'[Total RWA QTD]),'F GWB Cross Border Profitibality'[Balance Type]=\"AVE\",'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "QTD Total X-Border Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(sum('F GWB Cross Border Profitibality'[Total RWA QTD]),'F GWB Cross Border Profitibality'[Balance Type]=\"AVE\",'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")+CALCULATE(SUM('F GWB Cross Border'[Total RWA QTD]),'F GWB Cross Border Profitibality'[Balance Type]=\"AVE\")",
            "name": "QTD Total In-country & X-Border Avg RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([QTD Total X-Border Avg RWA GRM persp],[QTD Total In-country & X-Border Avg RWA])",
            "name": "QTD Total X-Border Avg RWA as a % of Total In-country & X-Border Avg RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(sum('F GWB Cross Border'[Total RWA QTD]),'F GWB Cross Border'[Balance Type]=\"AVE\",'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "QTD Total X-Border Avg RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE([QTD Annualized Total Income],'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "QTD Total X-Border Annualized Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "[QTD Annualized Income over RWA (Avg)]",
            "name": "QTD Total In-country Income / Avg RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE((CALCULATE([QTD Annualized Total Income (Outbound)],'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\"||'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\") +[QTD Annualized Total Income]),[QTD Total In-country & X-Border Avg RWA])",
            "name": "QTD Total In-country & X-Border Income / Avg RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "[QTD Total In-country Income / Avg RWA] - [QTD Total In-country & X-Border Income / Avg RWA]",
            "name": "QTD Total In-country Return vs. Total In-country & X-Border Return",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[QTD Total X-Border Income]-[QTD Total X-Border Income GRM persp]",
            "name": "QTD In-country Income from GRM Franchise (In-Bound) less: X-Border Income (Outbound)",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "[QTD Total X-Border Income / Avg RWA] - [QTD Total X-Border Income / Avg RWA GRM persp]",
            "name": "QTD In-country Income / Avg RWA from GRM Franchise (In-Bound) less: X-Border Income / Avg RWA (Outbound)",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[QTD Total X-Border Avg RWA]-[QTD Total X-Border Avg RWA GRM persp]",
            "name": "QTD In-country Avg RWA from GRM Franchise (In-Bound) less: X-Border Avg RWA (Outbound)",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([QTD Total X-Border Income], [QTD Total In-country Income])",
            "name": "QTD % of In-country Income from GRM Franchise",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([QTD Total X-Border Avg RWA],CALCULATE(SUM('F GWB Cross Border'[Total RWA QTD]),'F GWB Cross Border'[Balance Type]=\"AVE\"))",
            "name": "QTD % of In-country Avg RWA from GRM Franchise",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([QTD Total X-Border Income GRM persp],[LQ QTD Total X-Border Income GRM persp])",
            "name": "QoQ % Total X-Border Income GRM persp",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([QTD Total X-Border Income / Avg RWA GRM persp],[LQ QTD Total X-Border Income / Avg RWA GRM persp])",
            "name": "QoQ % Total X-Border Income / Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "CALCULATE([QoQ % QTD Total Income] , 'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "QoQ % Total X-Border Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([QTD Total X-Border Avg RWA GRM persp],[LQ QTD Total X-Border Avg RWA GRM persp])",
            "name": "QoQ % Total X-Border Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "CALCULATE([QoQ % QTD Total RWA] ,'F GWB Cross Border'[Balance Type]=\"AVE\",'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "QoQ % Total X-Border Avg RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "CALCULATE(DIVIDE([QoQ % QTD Annualized Total Income] , [QoQ % QTD Total RWA (Avg)]),'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "QoQ % QTD Income / RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(sum('F GWB Cross Border'[Total Income]),'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "MTD Total X-Border Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(sum('F GWB Cross Border Profitibality'[Total Income]),'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "MTD Total X-Border Income GRM persp",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "SUM('F GWB Cross Border'[Total Income])",
            "name": "MTD Total In-country Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(sum('F GWB Cross Border Profitibality'[Total Income]),'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")+SUM('F GWB Cross Border'[Total Income])",
            "name": "MTD Total In-country & X-Border Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([MTD Total X-Border Income GRM persp],[MTD Total In-country & X-Border Income])",
            "name": "MTD Total X-Border Income as a % of Total In-country & X-Border Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "CALCULATE([MTD Annualized Income over RWA (Outbound)],'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "MTD Total X-Border Income / Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "CALCULATE([MTD Annualized Income over RWA],'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "MTD Total X-Border Income / Avg RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(sum('F GWB Cross Border Profitibality'[Total RWA]),'F GWB Cross Border Profitibality'[Balance Type]=\"AVE\",'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "MTD Total X-Border Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(sum('F GWB Cross Border Profitibality'[Total RWA]),'F GWB Cross Border Profitibality'[Balance Type]=\"AVE\",'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")+CALCULATE(SUM('F GWB Cross Border'[Total RWA]),'F GWB Cross Border'[Balance Type]=\"AVE\")",
            "name": "MTD Total In-country & X-Border Avg RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([MTD Total X-Border Avg RWA GRM persp],[MTD Total In-country & X-Border Avg RWA])",
            "name": "MTD Total X-Border Avg RWA as a % of Total In-country & X-Border Avg RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(sum('F GWB Cross Border'[Total RWA]),'F GWB Cross Border'[Balance Type]=\"AVE\",'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "MTD Total X-Border Avg RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE([MTD Annualized Total Income],'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "MTD Total X-Border Annualized Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "[MTD Annualized Income over RWA (Avg)]",
            "name": "MTD Total In-country Income / Avg RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE((CALCULATE([MTD Annualized Total Income (Outbound)],'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\") +[MTD Annualized Total Income]),[MTD Total In-country & X-Border Avg RWA])",
            "name": "MTD Total In-country & X-Border Income / Avg RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "[MTD Total In-country Income / Avg RWA] - [MTD Total In-country & X-Border Income / Avg RWA]",
            "name": "MTD Total In-country Return vs. Total In-country & X-Border Return",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[MTD Total X-Border Income]-[MTD Total X-Border Income GRM persp]",
            "name": "MTD In-country Income from GRM Franchise (In-Bound) less: X-Border Income (Outbound)",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[MTD Total X-Border Avg RWA]-[MTD Total X-Border Avg RWA GRM persp]",
            "name": "MTD In-country Avg RWA from GRM Franchise (In-Bound) less: X-Border Avg RWA (Outbound)",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([MTD Total X-Border Income], [MTD Total In-country Income])",
            "name": "MTD % of In-country Income from GRM Franchise",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([MTD Total X-Border Income GRM persp],[LM MTD Total X-Border Income GRM persp])",
            "name": "MoM % Total X-Border Income GRM persp",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([MTD Total X-Border Income / Avg RWA GRM persp],[LM MTD Total X-Border Income / Avg RWA GRM persp])",
            "name": "MoM % Total X-Border Income / Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "CALCULATE([MoM % MTD Total Income] , 'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "MoM % Total X-Border Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([MTD Total X-Border Avg RWA GRM persp],[LM MTD Total X-Border Avg RWA GRM persp])",
            "name": "MoM % Total X-Border Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "CALCULATE([MoM % MTD Total RWA (Avg)] ,'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "MoM % Total X-Border Avg RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "CALCULATE(DIVIDE([MoM % MTD Annualized Total Income] , [MoM % MTD Total RWA (Avg)]),'D Cross Border Category'[Cross Border Category Code]=\"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code]=\"2-Cross Segment\")",
            "name": "MoM % MTD Income / RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE([YTD Total X-Border Income],'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Total X-border Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE([MTD Total X-Border Income],'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Total X-border Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE([QTD Total X-Border Income],'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Total X-border Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE([YTD Total X-Border Avg RWA],'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Total X-border Avg RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE([MTD Total X-Border Avg RWA],'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Total X-border Avg RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE([QTD Total X-Border Avg RWA],'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Total X-border Avg RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE([YTD Total X-Border Income / Avg RWA],'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Total X-border Income/Avg RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE([MTD Total X-Border Income / Avg RWA],'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Total X-border Income/Avg RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE([QTD Total X-Border Income / Avg RWA],'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Total X-border Income/Avg RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[YTD Total X-Border Income]-[LY YTD Total X-border Income]",
            "name": "YoY YTD Total X-border Income",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[QTD Total X-Border Income]-[LQ QTD Total X-border Income]",
            "name": "QoQ QTD Total X-border Income",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[MTD Total X-Border Income]-[LM MTD Total X-border Income]",
            "name": "MoM MTD Total X-border Income",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[YTD Total X-Border Avg RWA]-[LY YTD Total X-border Avg RWA]",
            "name": "YoY YTD Total X-border Avg RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[QTD Total X-Border Avg RWA]-[LQ QTD Total X-border Avg RWA]",
            "name": "QoQ QTD Total X-border Avg RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "[MTD Total X-Border Avg RWA]-[LM MTD Total X-border Avg RWA]",
            "name": "MoM MTD Total X-border Avg RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "[YTD Total X-Border Income / Avg RWA]-[LY YTD Total X-border Income/Avg RWA]",
            "name": "YoY YTD Total X-border Income/Avg RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "[MTD Total X-Border Income / Avg RWA]-[LM MTD Total X-border Income/Avg RWA]",
            "name": "MoM MTD Total X-border Income/Avg RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "[QTD Total X-Border Income / Avg RWA]-[LQ QTD Total X-border Income/Avg RWA]",
            "name": "QoQ QTD Total X-border Income/Avg RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE([MTD Total X-Border Avg RWA GRM persp],'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Total X-Border Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE([MTD Total X-Border Income / Avg RWA GRM persp],'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Total X-Border Income / Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE([MTD Total X-Border Income GRM persp],'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LM MTD Total X-Border Income GRM persp",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var MTH_DT = MAX('D Time'[Previous Month End Date]) RETURN  CALCULATE([QTD Total X-Border Avg RWA GRM persp],'D Time'[Calendar Date]=MTH_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Total X-Border Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE([QTD Total X-Border Income / Avg RWA GRM persp],'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Total X-Border Income / Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var QTR_DT = MAX('D Time'[Previous Quarter End Date]) RETURN CALCULATE([QTD Total X-Border Income GRM persp],'D Time'[Calendar Date]=QTR_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LQ QTD Total X-Border Income GRM persp",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE([YTD Total X-Border Avg RWA GRM persp],'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Total X-Border Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE([YTD Total X-Border Income / Avg RWA GRM persp],'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Total X-Border Income / Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "Var LY_DT = MAX('D Time'[Previous Year Month End Date]) RETURN CALCULATE([YTD Total X-Border Income GRM persp],'D Time'[Calendar Date]=LY_DT,'D Time'[Month End Indicator]=\"Y\",ALL('D Time'))",
            "name": "LY YTD Total X-Border Income GRM persp",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(SUM('F GWB Cross Border'[Total RWA YTD]),'F GWB Cross Border'[Balance Type]=\"AVE\")+[YTD Total X-Border Avg RWA GRM persp]",
            "name": "YTD Total In-country & X-Border Avg RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "[MTD Total X-Border Income / Avg RWA] - [MTD Total X-Border Income / Avg RWA GRM persp]",
            "name": "MTD In-country Income / Avg RWA from GRM Franchise (In-Bound) less: X-Border Income / Avg RWA (Outbound)",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([MTD Total X-Border Avg RWA] ,CALCULATE(sum('F GWB Cross Border'[Total RWA]),'F GWB Cross Border'[Balance Type]=\"AVE\"))",
            "name": "MTD % of In-country Avg RWA from GRM Franchise",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([YTD Total RWA (Outbound)],[LY YTD Total RWA (Outbound)])",
            "name": "YTD X-Border Vs LY YTD % RWA",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([QTD Total RWA (Outbound)],[LQ QTD Total RWA (Outbound)])",
            "name": "QTD X-Border Vs LQ QTD % RWA",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([MTD Total RWA (Outbound)],[LM MTD Total RWA (Outbound)])",
            "name": "MTD X-Border Vs LM MTD % RWA",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(('F GWB Cross Border'[YTD Total Income (Outbound)])) + CALCULATE(('F GWB Cross Border'[YTD Total Income (Outbound)]),  ('D Cross Border Category'[Cross Border Category Code] = \"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code] = \"2-Cross Segment\" ))",
            "name": "YTD Total In-country & X-Border Income GRM persp",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(('F GWB Cross Border'[YTD Total RWA (Outbound)])) + CALCULATE(('F GWB Cross Border'[YTD Total Income (Outbound)]),  ('D Cross Border Category'[Cross Border Category Code] = \"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code] = \"2-Cross Segment\" ))",
            "name": "YTD Total In-country & X-Border Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([YTD Total X-Border Income GRM persp],[YTD Total In-country & X-Border Income GRM persp])",
            "name": "YTD Total X-Border Income as a % of Total In-country & X-Border Income GRM persp",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([YTD Total X-Border Avg RWA GRM persp],[YTD Total In-country & X-Border Avg RWA GRM persp])",
            "name": "YTD Total X-Border Income as a % of Total In-country & X-Border Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(('F GWB Cross Border'[QTD Total Income (Outbound)])) + CALCULATE(('F GWB Cross Border'[QTD Total Income (Outbound)]),  ('D Cross Border Category'[Cross Border Category Code] = \"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code] = \"2-Cross Segment\" ))",
            "name": "QTD Total In-country & X-Border Income GRM persp",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(('F GWB Cross Border'[QTD Total RWA (Outbound)])) + CALCULATE(('F GWB Cross Border'[QTD Total Income (Outbound)]),  ('D Cross Border Category'[Cross Border Category Code] = \"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code] = \"2-Cross Segment\" ))",
            "name": "QTD Total In-country & X-Border Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([QTD Total X-Border Income GRM persp],[QTD Total In-country & X-Border Income GRM persp])",
            "name": "QTD Total X-Border Income as a % of Total In-country & X-Border Income GRM persp",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([QTD Total X-Border Avg RWA GRM persp],[QTD Total In-country & X-Border Avg RWA GRM persp])",
            "name": "QTD Total X-Border Income as a % of Total In-country & X-Border Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(('F GWB Cross Border'[MTD Total Income (Outbound)])) + CALCULATE(('F GWB Cross Border'[MTD Total Income (Outbound)]),  ('D Cross Border Category'[Cross Border Category Code] = \"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code] = \"2-Cross Segment\" ))",
            "name": "MTD Total In-country & X-Border Income GRM persp",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "CALCULATE(('F GWB Cross Border'[MTD Total RWA (Outbound)])) + CALCULATE(('F GWB Cross Border'[MTD Total Income (Outbound)]),  ('D Cross Border Category'[Cross Border Category Code] = \"1-Cross Border\" || 'D Cross Border Category'[Cross Border Category Code] = \"2-Cross Segment\" ))",
            "name": "MTD Total In-country & X-Border Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([MTD Total X-Border Income GRM persp],[MTD Total In-country & X-Border Income GRM persp])",
            "name": "MTD Total X-Border Income as a % of Total In-country & X-Border Income GRM persp",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000 %;-#,0.000000 %;#,0.000000 %",
            "expression": "DIVIDE([MTD Total X-Border Avg RWA GRM persp],[MTD Total In-country & X-Border Avg RWA GRM persp])",
            "name": "MTD Total X-Border Income as a % of Total In-country & X-Border Avg RWA GRM persp",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "expression": "CALCULATE([YoY % YTD Total RWA],'F GWB Cross Border'[Balance Type]=\"AVE\")",
            "name": "YoY % YTD Total RWA (Avg)",
            "isHidden": true
          },
          {
            "expression": "CALCULATE([QoQ % QTD Total RWA],'F GWB Cross Border'[Balance Type]=\"AVE\")",
            "name": "QoQ % QTD Total RWA (Avg)",
            "isHidden": true
          },
          {
            "expression": "CALCULATE([MoM % MTD Total RWA],'F GWB Cross Border'[Balance Type]=\"AVE\")",
            "name": "MoM % MTD Total RWA (Avg)",
            "isHidden": true
          },
          {
            "expression": "DIVIDE([YTD Annualized Total Income],CALCULATE(SUM('F GWB Cross Border'[Total RWA YTD]),'F GWB Cross Border'[Balance Type]=\"AVE\"))",
            "name": "YTD Annualized Income over RWA (Avg)",
            "isHidden": true
          },
          {
            "expression": "DIVIDE([YTD Annualized Total Income],CALCULATE(SUM('F GWB Cross Border'[Total RWA QTD]),'F GWB Cross Border'[Balance Type]=\"AVE\"))",
            "name": "QTD Annualized Income over RWA (Avg)",
            "isHidden": true
          },
          {
            "expression": "DIVIDE([YTD Annualized Total Income],CALCULATE(SUM('F GWB Cross Border'[Total RWA]),'F GWB Cross Border'[Balance Type]=\"AVE\"))",
            "name": "MTD Annualized Income over RWA (Avg)",
            "isHidden": true
          }
        ],
        "hierarchies": [],
        "columns": [
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "PARTY EDW ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "PRTY_EDW_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Customer Source Number",
            "displayFolder": "Attributes",
            "sourceColumn": "CUST_SRC_NUM"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Customer Source Type",
            "displayFolder": "Attributes",
            "sourceColumn": "CUST_SRC_TYPE"
          },
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "GRM OFFICER EDW Id",
            "displayFolder": "Tech Fields",
            "sourceColumn": "GRM_OFICR_EDW_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM Country Code",
            "displayFolder": "Tech Fields",
            "sourceColumn": "GRM_CTRY_CD",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM CTO Code",
            "displayFolder": "Attributes",
            "sourceColumn": "GRM_CTO_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM Group Name",
            "displayFolder": "Attributes",
            "sourceColumn": "GRM_GRP_NM"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM Cost Centre",
            "displayFolder": "Tech Fields",
            "sourceColumn": "GRM_COST_CTR",
            "isHidden": true
          },
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "FRM CTO OFFICER EDW ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "FRM_CTO_OFICR_EDW_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "FRM Country Code",
            "displayFolder": "Tech Fields",
            "sourceColumn": "FRM_CTRY_CD",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "FRM CTO Code",
            "displayFolder": "Attributes",
            "sourceColumn": "FRM_CTO_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "FRM Cost Centre",
            "displayFolder": "Tech Fields",
            "sourceColumn": "FRM_COST_CTR",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Cross Border Category",
            "displayFolder": "Tech Fields",
            "sourceColumn": "CROSS_BORDR_CAT",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Scenario Cd",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SCNRO_CD",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Scenario Sub Category",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SCNRO_SUB_CAT",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Balance Type",
            "displayFolder": "Attributes",
            "sourceColumn": "BAL_TYPE"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Valuation Type",
            "displayFolder": "Tech Fields",
            "sourceColumn": "VALUT_TYPE",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Reporting Branch",
            "displayFolder": "Attributes",
            "sourceColumn": "RPTG_BR"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Reporting Cost Centre",
            "displayFolder": "Tech Fields",
            "sourceColumn": "RPTG_COST_CTR",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Currency Type Code",
            "displayFolder": "Tech Fields",
            "sourceColumn": "CCY_TYPE_CD",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Currency Code",
            "displayFolder": "Tech Fields",
            "sourceColumn": "CCY_CD",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Product COA ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "PROD_COAID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Enterprise Product Leaf Node",
            "displayFolder": "Tech Fields",
            "sourceColumn": "ENTRP_PROD_LEAf_NODE",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "Date",
            "dataType": "dateTime",
            "name": "Business Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "BUSN_DT",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "Date",
            "dataType": "dateTime",
            "name": "As of Date",
            "displayFolder": "Attributes",
            "sourceColumn": "AS_OF_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Asis Aswas Category",
            "displayFolder": "Tech Fields",
            "sourceColumn": "ASIS_ASWAS_CAT",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Workspace Id",
            "displayFolder": "Attributes",
            "sourceColumn": "WRKSPC_ID",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Allowances For Credit and Other Losses",
            "displayFolder": "Measures",
            "sourceColumn": "ALLWS_FOR_CR_AND_OTH_LOSS"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Allowances For Credit and Other Losses QTD",
            "displayFolder": "Measures",
            "sourceColumn": "ALLWS_FOR_CR_AND_OTH_LOSS_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Allowances For Credit and Other Losses YTD",
            "displayFolder": "Measures",
            "sourceColumn": "ALLWS_FOR_CR_AND_OTH_LOSS_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Deposit and Balances of Non Bank Customer",
            "displayFolder": "Measures",
            "sourceColumn": "DEP_AND_BAL_OF_NON_BANK_CUST"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Deposit and Balances of Non Bank Customer QTD",
            "displayFolder": "Measures",
            "sourceColumn": "DEP_AND_BAL_OF_NON_BANK_CUST_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Deposit and Balances of Non Bank Customer YTD",
            "displayFolder": "Measures",
            "sourceColumn": "DEP_AND_BAL_OF_NON_BANK_CUST_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Deposit and Balances of Bank and Agent",
            "displayFolder": "Measures",
            "sourceColumn": "DEP_AND_BAL_OF_BANK_AND_AGN"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Deposit and Balances of Bank and Agent QTD",
            "displayFolder": "Measures",
            "sourceColumn": "DEP_AND_BAL_OF_BANK_AND_AGN_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Deposit and Balances of Bank and Agent YTD",
            "displayFolder": "Measures",
            "sourceColumn": "DEP_AND_BAL_OF_BANK_AND_AGN_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "EAD",
            "displayFolder": "Measures",
            "sourceColumn": "EAD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "EAD QTD",
            "displayFolder": "Measures",
            "sourceColumn": "EAD_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "EAD YTD",
            "displayFolder": "Measures",
            "sourceColumn": "EAD_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "ECL Stage1 and 2",
            "displayFolder": "Measures",
            "sourceColumn": "ECL_STAGE1_AND_2"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "ECL Stage1 and 2 QTD",
            "displayFolder": "Measures",
            "sourceColumn": "ECL_STAGE1_AND_2_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "ECL Stage1 and 2 YTD",
            "displayFolder": "Measures",
            "sourceColumn": "ECL_STAGE1_AND_2_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "ECL Stage3",
            "displayFolder": "Measures",
            "sourceColumn": "ECL_STAGE3"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "ECL Stage3 QTD",
            "displayFolder": "Measures",
            "sourceColumn": "ECL_STAGE3_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "ECL Stage3 YTD",
            "displayFolder": "Measures",
            "sourceColumn": "ECL_STAGE3_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "EL (P&L)",
            "displayFolder": "Measures",
            "sourceColumn": "EL_PL"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "EL (P&L) QTD",
            "displayFolder": "Measures",
            "sourceColumn": "EL_PL_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "EL (P&L) YTD",
            "displayFolder": "Measures",
            "sourceColumn": "EL_PL_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Funds Charge",
            "displayFolder": "Measures",
            "sourceColumn": "FUNDS_CHRG"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Funds Charge QTD",
            "displayFolder": "Measures",
            "sourceColumn": "FUNDS_CHRG_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Funds Charge YTD",
            "displayFolder": "Measures",
            "sourceColumn": "FUNDS_CHRG_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Funds Credit",
            "displayFolder": "Measures",
            "sourceColumn": "FUNDS_CR"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Funds Credit QTD",
            "displayFolder": "Measures",
            "sourceColumn": "FUNDS_CR_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Funds Credit YTD",
            "displayFolder": "Measures",
            "sourceColumn": "FUNDS_CR_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Gross Interest Income",
            "displayFolder": "Measures",
            "sourceColumn": "GRS_INT_INCM"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Gross Interest Income QTD",
            "displayFolder": "Measures",
            "sourceColumn": "GRS_INT_INCM_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Gross Interest Income YTD",
            "displayFolder": "Measures",
            "sourceColumn": "GRS_INT_INCM_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Gross Interest Expense",
            "displayFolder": "Measures",
            "sourceColumn": "GRS_INT_EXP"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Gross Interest Expense QTD",
            "displayFolder": "Measures",
            "sourceColumn": "GRS_INT_EXP_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Gross Interest Expense YTD",
            "displayFolder": "Measures",
            "sourceColumn": "GRS_INT_EXP_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Gross Loan",
            "displayFolder": "Measures",
            "sourceColumn": "GRS_LN"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Gross Loan QTD",
            "displayFolder": "Measures",
            "sourceColumn": "GRS_LN_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Gross Loan YTD",
            "displayFolder": "Measures",
            "sourceColumn": "GRS_LN_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Income Tax",
            "displayFolder": "Measures",
            "sourceColumn": "INCM_TAX"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Income Tax QTD",
            "displayFolder": "Measures",
            "sourceColumn": "INCM_TAX_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Income Tax YTD",
            "displayFolder": "Measures",
            "sourceColumn": "INCM_TAX_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Profit After Tax",
            "displayFolder": "Measures",
            "sourceColumn": "PRFT_AFTER_TAX"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Profit After Tax YTD",
            "displayFolder": "Measures",
            "sourceColumn": "PRFT_AFTER_TAX_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Profit After Tax QTD",
            "displayFolder": "Measures",
            "sourceColumn": "PRFT_AFTER_TAX_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Bearing Liability",
            "displayFolder": "Measures",
            "sourceColumn": "INT_BEAR_LIAB"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Bearing Liability QTD",
            "displayFolder": "Measures",
            "sourceColumn": "INT_BEAR_LIAB_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Bearing Liability YTD",
            "displayFolder": "Measures",
            "sourceColumn": "INT_BEAR_LIAB_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Bearing Asset",
            "displayFolder": "Measures",
            "sourceColumn": "INT_BEAR_ASSET"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Bearing Asset QTD",
            "displayFolder": "Measures",
            "sourceColumn": "INT_BEAR_ASSET_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Bearing Asset YTD",
            "displayFolder": "Measures",
            "sourceColumn": "INT_BEAR_ASSET_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Income",
            "displayFolder": "Measures",
            "sourceColumn": "INT_INCM"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Income QTD",
            "displayFolder": "Measures",
            "sourceColumn": "INT_INCM_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Income YTD",
            "displayFolder": "Measures",
            "sourceColumn": "INT_INCM_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Net Interest Income",
            "displayFolder": "Measures",
            "sourceColumn": "NET_INT_INCM"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Net Interest Income QTD",
            "displayFolder": "Measures",
            "sourceColumn": "NET_INT_INCM_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Net Interest Income YTD",
            "displayFolder": "Measures",
            "sourceColumn": "NET_INT_INCM_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Non Interest Income",
            "displayFolder": "Measures",
            "sourceColumn": "NON_INT_INCM"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Non Interest Income QTD",
            "displayFolder": "Measures",
            "sourceColumn": "NON_INT_INCM_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Non Interest Income YTD",
            "displayFolder": "Measures",
            "sourceColumn": "NON_INT_INCM_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Income",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_INCM"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Income QTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_INCM_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Income YTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_INCM_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Expense",
            "displayFolder": "Measures",
            "sourceColumn": "INT_EXP"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Expense QTD",
            "displayFolder": "Measures",
            "sourceColumn": "INT_EXP_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Interest Expense YTD",
            "displayFolder": "Measures",
            "sourceColumn": "INT_EXP_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Expense",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_EXP"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Expense QTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_EXP_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Expense YTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_EXP_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Operating Profit",
            "displayFolder": "Measures",
            "sourceColumn": "OPRT_PRFT"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Operating Profit QTD",
            "displayFolder": "Measures",
            "sourceColumn": "OPRT_PRFT_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Operating Profit YTD",
            "displayFolder": "Measures",
            "sourceColumn": "OPRT_PRFT_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Placement and Balance With Bank and Agent",
            "displayFolder": "Measures",
            "sourceColumn": "PLCMT_AND_BAL_WTH_BANK_AND_AGN"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Placement and Balance With Bank and Agent QTD",
            "displayFolder": "Measures",
            "sourceColumn": "PLCMT_AND_BAL_WTH_BANK_AND_AGN_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Placement and Balance With Bank and Agent YTD",
            "displayFolder": "Measures",
            "sourceColumn": "PLCMT_AND_BAL_WTH_BANK_AND_AGN_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Profit Before Tax",
            "displayFolder": "Measures",
            "sourceColumn": "PRFT_BEF_TAX"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Profit Before Tax QTD",
            "displayFolder": "Measures",
            "sourceColumn": "PRFT_BEF_TAX_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Profit Before Tax YTD",
            "displayFolder": "Measures",
            "sourceColumn": "PRFT_BEF_TAX_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Share of Profit of Associate",
            "displayFolder": "Measures",
            "sourceColumn": "SHR_OF_PRFT_OF_ASSC"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Share of Profit of Associate QTD",
            "displayFolder": "Measures",
            "sourceColumn": "SHR_OF_PRFT_OF_ASSC_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Share of Profit of Associate YTD",
            "displayFolder": "Measures",
            "sourceColumn": "SHR_OF_PRFT_OF_ASSC_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Allowance Loan",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_ALLW_LN"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Allowance Loan QTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_ALLW_LN_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Allowance Loan YTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_ALLW_LN_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Asset",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_ASSET"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Asset QTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_ASSET_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Asset YTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_ASSET_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Liability",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_LIAB"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Liability QTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_LIAB_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total Liability YTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_LIAB_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total RWA",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_RWA"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total RWA QTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_RWA_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Total RWA YTD",
            "displayFolder": "Measures",
            "sourceColumn": "TOT_RWA_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Market Risk RWA",
            "displayFolder": "Measures",
            "sourceColumn": "MKT_RISK_RWA"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Market Risk RWA QTD",
            "displayFolder": "Measures",
            "sourceColumn": "MKT_RISK_RWA_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Market Risk RWA YTD",
            "displayFolder": "Measures",
            "sourceColumn": "MKT_RISK_RWA_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Operation Risk RWA",
            "displayFolder": "Measures",
            "sourceColumn": "OPR_RISK_RWA"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Operation Risk RWA QTD",
            "displayFolder": "Measures",
            "sourceColumn": "OPR_RISK_RWA_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Operation Risk RWA YTD",
            "displayFolder": "Measures",
            "sourceColumn": "OPR_RISK_RWA_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Credit Risk RWA",
            "displayFolder": "Measures",
            "sourceColumn": "CR_RISK_RWA"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Credit Risk RWA QTD",
            "displayFolder": "Measures",
            "sourceColumn": "CR_RISK_RWA_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Credit Risk RWA YTD",
            "displayFolder": "Measures",
            "sourceColumn": "CR_RISK_RWA_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "RWA BBIRR",
            "displayFolder": "Measures",
            "sourceColumn": "RWA_BBIRR"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "RWA BBIRR QTD",
            "displayFolder": "Measures",
            "sourceColumn": "RWA_BBIRR_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "RWA BBIRR YTD",
            "displayFolder": "Measures",
            "sourceColumn": "RWA_BBIRR_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Core Capital Deduction RWA",
            "displayFolder": "Measures",
            "sourceColumn": "CORE_CAP_DED_RWA"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Core Capital Deduction RWA QTD",
            "displayFolder": "Measures",
            "sourceColumn": "CORE_CAP_DED_RWA_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Core Capital Deduction RWA YTD",
            "displayFolder": "Measures",
            "sourceColumn": "CORE_CAP_DED_RWA_YTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "CVA RWA",
            "displayFolder": "Measures",
            "sourceColumn": "CVA_RWA"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "CVA RWA QTD",
            "displayFolder": "Measures",
            "sourceColumn": "CVA_RWA_QTD"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "CVA RWA YTD",
            "displayFolder": "Measures",
            "sourceColumn": "CVA_RWA_YTD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Attributes",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Attributes",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "Date",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Attributes",
            "sourceColumn": "START_DATE",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "Date",
            "dataType": "dateTime",
            "name": "End Date",
            "displayFolder": "Attributes",
            "sourceColumn": "END_DATE",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Record Deleted Flag",
            "displayFolder": "Attributes",
            "sourceColumn": "RECORD_DELETED_FLAG",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Control ID",
            "displayFolder": "Attributes",
            "sourceColumn": "CTL_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "PROCESS_NAME",
            "displayFolder": "Attributes",
            "sourceColumn": "PROCESS_NAME",
            "isHidden": true
          },
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "PROCESS_ID",
            "displayFolder": "Attributes",
            "sourceColumn": "PROCESS_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Update Process Name",
            "displayFolder": "Attributes",
            "sourceColumn": "UPDATE_PROCESS_NAME",
            "isHidden": true
          },
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "Update Process ID",
            "displayFolder": "Attributes",
            "sourceColumn": "UPDATE_PROCESS_ID",
            "isHidden": true
          },
          {
            "formatString": "Timestamp",
            "sourceProviderType": "Date",
            "dataType": "dateTime",
            "name": "Start Timestamp",
            "displayFolder": "Attributes",
            "sourceColumn": "START_TS",
            "isHidden": true
          },
          {
            "formatString": "Timestamp",
            "sourceProviderType": "Date",
            "dataType": "dateTime",
            "name": "End Timestamp",
            "displayFolder": "Attributes",
            "sourceColumn": "END_TS",
            "isHidden": true
          },
          {
            "expression": "'F GWB Cross Border'[As of Date] & \"~\" &'F GWB Cross Border'[GRM OFFICER EDW Id]",
            "name": "BUSS_DT_GRM_OFICR_EDW_ID",
            "type": "calculated",
            "displayFolder": "Tech Fields",
            "isHidden": true
          },
          {
            "expression": "'F GWB Cross Border'[As of Date] & \"~\" & 'F GWB Cross Border'[FRM CTO OFFICER EDW ID]",
            "name": "BUSS_DT_FRM_CTO_OFICR_EDW_ID",
            "type": "calculated",
            "displayFolder": "Tech Fields",
            "isHidden": true
          },
          {
            "expression": "'F GWB Cross Border'[As of Date] & \"~\" & 'F GWB Cross Border'[Scenario Cd]",
            "name": "BUSS_DT_SCNRO_CD",
            "type": "calculated",
            "displayFolder": "Tech Fields",
            "isHidden": true
          },
          {
            "expression": "'F GWB Cross Border'[As of Date] & \"~\" & 'F GWB Cross Border'[Product COA ID]",
            "name": "BUSN_DT_PROD_COAID",
            "type": "calculated",
            "displayFolder": "Tech Fields",
            "isHidden": true
          },
          {
            "expression": "'F GWB Cross Border'[As of Date] & \"~\" & 'F GWB Cross Border'[PARTY EDW ID]",
            "name": "BUSS_DT_PRTY_EDW_ID",
            "type": "calculated",
            "displayFolder": "Tech Fields",
            "isHidden": true
          },
          {
            "expression": "'F GWB Cross Border'[As of Date] & \"~\" & 'F GWB Cross Border'[Reporting Branch]",
            "name": "BUSS_DT_RPTG_BR",
            "type": "calculated",
            "displayFolder": "Tech Fields",
            "isHidden": true
          },
          {
            "expression": "'F GWB Cross Border'[Reporting Cost Centre]& \"~\" & 'F GWB Cross Border'[Product COA ID]",
            "name": "RPTG_COST_CTR_PROD_COAID",
            "type": "calculated",
            "displayFolder": "Tech Fields",
            "isHidden": true
          },
          {
            "expression": "'F GWB Cross Border'[Reporting Cost Centre]& \"~\" & 'F GWB Cross Border'[Enterprise Product Leaf Node]",
            "name": "RPTG_COST_CTR_ENTRP_PROD_LEAf_NODE",
            "type": "calculated",
            "displayFolder": "Tech Fields",
            "isHidden": true
          },
          {
            "expression": "'F GWB Cross Border'[As of Date]& \"~\" & 'F GWB Cross Border'[Enterprise Product Leaf Node]",
            "name": "BUSS_DT_ENTRP_PROD_LEAf_NODE",
            "type": "calculated",
            "displayFolder": "Tech Fields",
            "isHidden": true
          },
          {
            "expression": "'F GWB Cross Border'[GRM Country Code]& \"~\" & 'F GWB Cross Border'[Site ID]",
            "name": "GRM_CTRY_CD_SITE_ID",
            "type": "calculated",
            "displayFolder": "Tech Fields",
            "isHidden": true
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\",   'F GWB Cross Border'[Gross Interest Income YTD]  ,  0 )",
            "name": "YTD Gross Interest Income (non- trade)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code])=\"PG_1030012L04\", 'F GWB Cross Border'[Gross Interest Income QTD], 0)",
            "name": "QTD Gross Interest Income (non- trade)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\", 'F GWB Cross Border'[Gross Interest Income], 0)",
            "name": "MTD Gross Interest Income (non- trade)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\", 'F GWB Cross Border'[Funds Charge YTD], 0 )",
            "name": "YTD Funds Charge (non- trade)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\", 'F GWB Cross Border'[Funds Charge QTD], 0)",
            "name": "QTD Funds Charge (non- trade)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code] )=\"PG_1030012L04\", 'F GWB Cross Border'[Funds Charge], 0)",
            "name": "MTD Funds Charge (non- trade)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code] )=\"PG_1030012L04\", 'F GWB Cross Border'[Net Interest Income YTD], 0)",
            "name": "YTD Net Interest Income (non- trade)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code] )=\"PG_1030012L04\", 'F GWB Cross Border'[Net Interest Income QTD], 0)",
            "name": "QTD Net Interest Income (non- trade)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\", 'F GWB Cross Border'[Net Interest Income], 0)",
            "name": "MTD Net Interest Income (non- trade)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Funds Credit YTD], 0)",
            "name": "YTD Funds Credit (CASA)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Funds Credit QTD], 0)",
            "name": "QTD Funds Credit (CASA)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Funds Credit], 0)",
            "name": "MTD Funds Credit (CASA)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Gross Interest Expense YTD], 0)",
            "name": "YTD Gross Interest Expense (CASA)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Gross Interest Expense QTD], 0)",
            "name": "QTD Gross Interest Expense (CASA)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Gross Interest Expense], 0)",
            "name": "MTD Gross Interest Expense (CASA)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Net Interest Income YTD], 0)",
            "name": "YTD Net Interest Income (CASA)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Net Interest Income QTD], 0)",
            "name": "QTD Net Interest Income (CASA)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Net Interest Income], 0)",
            "name": "MTD Net Interest Income (CASA)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\", 'F GWB Cross Border'[Funds Credit YTD], 0)",
            "name": "YTD Funds Credit (FD & others)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\", 'F GWB Cross Border'[Funds Credit QTD], 0)",
            "name": "QTD Funds Credit (FD & others)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\", 'F GWB Cross Border'[Funds Credit], 0)",
            "name": "MTD Funds Credit (FD & others)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\", 'F GWB Cross Border'[Gross Interest Expense YTD], 0)",
            "name": "YTD Gross Interest Expense (FD & others)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\", 'F GWB Cross Border'[Gross Interest Expense QTD], 0)",
            "name": "QTD Gross Interest Expense (FD & others)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\", 'F GWB Cross Border'[Gross Interest Expense], 0)",
            "name": "MTD Gross Interest Expense (FD & others)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\", 'F GWB Cross Border'[Net Interest Income YTD], 0)",
            "name": "YTD Net Interest Income (FD & others)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\", 'F GWB Cross Border'[Net Interest Income QTD], 0)",
            "name": "QTD Net Interest Income (FD & others)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\", 'F GWB Cross Border'[Net Interest Income], 0)",
            "name": "MTD Net Interest Income (FD & others)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\", 'F GWB Cross Border'[Non Interest Income YTD], 0)",
            "name": "YTD Loan Fees",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\", 'F GWB Cross Border'[Non Interest Income QTD], 0)",
            "name": "QTD Loan Fees",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\", 'F GWB Cross Border'[Non Interest Income], 0)",
            "name": "MTD Loan Fees",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 03 Code]  )=\"P_1030007L04\", 'F GWB Cross Border'[Non Interest Income QTD], 0) + IF (RELATED ( 'H Product Org'[Level 03 Code]  )=\"P_1030074L04\", 'F GWB Cross Border'[Non Interest Income QTD], 0)",
            "name": "QTD Trade Fees",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 03 Code]  )=\"P_1020020L05\", 'F GWB Cross Border'[Non Interest Income YTD], 0)",
            "name": "YTD Investment Banking",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 03 Code]  )=\"P_1020020L05\", 'F GWB Cross Border'[Non Interest Income QTD], 0)",
            "name": "QTD Investment Banking",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 03 Code]  )=\"P_1020020L05\", 'F GWB Cross Border'[Non Interest Income], 0)",
            "name": "MTD Investment Banking",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 02 Code]  )=\"P_1020018L05\", 'F GWB Cross Border'[Non Interest Income YTD], 0)",
            "name": "YTD Global Market",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 02 Code]  )=\"P_1020018L05\", 'F GWB Cross Border'[Non Interest Income QTD], 0)",
            "name": "QTD Global Market",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 02 Code]  )=\"P_1020018L05\", 'F GWB Cross Border'[Non Interest Income], 0)",
            "name": "MTD Global Market",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 03 Code]  )=\"P_1030062L04\", 'F GWB Cross Border'[Non Interest Income YTD], 0)",
            "name": "YTD Cash Mgmt",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 03 Code]  )=\"P_1030062L04\", 'F GWB Cross Border'[Non Interest Income QTD], 0)",
            "name": "QTD Cash Mgmt",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 03 Code]  )=\"P_1030062L04\", 'F GWB Cross Border'[Non Interest Income], 0)",
            "name": "MTD Cash Mgmt",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Non Interest Income YTD], 0)",
            "name": "YTD CASA Fees",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Non Interest Income QTD], 0)",
            "name": "QTD CASA Fees",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Non Interest Income], 0)",
            "name": "MTD CASA Fees",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 04 Code]  )=\"P_1040071L03\", 'F GWB Cross Border'[Non Interest Income YTD], 0)",
            "name": "YTD Bancassurance",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 04 Code]  )=\"P_1040071L03\", 'F GWB Cross Border'[Non Interest Income QTD], 0)",
            "name": "QTD Bancassurance",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 04 Code]  )=\"P_1040071L03\", 'F GWB Cross Border'[Non Interest Income], 0)",
            "name": "MTD Bancassurance",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", IF(RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\", 'F GWB Cross Border'[Gross Loan YTD], 0) ,0)+IF( 'F GWB Cross Border'[Balance Type]=\"EOP\", IF(RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent YTD], 0) ,0)",
            "name": "YTD Non Trade (Gross End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", IF(RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\", 'F GWB Cross Border'[Gross Loan QTD], 0) ,0)+IF( 'F GWB Cross Border'[Balance Type]=\"EOP\", IF(RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent QTD], 0) ,0)",
            "name": "QTD Non Trade (Gross End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", IF(RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\", 'F GWB Cross Border'[Gross Loan], 0) ,0)+IF( 'F GWB Cross Border'[Balance Type]=\"EOP\", IF(RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent], 0) ,0)",
            "name": "MTD Non Trade (Gross End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 03 Code])=\"P_1030007L04\" && 'F GWB Cross Border'[Balance Type]=\"EOP\") ,'F GWB Cross Border'[Gross Loan YTD], 0)+IF ((RELATED ('H Product Org'[Level 03 Code])=\"P_1030074L04\" && 'F GWB Cross Border'[Balance Type]=\"EOP\") , 'F GWB Cross Border'[Gross Loan YTD], 0)+IF ((RELATED ( 'H Product Org'[Level 03 Code])=\"P_1030007L04\" && 'F GWB Cross Border'[Balance Type]=\"EOP\") ,'F GWB Cross Border'[Placement and Balance With Bank and Agent YTD], 0)+IF ((RELATED ('H Product Org'[Level 03 Code])=\"P_1030074L04\" && 'F GWB Cross Border'[Balance Type]=\"EOP\") , 'F GWB Cross Border'[Placement and Balance With Bank and Agent YTD], 0)",
            "name": "YTD Trade (Gross End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 03 Code])=\"P_1030007L04\" && 'F GWB Cross Border'[Balance Type]=\"EOP\") ,'F GWB Cross Border'[Gross Loan QTD], 0)+IF ((RELATED ('H Product Org'[Level 03 Code])=\"P_1030074L04\" && 'F GWB Cross Border'[Balance Type]=\"EOP\") , 'F GWB Cross Border'[Gross Loan QTD], 0)+IF ((RELATED ( 'H Product Org'[Level 03 Code])=\"P_1030007L04\" && 'F GWB Cross Border'[Balance Type]=\"EOP\") ,'F GWB Cross Border'[Placement and Balance With Bank and Agent QTD], 0)+IF ((RELATED ('H Product Org'[Level 03 Code])=\"P_1030074L04\" && 'F GWB Cross Border'[Balance Type]=\"EOP\") , 'F GWB Cross Border'[Placement and Balance With Bank and Agent QTD], 0)",
            "name": "QTD Trade (Gross End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 03 Code])=\"P_1030007L04\" && 'F GWB Cross Border'[Balance Type]=\"EOP\") ,'F GWB Cross Border'[Gross Loan], 0)+IF ((RELATED ('H Product Org'[Level 03 Code])=\"P_1030074L04\" && 'F GWB Cross Border'[Balance Type]=\"EOP\") , 'F GWB Cross Border'[Gross Loan], 0)+IF ((RELATED ( 'H Product Org'[Level 03 Code])=\"P_1030007L04\" && 'F GWB Cross Border'[Balance Type]=\"EOP\") ,'F GWB Cross Border'[Placement and Balance With Bank and Agent], 0)+IF ((RELATED ('H Product Org'[Level 03 Code])=\"P_1030074L04\" && 'F GWB Cross Border'[Balance Type]=\"EOP\") , 'F GWB Cross Border'[Placement and Balance With Bank and Agent], 0)",
            "name": "MTD Trade (Gross End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Gross Loan YTD], 0)+IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent YTD], 0)",
            "name": "YTD Total Loan (Gross End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Gross Loan QTD], 0)+IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent QTD], 0)",
            "name": "QTD Total Loan (Gross End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Gross Loan], 0)+IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent], 0)",
            "name": "MTD Total Loan (Gross End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Total Allowance Loan YTD], 0)",
            "name": "YTD Total Allowances (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Total Allowance Loan QTD], 0)",
            "name": "QTD Total Allowances (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Total Allowance Loan], 0)",
            "name": "MTD Total Allowances (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Total Asset YTD], 0)",
            "name": "YTD Total Assets (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Total Asset QTD], 0)",
            "name": "QTD Total Assets (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Total Asset], 0)",
            "name": "MTD Total Assets (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", IF(RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\", 'F GWB Cross Border'[Gross Loan YTD], 0) ,0)+IF( 'F GWB Cross Border'[Balance Type]=\"AVE\", IF(RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent YTD], 0) ,0)",
            "name": "YTD Non Trade (Gross Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", IF(RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\", 'F GWB Cross Border'[Gross Loan QTD], 0) ,0)+IF( 'F GWB Cross Border'[Balance Type]=\"AVE\", IF(RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent QTD], 0) ,0)",
            "name": "QTD Non Trade (Gross Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", IF(RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\", 'F GWB Cross Border'[Gross Loan], 0) ,0)+IF( 'F GWB Cross Border'[Balance Type]=\"AVE\", IF(RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent], 0) ,0)",
            "name": "MTD Non Trade (Gross Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Gross Loan YTD], 0)+IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent YTD], 0)",
            "name": "YTD Total Loan (Gross Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Gross Loan QTD], 0)+IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent QTD], 0)",
            "name": "QTD Total Loan (Gross Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Gross Loan], 0)+IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent], 0)",
            "name": "MTD Total Loan (Gross Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Total Allowance Loan YTD], 0)",
            "name": "YTD Total Allowances (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Total Allowance Loan QTD], 0)",
            "name": "QTD Total Allowances (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Total Allowance Loan], 0)",
            "name": "MTD Total Allowances (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Total Asset YTD], 0)",
            "name": "YTD Total Assets (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Total Asset QTD], 0)",
            "name": "QTD Total Assets (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Total Asset], 0)",
            "name": "MTD Total Assets (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer YTD], 0) , 0 )+IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent YTD], 0) , 0 )",
            "name": "YTD CASA (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer QTD], 0) , 0 )+IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent QTD], 0) , 0 )",
            "name": "QTD CASA (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer], 0) , 0 )+IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent], 0) , 0 )",
            "name": "MTD CASA (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer YTD], 0) , 0 )+IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent YTD], 0) , 0 )",
            "name": "YTD FD & Others (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer QTD], 0) , 0 )+IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent QTD], 0) , 0 )",
            "name": "QTD FD & Others (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer], 0) , 0 )+IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent], 0) , 0 )",
            "name": "MTD FD & Others (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer YTD] , 0)+IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer YTD] , 0)",
            "name": "YTD Total Deposit (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer QTD] , 0)+IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer QTD] , 0)",
            "name": "QTD Total Deposit (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer], 0)+IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer] , 0)",
            "name": "MTD Total Deposit (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Total Liability YTD], 0)",
            "name": "YTD Total Liabilities (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Total Liability QTD], 0)",
            "name": "QTD Total Liabilities (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Total Liability], 0)",
            "name": "MTD Total Liabilities (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer YTD], 0) , 0 )+IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent YTD], 0) , 0 )",
            "name": "YTD CASA (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer QTD], 0) , 0 )+IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent QTD], 0) , 0 )",
            "name": "QTD CASA (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer], 0) , 0 )+IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent], 0) , 0 )",
            "name": "MTD CASA (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer YTD], 0) , 0 )+IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent YTD], 0) , 0 )",
            "name": "YTD FD & Others (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer QTD], 0) , 0 )+IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent QTD], 0) , 0 )",
            "name": "QTD FD & Others (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer], 0) , 0 )+IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent], 0) , 0 )",
            "name": "MTD FD & Others (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer YTD] , 0)+IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer YTD] , 0)",
            "name": "YTD Total Deposit (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer QTD] , 0)+IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer QTD] , 0)",
            "name": "QTD Total Deposit (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer], 0)+IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer] , 0)",
            "name": "MTD Total Deposit (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Total Liability YTD], 0)",
            "name": "YTD Total Liabilities (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Total Liability QTD], 0)",
            "name": "QTD Total Liabilities (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF('F GWB Cross Border'[Balance Type]=\"AVE\",'F GWB Cross Border'[Total Liability], 0)",
            "name": "MTD Total Liabilities (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF( (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\" &&  'F GWB Cross Border'[Balance Type]=\"AVE\"),'F GWB Cross Border'[Interest Bearing Liability YTD], 0)",
            "name": "YTD CASA (Interest Bearing Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\" && 'F GWB Cross Border'[Balance Type]=\"AVE\") , 'F GWB Cross Border'[Interest Bearing Liability QTD], 0)",
            "name": "QTD CASA (Interest Bearing Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030032L04\" && 'F GWB Cross Border'[Balance Type]=\"AVE\"),'F GWB Cross Border'[Interest Bearing Liability], 0)",
            "name": "MTD CASA (Interest Bearing Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\" && 'F GWB Cross Border'[Balance Type]=\"AVE\") ,'F GWB Cross Border'[Interest Bearing Liability YTD], 0)",
            "name": "YTD FD & Others (Interest Bearing Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\" && 'F GWB Cross Border'[Balance Type]=\"AVE\") ,'F GWB Cross Border'[Interest Bearing Liability QTD], 0)",
            "name": "QTD FD & Others (Interest Bearing Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030007L04\" && 'F GWB Cross Border'[Balance Type]=\"AVE\") ,'F GWB Cross Border'[Interest Bearing Liability], 0)",
            "name": "MTD FD & Others (Interest Bearing Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\" , 'F GWB Cross Border'[EAD YTD] , 0)",
            "name": "YTD EAD (End Balance)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\" , 'F GWB Cross Border'[EAD QTD] , 0)",
            "name": "QTD EAD (End Balance)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\" , 'F GWB Cross Border'[EAD] , 0)",
            "name": "MTD EAD (End Balance)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Total RWA YTD], 0)",
            "name": "YTD Total RWA End",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Total RWA QTD], 0)",
            "name": "QTD Total RWA End",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\", 'F GWB Cross Border'[Total RWA], 0)",
            "name": "MTD Total RWA End",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Total RWA YTD], 0)",
            "name": "YTD Total RWA Average",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Total RWA QTD], 0)",
            "name": "QTD Total RWA Average",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", 'F GWB Cross Border'[Total RWA], 0)",
            "name": "MTD Total RWA Average",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Gross Interest Income YTD], 0)",
            "name": "YTD Gross Interest Income (GoldLoans)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Gross Interest Income QTD], 0)",
            "name": "QTD Gross Interest Income (GoldLoans)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Gross Interest Income], 0)",
            "name": "MTD Gross Interest Income (GoldLoans)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Funds Charge YTD], 0)",
            "name": "YTD Funds Charge (GoldLoans)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Funds Charge QTD], 0)",
            "name": "QTD Funds Charge (GoldLoans)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Funds Charge], 0)",
            "name": "MTD Funds Charge (GoldLoans)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Net Interest Income YTD], 0)",
            "name": "YTD Net Interest Income (GoldLoans)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Net Interest Income QTD], 0)",
            "name": "QTD Net Interest Income (GoldLoans)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Net Interest Income], 0)",
            "name": "MTD Net Interest Income (GoldLoans)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Gross Loan YTD], 0) , 0) + IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent YTD], 0) , 0)",
            "name": "YTD GoldLoans (Gross End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Gross Loan QTD], 0) , 0) + IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent QTD], 0) , 0)",
            "name": "QTD GoldLoans (Gross End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Gross Loan], 0) , 0) + IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent], 0) , 0)",
            "name": "MTD GoldLoans (Gross End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Gross Loan YTD], 0) , 0) + IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent YTD], 0) , 0)",
            "name": "YTD GoldLoans (Gross Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Gross Loan QTD], 0) , 0) + IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent QTD], 0) , 0)",
            "name": "QTD GoldLoans (Gross Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Gross Loan], 0) , 0) + IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent], 0) , 0)",
            "name": "MTD GoldLoans (Gross Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Interest Bearing Asset YTD], 0) , 0)",
            "name": "YTD GoldLoans (Interest Earning Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\",'F GWB Cross Border'[Interest Bearing Asset QTD], 0) , 0)",
            "name": "QTD GoldLoans (Interest Earning Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060169L01\", 'F GWB Cross Border'[Interest Bearing Asset], 0) , 0)",
            "name": "MTD GoldLoans (Interest Earning Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Gross Interest Income YTD], 0)",
            "name": "YTD Gross Interest Income (Reverse Repo)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Gross Interest Income QTD], 0)",
            "name": "QTD Gross Interest Income (Reverse Repo)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Gross Interest Income], 0)",
            "name": "MTD Gross Interest Income (Reverse Repo)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Funds Charge YTD], 0)",
            "name": "YTD Funds Charge (Reverse Repo)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Funds Charge QTD], 0)",
            "name": "QTD Funds Charge (Reverse Repo)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Funds Charge], 0)",
            "name": "MTD Funds Charge (Reverse Repo)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Net Interest Income YTD], 0)",
            "name": "YTD Net Interest Income (Reverse Repo)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Net Interest Income QTD], 0)",
            "name": "QTD Net Interest Income (Reverse Repo)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Net Interest Income], 0)",
            "name": "MTD Net Interest Income (Reverse Repo)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Gross Loan YTD], 0) , 0) + IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent YTD], 0) , 0)",
            "name": "YTD Reverse Repo (Gross End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Gross Loan QTD], 0) , 0) + IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent QTD], 0) , 0)",
            "name": "QTD Reverse Repo (Gross End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Gross Loan], 0) , 0) + IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent], 0) , 0)",
            "name": "MTD Reverse Repo (Gross End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Gross Loan YTD], 0) , 0) + IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent YTD], 0) , 0)",
            "name": "YTD Reverse Repo (Gross Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Gross Loan QTD], 0) , 0) + IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent QTD], 0) , 0)",
            "name": "QTD Reverse Repo (Gross Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Gross Loan], 0) , 0) + IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Placement and Balance With Bank and Agent], 0) , 0)",
            "name": "MTD Reverse Repo (Gross Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\", IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Interest Bearing Asset YTD], 0) , 0)",
            "name": "YTD Reverse Repo (Interest Earning Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\",'F GWB Cross Border'[Interest Bearing Asset QTD], 0) , 0)",
            "name": "QTD Reverse Repo (Interest Earning Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 06 Code]  )=\"PG_1060509L01\", 'F GWB Cross Border'[Interest Bearing Asset], 0) , 0)",
            "name": "MTD Reverse Repo (Interest Earning Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Funds Credit YTD], 0)",
            "name": "YTD Funds Credit (MMD)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Funds Credit QTD], 0)",
            "name": "QTD Funds Credit (MMD)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Funds Credit], 0)",
            "name": "MTD Funds Credit (MMD)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Gross Interest Expense YTD], 0)",
            "name": "YTD Gross Interest Expense (MMD)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Gross Interest Expense QTD], 0)",
            "name": "QTD Gross Interest Expense (MMD)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Gross Interest Expense], 0)",
            "name": "MTD Gross Interest Expense (MMD)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Net Interest Income YTD], 0)",
            "name": "YTD Net Interest Income (MMD)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Net Interest Income QTD], 0)",
            "name": "QTD Net Interest Income (MMD)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Net Interest Income], 0)",
            "name": "MTD Net Interest Income (MMD)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer YTD], 0) , 0)  +  IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent YTD], 0) , 0)",
            "name": "YTD MMD (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer QTD], 0) , 0)  +  IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent QTD], 0) , 0)",
            "name": "QTD MMD (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer], 0) , 0)  +  IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent], 0) , 0)",
            "name": "MTD MMD (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer YTD], 0) , 0)  +  IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent YTD], 0) , 0)",
            "name": "YTD MMD (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer QTD], 0) , 0)  +  IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent QTD], 0) , 0)",
            "name": "QTD MMD (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer], 0) , 0)  +  IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent], 0) , 0)",
            "name": "MTD MMD (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Interest Bearing Liability], 0) , 0)",
            "name": "YTD MMD (Interest Bearing Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Interest Bearing Liability], 0) , 0)",
            "name": "QTD MMD (Interest Bearing Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040168L03\", 'F GWB Cross Border'[Interest Bearing Liability], 0) , 0)",
            "name": "MTD MMD (Interest Bearing Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L03\", 'F GWB Cross Border'[Funds Credit YTD], 0)",
            "name": "YTD Funds Credit (NCD)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L03\", 'F GWB Cross Border'[Funds Credit QTD], 0)",
            "name": "QTD Funds Credit (NCD)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L03\", 'F GWB Cross Border'[Funds Credit], 0)",
            "name": "MTD Funds Credit (NCD)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L04\", 'F GWB Cross Border'[Gross Interest Expense YTD], 0)",
            "name": "YTD Gross Interest Expense (NCD)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L04\", 'F GWB Cross Border'[Gross Interest Expense QTD], 0)",
            "name": "QTD Gross Interest Expense (NCD)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L04\", 'F GWB Cross Border'[Gross Interest Expense], 0)",
            "name": "MTD Gross Interest Expense (NCD)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L03\", 'F GWB Cross Border'[Net Interest Income YTD], 0)",
            "name": "YTD Net Interest Income (NCD)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L03\", 'F GWB Cross Border'[Net Interest Income QTD], 0)",
            "name": "QTD Net Interest Income (NCD)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L03\", 'F GWB Cross Border'[Net Interest Income], 0)",
            "name": "MTD Net Interest Income (NCD)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L03\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer YTD], 0) , 0)  +  IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L03\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent YTD], 0) , 0)",
            "name": "YTD NCD (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L03\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer QTD], 0) , 0)  +  IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L03\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent QTD], 0) , 0)",
            "name": "QTD NCD (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L03\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer], 0) , 0)  +  IF ( 'F GWB Cross Border'[Balance Type]=\"EOP\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L03\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent], 0) , 0)",
            "name": "MTD NCD (End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L03\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer YTD], 0) , 0)  +  IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L03\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent YTD], 0) , 0)",
            "name": "YTD NCD (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L03\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer QTD], 0) , 0)  +  IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L03\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent QTD], 0) , 0)",
            "name": "QTD NCD (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L03\", 'F GWB Cross Border'[Deposit and Balances of Non Bank Customer], 0) , 0)  +  IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L03\", 'F GWB Cross Border'[Deposit and Balances of Bank and Agent], 0) , 0)",
            "name": "MTD NCD (Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L03\", 'F GWB Cross Border'[Interest Bearing Liability], 0) , 0)",
            "name": "YTD NCD (Interest Bearing Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L03\", 'F GWB Cross Border'[Interest Bearing Liability], 0) , 0)",
            "name": "QTD NCD (Interest Bearing Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 04 Code]  )=\"PG_1040173L03\", 'F GWB Cross Border'[Interest Bearing Liability], 0) , 0)",
            "name": "MTD NCD (Interest Bearing Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\"  , 'F GWB Cross Border'[Net Interest Income YTD], 0) +  IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030074L04\" , 'F GWB Cross Border'[Net Interest Income YTD], 0)",
            "name": "YTD Net Interest Income (Export)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\"  , 'F GWB Cross Border'[Net Interest Income QTD], 0) +  IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030074L04\" , 'F GWB Cross Border'[Net Interest Income QTD], 0)",
            "name": "QTD Net Interest Income (Export)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\"  , 'F GWB Cross Border'[Net Interest Income], 0) + IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030074L04\"  , 'F GWB Cross Border'[Net Interest Income], 0)",
            "name": "MTD Net Interest Income (Export)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\" , 'F GWB Cross Border'[Non Interest Income YTD], 0) + IF(   RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030074L04\" , 'F GWB Cross Border'[Non Interest Income YTD], 0)",
            "name": "YTD Non Interest Income (Export)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\" , 'F GWB Cross Border'[Non Interest Income QTD], 0) + IF( RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030074L04\" , 'F GWB Cross Border'[Non Interest Income QTD], 0)",
            "name": "QTD Non Interest Income (Export)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\" , 'F GWB Cross Border'[Non Interest Income], 0) + IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030074L04\" , 'F GWB Cross Border'[Non Interest Income], 0)",
            "name": "MTD Non Interest Income (Export)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\",'F GWB Cross Border'[Net Interest Income YTD], 0) + IF( RELATED( 'H Product Org'[Level 03 Code]  )= \"P_1030074L04\" , 'F GWB Cross Border'[Net Interest Income YTD], 0)",
            "name": "YTD Net Interest Income (Import)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\" ,'F GWB Cross Border'[Net Interest Income QTD], 0) + IF(  RELATED( 'H Product Org'[Level 03 Code]  )= \"P_1030074L04\" , 'F GWB Cross Border'[Net Interest Income QTD], 0)",
            "name": "QTD Net Interest Income (Import)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF( RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\" ,'F GWB Cross Border'[Net Interest Income], 0) + IF(   RELATED( 'H Product Org'[Level 03 Code]  )= \"P_1030074L04\" , 'F GWB Cross Border'[Net Interest Income], 0)",
            "name": "MTD Net Interest Income (Import)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\" , 'F GWB Cross Border'[Non Interest Income YTD], 0) + IF(  RELATED( 'H Product Org'[Level 03 Code]  )= \"P_1030074L04\" , 'F GWB Cross Border'[Non Interest Income YTD], 0)",
            "name": "YTD Non Interest Income (Import)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF( RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\" , 'F GWB Cross Border'[Non Interest Income QTD], 0) + IF(   RELATED( 'H Product Org'[Level 03 Code]  )= \"P_1030074L04\" , 'F GWB Cross Border'[Non Interest Income QTD], 0)",
            "name": "QTD Non Interest Income (Import)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF( RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\" , 'F GWB Cross Border'[Non Interest Income], 0) + IF(   RELATED( 'H Product Org'[Level 03 Code]  )= \"P_1030074L04\" , 'F GWB Cross Border'[Non Interest Income], 0)",
            "name": "MTD Non Interest Income (Import)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\",'F GWB Cross Border'[Gross Interest Income YTD], 0) + IF( RELATED( 'H Product Org'[Level 03 Code]  )= \"P_1030074L04\" , 'F GWB Cross Border'[Gross Interest Income YTD], 0)",
            "name": "YTD Gross Interest Income (trade)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\",'F GWB Cross Border'[Gross Interest Income QTD], 0) + IF( RELATED( 'H Product Org'[Level 03 Code]  )= \"P_1030074L04\" , 'F GWB Cross Border'[Gross Interest Income QTD], 0)",
            "name": "QTD Gross Interest Income (trade)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\",'F GWB Cross Border'[Gross Interest Income], 0) + IF( RELATED( 'H Product Org'[Level 03 Code]  )= \"P_1030074L04\" , 'F GWB Cross Border'[Gross Interest Income], 0)",
            "name": "MTD Gross Interest Income (trade)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\",'F GWB Cross Border'[Funds Charge YTD], 0) + IF( RELATED( 'H Product Org'[Level 03 Code]  )= \"P_1030074L04\" , 'F GWB Cross Border'[Funds Charge YTD], 0)",
            "name": "YTD Funds Charge (trade)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\",'F GWB Cross Border'[Funds Charge QTD], 0) + IF( RELATED( 'H Product Org'[Level 03 Code]  )= \"P_1030074L04\" , 'F GWB Cross Border'[Funds Charge QTD], 0)",
            "name": "QTD Funds Charge (trade)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\",'F GWB Cross Border'[Funds Charge], 0) + IF( RELATED( 'H Product Org'[Level 03 Code]  )= \"P_1030074L04\" , 'F GWB Cross Border'[Funds Charge], 0)",
            "name": "MTD Funds Charge (trade)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\",'F GWB Cross Border'[Net Interest Income YTD], 0) + IF( RELATED( 'H Product Group'[Level 03 Code]  )= \"P_1030074L04\" , 'F GWB Cross Border'[Net Interest Income YTD], 0)",
            "name": "YTD Net Interest Income (trade)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\",'F GWB Cross Border'[Net Interest Income QTD], 0) + IF( RELATED( 'H Product Org'[Level 03 Code]  )= \"P_1030074L04\" , 'F GWB Cross Border'[Net Interest Income QTD], 0)",
            "name": "QTD Net Interest Income (trade)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\",'F GWB Cross Border'[Net Interest Income], 0) + IF( RELATED( 'H Product Org'[Level 03 Code]  )= \"P_1030074L04\" , 'F GWB Cross Border'[Net Interest Income], 0)",
            "name": "MTD Net Interest Income (trade)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 03 Code])=\"P_1020018L05\", 'F GWB Cross Border'[Net Interest Income YTD], 0)-IF (RELATED ( 'H Product Group'[Level 04 Code])=\"PG_1040173L03\", 'F GWB Cross Border'[Net Interest Income YTD], 0)",
            "name": "YTD Net Interest Income (GM)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 03 Code])=\"P_1020018L05\", 'F GWB Cross Border'[Net Interest Income QTD], 0)- IF(RELATED ( 'H Product Group'[Level 04 Code])=\"PG_1040173L03\", 'F GWB Cross Border'[Net Interest Income QTD], 0)",
            "name": "QTD Net Interest Income (GM)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 03 Code])=\"P_1020018L05\", 'F GWB Cross Border'[Net Interest Income], 0)-IF (RELATED ( 'H Product Group'[Level 04 Code])=\"PG_1040173L03\", 'F GWB Cross Border'[Net Interest Income], 0)",
            "name": "MTD Net Interest Income (GM)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\",'F GWB Cross Border'[Non Interest Income YTD], 0) + IF( RELATED( 'H Product Org'[Level 03 Code]  )= \"P_1030074L04\" , 'F GWB Cross Border'[Non Interest Income YTD], 0)",
            "name": "YTD Trade Fees",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF(  RELATED( 'H Product Org'[Level 03 Code]  ) = \"P_1030007L04\",'F GWB Cross Border'[Non Interest Income], 0) + IF( RELATED( 'H Product Org'[Level 03 Code]  )= \"P_1030074L04\" , 'F GWB Cross Border'[Non Interest Income], 0)",
            "name": "MTD Trade Fees",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020018L05\"  && 'F GWB Cross Border'[Balance Type]=\"EOP\"), 'F GWB Cross Border'[Gross Loan YTD], 0)+IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020018L05\"  && 'F GWB Cross Border'[Balance Type]=\"EOP\"), 'F GWB Cross Border'[Placement and Balance With Bank and Agent YTD], 0)",
            "name": "YTD Global Market (Gross End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020018L05\"  && 'F GWB Cross Border'[Balance Type]=\"EOP\"), 'F GWB Cross Border'[Gross Loan YTD], 0)+IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020018L05\"  && 'F GWB Cross Border'[Balance Type]=\"EOP\"), 'F GWB Cross Border'[Placement and Balance With Bank and Agent QTD], 0)",
            "name": "QTD Global Market (Gross End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020018L05\"  && 'F GWB Cross Border'[Balance Type]=\"EOP\"), 'F GWB Cross Border'[Gross Loan], 0)+IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020018L05\"  && 'F GWB Cross Border'[Balance Type]=\"EOP\"), 'F GWB Cross Border'[Placement and Balance With Bank and Agent], 0)",
            "name": "MTD Global Market (Gross End)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 03 Code])=\"P_1030007L04\" && 'F GWB Cross Border'[Balance Type]=\"AVE\") ,'F GWB Cross Border'[Gross Loan YTD], 0)+IF ((RELATED ('H Product Org'[Level 03 Code])=\"P_1030074L04\" && 'F GWB Cross Border'[Balance Type]=\"AVE\") , 'F GWB Cross Border'[Gross Loan YTD], 0)+IF ((RELATED ( 'H Product Org'[Level 03 Code])=\"P_1030007L04\" && 'F GWB Cross Border'[Balance Type]=\"AVE\") ,'F GWB Cross Border'[Placement and Balance With Bank and Agent YTD], 0)+IF ((RELATED ('H Product Org'[Level 03 Code])=\"P_1030074L04\" && 'F GWB Cross Border'[Balance Type]=\"AVE\") , 'F GWB Cross Border'[Placement and Balance With Bank and Agent YTD], 0)",
            "name": "YTD Trade (Gross Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 03 Code])=\"P_1030007L04\" && 'F GWB Cross Border'[Balance Type]=\"AVE\") ,'F GWB Cross Border'[Gross Loan QTD], 0)+IF ((RELATED ('H Product Org'[Level 03 Code])=\"P_1030074L04\" && 'F GWB Cross Border'[Balance Type]=\"AVE\") , 'F GWB Cross Border'[Gross Loan QTD], 0)+IF ((RELATED ( 'H Product Org'[Level 03 Code])=\"P_1030007L04\" && 'F GWB Cross Border'[Balance Type]=\"AVE\") ,'F GWB Cross Border'[Placement and Balance With Bank and Agent QTD], 0)+IF ((RELATED ('H Product Org'[Level 03 Code])=\"P_1030074L04\" && 'F GWB Cross Border'[Balance Type]=\"AVE\") , 'F GWB Cross Border'[Placement and Balance With Bank and Agent QTD], 0)",
            "name": "QTD Trade (Gross Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 03 Code])=\"P_1030007L04\" && 'F GWB Cross Border'[Balance Type]=\"AVE\") ,'F GWB Cross Border'[Gross Loan], 0)+IF ((RELATED ('H Product Org'[Level 03 Code])=\"P_1030074L04\" && 'F GWB Cross Border'[Balance Type]=\"AVE\") , 'F GWB Cross Border'[Gross Loan], 0)+IF ((RELATED ( 'H Product Org'[Level 03 Code])=\"P_1030007L04\" && 'F GWB Cross Border'[Balance Type]=\"AVE\") ,'F GWB Cross Border'[Placement and Balance With Bank and Agent], 0)+IF ((RELATED ('H Product Org'[Level 03 Code])=\"P_1030074L04\" && 'F GWB Cross Border'[Balance Type]=\"AVE\") , 'F GWB Cross Border'[Placement and Balance With Bank and Agent], 0)",
            "name": "MTD Trade (Gross Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020018L05\"  && 'F GWB Cross Border'[Balance Type]=\"AVE\"), 'F GWB Cross Border'[Gross Loan YTD], 0)+IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020018L05\"  && 'F GWB Cross Border'[Balance Type]=\"AVE\"), 'F GWB Cross Border'[Placement and Balance With Bank and Agent YTD], 0)",
            "name": "YTD Global Market (Gross Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020018L05\"  && 'F GWB Cross Border'[Balance Type]=\"AVE\"), 'F GWB Cross Border'[Gross Loan YTD], 0)+IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020018L05\"  && 'F GWB Cross Border'[Balance Type]=\"AVE\"), 'F GWB Cross Border'[Placement and Balance With Bank and Agent QTD], 0)",
            "name": "QTD Global Market (Gross Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020018L05\"  && 'F GWB Cross Border'[Balance Type]=\"AVE\"), 'F GWB Cross Border'[Gross Loan], 0)+IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020018L05\"  && 'F GWB Cross Border'[Balance Type]=\"AVE\"), 'F GWB Cross Border'[Placement and Balance With Bank and Agent], 0)",
            "name": "MTD Global Market (Gross Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 03 Code])=\"P_1030007L04\"  && 'F GWB Cross Border'[Balance Type]=\"AVE\" ), 'F GWB Cross Border'[Interest Bearing Asset YTD], 0) + IF ((RELATED ( 'H Product Org'[Level 03 Code])=\"P_1030074L04\"  && 'F GWB Cross Border'[Balance Type]=\"AVE\" ), 'F GWB Cross Border'[Interest Bearing Asset YTD], 0)",
            "name": "YTD Trade (Interest Earning Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 03 Code])=\"P_1030007L04\"  && 'F GWB Cross Border'[Balance Type]=\"AVE\" ), 'F GWB Cross Border'[Interest Bearing Asset QTD], 0) + IF ((RELATED ( 'H Product Org'[Level 03 Code])=\"P_1030074L04\"  && 'F GWB Cross Border'[Balance Type]=\"AVE\" ), 'F GWB Cross Border'[Interest Bearing Asset QTD], 0)",
            "name": "QTD Trade (Interest Earning Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 03 Code])=\"P_1030007L04\"  && 'F GWB Cross Border'[Balance Type]=\"AVE\" ), 'F GWB Cross Border'[Interest Bearing Asset], 0) +  IF ((RELATED ( 'H Product Org'[Level 03 Code])=\"P_1030074L04\"  && 'F GWB Cross Border'[Balance Type]=\"AVE\" ), 'F GWB Cross Border'[Interest Bearing Asset], 0)",
            "name": "MTD Trade (Interest Earning Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020018L05\"  && 'F GWB Cross Border'[Balance Type]=\"AVE\" ), 'F GWB Cross Border'[Interest Bearing Asset YTD], 0)",
            "name": "YTD Global Market (Interest Earning Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020018L05\"  && 'F GWB Cross Border'[Balance Type]=\"AVE\" ), 'F GWB Cross Border'[Interest Bearing Asset QTD], 0)",
            "name": "QTD Global Market (Interest Earning Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020018L05\"  && 'F GWB Cross Border'[Balance Type]=\"AVE\" ), 'F GWB Cross Border'[Interest Bearing Asset], 0)",
            "name": "MTD Global Market (Interest Earning Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020022L05\", 'F GWB Cross Border'[Total Income YTD], 0)",
            "name": "YTD Total Income (Transaction Banking)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020022L05\", 'F GWB Cross Border'[Total Income QTD], 0)",
            "name": "QTD Total Income (Transaction Banking)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020022L05\", 'F GWB Cross Border'[Total Income], 0)",
            "name": "MTD Total Income (Transaction Banking)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020022L05\"  && 'F GWB Cross Border'[Balance Type]=\"EOP\" ), 'F GWB Cross Border'[Total RWA YTD], 0)",
            "name": "YTD TB RWA End",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020022L05\"  && 'F GWB Cross Border'[Balance Type]=\"EOP\"), 'F GWB Cross Border'[Total RWA QTD], 0)",
            "name": "QTD TB RWA End",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020022L05\"  && 'F GWB Cross Border'[Balance Type]=\"EOP\" ), 'F GWB Cross Border'[Total RWA], 0)",
            "name": "MTD TB RWA End",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020022L05\"  && 'F GWB Cross Border'[Balance Type]=\"AVE\" ), 'F GWB Cross Border'[Total RWA YTD], 0)",
            "name": "YTD TB RWA Average",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020022L05\"  && 'F GWB Cross Border'[Balance Type]=\"AVE\" ), 'F GWB Cross Border'[Total RWA QTD], 0)",
            "name": "QTD TB RWA Average",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020022L05\"  && 'F GWB Cross Border'[Balance Type]=\"AVE\" ), 'F GWB Cross Border'[Total RWA], 0)",
            "name": "MTD TB RWA Average",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020018L05\"  && 'F GWB Cross Border'[Balance Type]=\"EOP\" ), 'F GWB Cross Border'[Total RWA YTD], 0)",
            "name": "YTD GM RWA End",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020018L05\"  && 'F GWB Cross Border'[Balance Type]=\"EOP\" ), 'F GWB Cross Border'[Total RWA QTD], 0)",
            "name": "QTD GM RWA End",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020018L05\"  && 'F GWB Cross Border'[Balance Type]=\"EOP\" ), 'F GWB Cross Border'[Total RWA], 0)",
            "name": "MTD GM RWA End",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020018L05\"  && 'F GWB Cross Border'[Balance Type]=\"AVE\" ), 'F GWB Cross Border'[Total RWA YTD], 0)",
            "name": "YTD GM RWA Average",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020018L05\"  && 'F GWB Cross Border'[Balance Type]=\"AVE\" ), 'F GWB Cross Border'[Total RWA QTD], 0)",
            "name": "QTD GM RWA Average",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ((RELATED ( 'H Product Org'[Level 02 Code])=\"P_1020018L05\"  && 'F GWB Cross Border'[Balance Type]=\"AVE\" ), 'F GWB Cross Border'[Total RWA], 0)",
            "name": "MTD GM RWA Average",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 03 Code])=\"P_1030065L04\",'F GWB Cross Border'[Non Interest Income YTD], 0)",
            "name": "YTD Custody",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 03 Code])=\"P_1030065L04\",'F GWB Cross Border'[Non Interest Income QTD], 0)",
            "name": "QTD Custody",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF (RELATED ( 'H Product Org'[Level 03 Code])=\"P_1030065L04\",'F GWB Cross Border'[Non Interest Income], 0)",
            "name": "MTD Custody",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\" , 'F GWB Cross Border'[Interest Bearing Liability YTD] , 0)",
            "name": "YTD Total Deposit (Interest Bearing Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\" , 'F GWB Cross Border'[Interest Bearing Liability QTD] , 0)",
            "name": "QTD Total Deposit (Interest Bearing Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\" , 'F GWB Cross Border'[Interest Bearing Liability] , 0)",
            "name": "MTD Total Deposit (Interest Bearing Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\" , 'F GWB Cross Border'[Interest Bearing Asset YTD] , 0)",
            "name": "YTD Total Loan (Interest Earning Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\" , 'F GWB Cross Border'[Interest Bearing Asset QTD] , 0)",
            "name": "QTD Total Loan (Interest Earning Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\" , 'F GWB Cross Border'[Interest Bearing Asset] , 0)",
            "name": "MTD Total Loan (Interest Earning Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\", 'F GWB Cross Border'[Interest Bearing Asset YTD], 0) , 0)",
            "name": "YTD Non Trade (Interest Earning Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\3. Yearly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\",'F GWB Cross Border'[Interest Bearing Asset QTD], 0) , 0)",
            "name": "QTD Non Trade (Interest Earning Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\2. Quarterly"
          },
          {
            "formatString": "#,0.000000;(#,0.000000);#,0.000000",
            "expression": "IF ( 'F GWB Cross Border'[Balance Type]=\"AVE\",IF (RELATED ( 'H Product Group'[Level 03 Code]  )=\"PG_1030012L04\", 'F GWB Cross Border'[Interest Bearing Asset], 0) , 0)",
            "name": "MTD Non Trade (Interest Earning Avg)",
            "type": "calculated",
            "displayFolder": "Derived Measures\\1. Monthly"
          }
        ],
        "dataCategory": "",
        "name": "F GWB Cross Border",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_GWB_V\".\"F_GWB_CROSS_BORDR_RPTG\".* FROM \"U01_EDW_SEM_GWB_V\".\"F_GWB_CROSS_BORDR_RPTG\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "F_GWB_CROSS_BORDR_RPTG"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "D_CCY",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_OTH_V\".\"D_CCY\".* FROM \"U01_EDW_SEM_OTH_V\".\"D_CCY\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Currency Code",
            "displayFolder": "Attributes",
            "sourceColumn": "CCY_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Currency Name",
            "displayFolder": "Attributes",
            "sourceColumn": "CCY_NM"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "ISO Currency Code",
            "displayFolder": "Attributes",
            "sourceColumn": "ISO_CCY_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "ISO Currency Name",
            "displayFolder": "Attributes",
            "sourceColumn": "ISO_CCY_NM"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Record Deleted Flag",
            "summarizeBy": "none",
            "displayFolder": "Tech Fields",
            "sourceColumn": "RECORD_DELETED_FLAG",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Control ID",
            "summarizeBy": "none",
            "displayFolder": "Tech Fields",
            "sourceColumn": "CTL_ID",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "D Currency",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_OTH_V\".\"D_CCY\".* FROM \"U01_EDW_SEM_OTH_V\".\"D_CCY\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "D_CCY"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "D_CURY_TYPE",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_OTH_V\".\"D_CURY_TYPE\".* FROM \"U01_EDW_SEM_OTH_V\".\"D_CURY_TYPE\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Currency Type Code",
            "displayFolder": "Attributes",
            "sourceColumn": "CCY_TYPE_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Currency Type Description",
            "displayFolder": "Attributes",
            "sourceColumn": "CCY_TYPE_DESC"
          }
        ],
        "dataCategory": "",
        "name": "D Currency Filter",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_OTH_V\".\"D_CURY_TYPE\".* FROM \"U01_EDW_SEM_OTH_V\".\"D_CURY_TYPE\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "D_CURY_TYPE"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "D_TIME",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_OTH_V\".\"D_TIME\".* FROM \"U01_EDW_SEM_OTH_V\".\"D_TIME\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [
          {
            "formatString": "#,0.00;(#,0.00);#,0.00",
            "expression": "MAX('D Time'[Annualizing Factor MTH])",
            "name": "MTD Annualizing Factor",
            "displayFolder": "Derived Measures"
          },
          {
            "formatString": "#,0.00;(#,0.00);#,0.00",
            "expression": "MAX('D Time'[Annualizing Factor YTD])",
            "name": "YTD Annualizing Factor",
            "displayFolder": "Derived Measures"
          },
          {
            "formatString": "#,0.00;(#,0.00);#,0.00",
            "expression": "MAX('D Time'[Annualizing Factor QTD])",
            "name": "QTD Annualizing Factor",
            "displayFolder": "Derived Measures"
          }
        ],
        "hierarchies": [],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Reporting Month End Indicator",
            "displayFolder": "Attributes",
            "sourceColumn": "REP_MTH_END_IND"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Month-Year",
            "displayFolder": "Attributes",
            "sourceColumn": "MTH_YR"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Month End Indicator",
            "displayFolder": "Attributes",
            "sourceColumn": "MTH_END_IND"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Quarter",
            "displayFolder": "Attributes",
            "sourceColumn": "QTR"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Quarter-Year",
            "displayFolder": "Attributes",
            "sourceColumn": "QTR_YR"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "FY Start Date Month",
            "displayFolder": "Attributes",
            "sourceColumn": "FY_STRT_MTH"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "FY End Date Month",
            "displayFolder": "Attributes",
            "sourceColumn": "FY_END_MTH"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Year-Period",
            "displayFolder": "Attributes",
            "sourceColumn": "YR_PER"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Quarter End Indicator",
            "displayFolder": "Attributes",
            "sourceColumn": "QTR_END_IND"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Year End Indicator",
            "displayFolder": "Attributes",
            "sourceColumn": "YR_END_IND"
          },
          {
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Previous Year Quarter End Date",
            "displayFolder": "Attributes",
            "sourceColumn": "PREV_YR_QTR_END_DT"
          },
          {
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Previous Year-Year End Date",
            "displayFolder": "Attributes",
            "sourceColumn": "PREV_YR_YE_DT"
          },
          {
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Previous Month End Date",
            "displayFolder": "Attributes",
            "sourceColumn": "PREV_ME_DT"
          },
          {
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Previous Quarter End Date",
            "displayFolder": "Attributes",
            "sourceColumn": "PREV_QTR_END_DT"
          },
          {
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Previous Year Month End Date",
            "displayFolder": "Attributes",
            "sourceColumn": "PREV_YR_ME_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source ID",
            "displayFolder": "Attributes",
            "sourceColumn": "SRC_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Fiscal Calendar ID",
            "displayFolder": "Attributes",
            "sourceColumn": "FISC_CAL_ID"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Calendar Date",
            "isKey": true,
            "displayFolder": "Attributes",
            "sourceColumn": "CAL_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Fiscal Calendar Name",
            "displayFolder": "Attributes",
            "sourceColumn": "FISC_CAL_NM"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Day of Calendar Year",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "DAY_OF_CAL_YR"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Day of Calendar Quarter",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "DAY_OF_CAL_QTR"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Day of Calendar Month",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "DAY_OF_CAL_MTH"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Day of Calendar Week",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "DAY_OF_CAL_WK"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Year Number",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "YR_NUM"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Year Start Date",
            "displayFolder": "Attributes",
            "sourceColumn": "YR_STRT_DT"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Year End Date",
            "displayFolder": "Attributes",
            "sourceColumn": "YE_DT"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Quarter Number",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "QTR_NUM"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Quarter Start Date",
            "displayFolder": "Attributes",
            "sourceColumn": "QTR_STRT_DT"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Quarter End Date",
            "displayFolder": "Attributes",
            "sourceColumn": "QTR_END_DT"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Quarters in Year",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "QTR_IN_YR"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Month Number",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "MTH_NUM"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Short Name of Month",
            "sortByColumn": "Month Number",
            "displayFolder": "Attributes",
            "sourceColumn": "SHRT_NM_OF_MTH"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Month Start Date",
            "displayFolder": "Attributes",
            "sourceColumn": "MTH_STRT_DT"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Month End Date",
            "displayFolder": "Attributes",
            "sourceColumn": "ME_DT"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Months in Quarter",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "MTH_IN_QTR"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Months in Year",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "MTH_IN_YR"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "ISO Week Number",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "ISO_WK_NUM"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "ISO Week Year Number",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "ISO_WK_YR_NUM"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Week Start Date",
            "displayFolder": "Attributes",
            "sourceColumn": "WK_STRT_DT"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Week End Date",
            "displayFolder": "Attributes",
            "sourceColumn": "WK_END_DT"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Weeks in Year",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "WK_IN_YR"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Day Number",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "DAY_NUM"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Name of Day",
            "displayFolder": "Attributes",
            "sourceColumn": "NM_OF_DAY"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Short Name of Day",
            "sortByColumn": "Day of Calendar Week",
            "displayFolder": "Attributes",
            "sourceColumn": "SHRT_NM_OF_DAY"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Days in Year",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "DAYS_IN_YR"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Days in Quarter",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "DAYS_IN_QTR"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Days in Month",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "DAYS_IN_MTH"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Days in Week Year",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "DAYS_IN_WK_YR"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Working Day Flag",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "WRK_DAY_FL"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Fiscal Year",
            "displayFolder": "Attributes",
            "sourceColumn": "FISC_YR"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Fiscal Year Start Date",
            "displayFolder": "Attributes",
            "sourceColumn": "FISC_YR_STRT_DT"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Fiscal Year End Date",
            "displayFolder": "Attributes",
            "sourceColumn": "FISC_YE_DT"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Days in Fiscal Year",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "DAYS_IN_FISC_YR"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Fiscal Period Code",
            "displayFolder": "Attributes",
            "sourceColumn": "FISC_PER_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Fiscal Period",
            "displayFolder": "Attributes",
            "sourceColumn": "FISC_PER"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Period Start Date",
            "displayFolder": "Attributes",
            "sourceColumn": "PER_STRT_DT"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Period End Date",
            "displayFolder": "Attributes",
            "sourceColumn": "PER_END_DT"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Days in Period",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "DAYS_IN_PER"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Periods in Fiscal Year",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "PERS_IN_FISC_YR"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Special Periods in Financial Year",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "SPL_PERS_IN_FYR"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Annualizing Factor",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "ANL_FACT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Record Deleted Flag",
            "summarizeBy": "none",
            "displayFolder": "Tech Fields",
            "sourceColumn": "RECORD_DELETED_FLAG",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Control ID",
            "summarizeBy": "none",
            "displayFolder": "Tech Fields",
            "sourceColumn": "CTL_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Annualizing Factor YTD",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "ANL_FACT_YTD"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Annualizing Factor QTD",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "ANL_FACT_QTD"
          },
          {
            "formatString": "0",
            "sourceProviderType": "Decimal",
            "dataType": "double",
            "name": "Annualizing Factor MTH",
            "summarizeBy": "none",
            "displayFolder": "Attributes",
            "sourceColumn": "ANL_FACT_MTH"
          }
        ],
        "dataCategory": "",
        "name": "D Time",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_OTH_V\".\"D_TIME\".* FROM \"U01_EDW_SEM_OTH_V\".\"D_TIME\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "D_TIME"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "H_PROD_GRP_C",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_PROD_GRP_C\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_PROD_GRP_C\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [
          {
            "name": "H Product Group - Description",
            "levels": [
              {
                "name": "Level 01 Description",
                "column": "Level 01 Description",
                "ordinal": 0
              },
              {
                "name": "Level 02 Description",
                "column": "Level 02 Description",
                "ordinal": 1
              },
              {
                "name": "Level 03 Description",
                "column": "Level 03 Description",
                "ordinal": 2
              },
              {
                "name": "Level 04 Description",
                "column": "Level 04 Description",
                "ordinal": 3
              },
              {
                "name": "Level 05 Description",
                "column": "Level 05 Description",
                "ordinal": 4
              },
              {
                "name": "Level 06 Description",
                "column": "Level 06 Description",
                "ordinal": 5
              }
            ]
          },
          {
            "name": "H Product Group - Code",
            "levels": [
              {
                "name": "Level 01 Code",
                "column": "Level 01 Code",
                "ordinal": 0
              },
              {
                "name": "Level 02 Code",
                "column": "Level 02 Code",
                "ordinal": 1
              },
              {
                "name": "Level 03 Code",
                "column": "Level 03 Code",
                "ordinal": 2
              },
              {
                "name": "Level 04 Code",
                "column": "Level 04 Code",
                "ordinal": 3
              },
              {
                "name": "Level 05 Code",
                "column": "Level 05 Code",
                "ordinal": 4
              },
              {
                "name": "Level 06 Code",
                "column": "Level 06 Code",
                "ordinal": 5
              }
            ]
          }
        ],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 01 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_01_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 01 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_01_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 02 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_02_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 02 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_02_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 03 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_03_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 03 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_03_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 04 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_04_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 04 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_04_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 05 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_05_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 05 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_05_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 06 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_06_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 06 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_06_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Node",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_NODE"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Node Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_NODE_DESC"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Effective Date",
            "displayFolder": "Attributes",
            "sourceColumn": "EFF_DT"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Closed Date",
            "displayFolder": "Attributes",
            "sourceColumn": "CLS_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Closed Indicator",
            "displayFolder": "Attributes",
            "sourceColumn": "CLS_IND"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag1",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG1"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag2",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG2"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag3",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG3"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Business Date",
            "displayFolder": "Attributes",
            "sourceColumn": "BUSN_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "H Product Group",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_PROD_GRP_C\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_PROD_GRP_C\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "H_PROD_GRP_C"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "H_PROD_ORG_C",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_PROD_ORG_C\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_PROD_ORG_C\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [
          {
            "name": "H Product Org - Code",
            "levels": [
              {
                "name": "Level 01 Code",
                "column": "Level 01 Code",
                "ordinal": 0
              },
              {
                "name": "Level 02 Code",
                "column": "Level 02 Code",
                "ordinal": 1
              },
              {
                "name": "Level 03 Code",
                "column": "Level 03 Code",
                "ordinal": 2
              },
              {
                "name": "Level 04 Code",
                "column": "Level 04 Code",
                "ordinal": 3
              },
              {
                "name": "Level 05 Code",
                "column": "Level 05 Code",
                "ordinal": 4
              },
              {
                "name": "Level 06 Code",
                "column": "Level 06 Code",
                "ordinal": 5
              }
            ]
          },
          {
            "name": "H Product Org - Description",
            "levels": [
              {
                "name": "Level 01 Description",
                "column": "Level 01 Description",
                "ordinal": 0
              },
              {
                "name": "Level 02 Description",
                "column": "Level 02 Description",
                "ordinal": 1
              },
              {
                "name": "Level 03 Description",
                "column": "Level 03 Description",
                "ordinal": 2
              },
              {
                "name": "Level 04 Description",
                "column": "Level 04 Description",
                "ordinal": 3
              },
              {
                "name": "Level 05 Description",
                "column": "Level 05 Description",
                "ordinal": 4
              },
              {
                "name": "Level 06 Description",
                "column": "Level 06 Description",
                "ordinal": 5
              }
            ]
          }
        ],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 01 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_01_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 01 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_01_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 02 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_02_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 02 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_02_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 03 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_03_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 03 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_03_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 04 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_04_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 04 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_04_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 05 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_05_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 05 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_05_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 06 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_06_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 06 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_06_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Node",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_NODE"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Node Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_NODE_DESC"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Effective Date",
            "displayFolder": "Attributes",
            "sourceColumn": "EFF_DT"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Closed Date",
            "displayFolder": "Attributes",
            "sourceColumn": "CLS_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Closed Indicator",
            "displayFolder": "Attributes",
            "sourceColumn": "CLS_IND"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag1",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG1"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag2",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG2"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Tag3",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_TAG3"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Business Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "BUSN_DT",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "H Product Org",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_PROD_ORG_C\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_PROD_ORG_C\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "H_PROD_ORG_C"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "D_CTO_OFFICER_CM",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_CUS_V\".\"D_CTO_OFFICER_CM\".* FROM \"U01_EDW_SEM_CUS_V\".\"D_CTO_OFFICER_CM\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [],
        "columns": [
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "CTO Officer EDW ID",
            "summarizeBy": "none",
            "displayFolder": "Tech Fields",
            "sourceColumn": "CTO_OFICR_EDW_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CTO Officer Code",
            "displayFolder": "Attributes",
            "sourceColumn": "CTO_OFICR_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CTO Officer Name",
            "displayFolder": "Attributes",
            "sourceColumn": "CTO_OFICR_NM"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CTO Cost Center",
            "displayFolder": "Attributes",
            "sourceColumn": "CTO_COST_CTR",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Marketing Team",
            "displayFolder": "Attributes",
            "sourceColumn": "MKTG_TEAM"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Record Deleted Flag",
            "summarizeBy": "none",
            "displayFolder": "Tech Fields",
            "sourceColumn": "RECORD_DELETED_FLAG",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Control ID",
            "summarizeBy": "none",
            "displayFolder": "Tech Fields",
            "sourceColumn": "CTL_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "D CTO Officer",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_CUS_V\".\"D_CTO_OFFICER_CM\".* FROM \"U01_EDW_SEM_CUS_V\".\"D_CTO_OFFICER_CM\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "D_CTO_OFFICER_CM"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "D_CTO_OFFICER_D",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_CUS_V\".\"D_CTO_OFFICER_D\".* FROM \"U01_EDW_SEM_CUS_V\".\"D_CTO_OFFICER_D\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [],
        "columns": [
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Business Date",
            "displayFolder": "Attributes",
            "sourceColumn": "BUSN_DT",
            "isHidden": true
          },
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "CTO Officer EDW ID",
            "summarizeBy": "none",
            "displayFolder": "Tech Fields",
            "sourceColumn": "CTO_OFICR_EDW_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CTO Officer Code",
            "displayFolder": "Attributes",
            "sourceColumn": "CTO_OFICR_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CTO Officer Name",
            "displayFolder": "Attributes",
            "sourceColumn": "CTO_OFICR_NM"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CTO Cost Center",
            "displayFolder": "Attributes",
            "sourceColumn": "CTO_COST_CTR",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Marketing Team",
            "displayFolder": "Attributes",
            "sourceColumn": "MKTG_TEAM"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Record Deleted Flag",
            "summarizeBy": "none",
            "displayFolder": "Tech Fields",
            "sourceColumn": "RECORD_DELETED_FLAG",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Control ID",
            "summarizeBy": "none",
            "displayFolder": "Tech Fields",
            "sourceColumn": "CTL_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "expression": "'X D CTO Officer Dated'[Business Date] & \"~\" & 'X D CTO Officer Dated'[CTO Officer EDW ID]",
            "name": "BUSN_DT_CTO_OFICR_EDW_ID",
            "type": "calculated",
            "displayFolder": "Tech Fields",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "X D CTO Officer Dated",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_CUS_V\".\"D_CTO_OFFICER_D\".* FROM \"U01_EDW_SEM_CUS_V\".\"D_CTO_OFFICER_D\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "D_CTO_OFFICER_D"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "D_SCNRO_TYPE",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_OTH_V\".\"D_SCNRO_TYPE\".* FROM \"U01_EDW_SEM_OTH_V\".\"D_SCNRO_TYPE\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Scenario Code",
            "displayFolder": "Attributes",
            "sourceColumn": "SCNRO_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Scenario Description",
            "displayFolder": "Attributes",
            "sourceColumn": "SCNRO_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Record Deleted Flag",
            "summarizeBy": "none",
            "displayFolder": "Tech Fields",
            "sourceColumn": "RECORD_DELETED_FLAG",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Control ID",
            "summarizeBy": "none",
            "displayFolder": "Tech Fields",
            "sourceColumn": "CTL_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "D Scenario Type",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_OTH_V\".\"D_SCNRO_TYPE\".* FROM \"U01_EDW_SEM_OTH_V\".\"D_SCNRO_TYPE\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "D_SCNRO_TYPE"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "D_SCNRO_SUB_CAT",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_OTH_V\".\"D_SCNRO_SUB_CAT\".* FROM \"U01_EDW_SEM_OTH_V\".\"D_SCNRO_SUB_CAT\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Scenario Sub Category",
            "displayFolder": "Attributes",
            "sourceColumn": "SCNRO_SUB_CAT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Scenario Sub Category Description",
            "displayFolder": "Attributes",
            "sourceColumn": "SCNRO_SUB_CAT_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Record Deleted Flag",
            "displayFolder": "Tech Fields",
            "sourceColumn": "RECORD_DELETED_FLAG",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "Date",
            "dataType": "dateTime",
            "name": "Snapshot Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Control ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "CTL_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "D Scenario Sub Category",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_OTH_V\".\"D_SCNRO_SUB_CAT\".* FROM \"U01_EDW_SEM_OTH_V\".\"D_SCNRO_SUB_CAT\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "D_SCNRO_SUB_CAT"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "D_GRM_OFICR_CM",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_GWB_V\".\"D_GRM_OFICR_CM\".* FROM \"U01_EDW_SEM_GWB_V\".\"D_GRM_OFICR_CM\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [],
        "columns": [
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "GRM Officer EDW ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "GRM_OFICR_EDW_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM Country Code",
            "displayFolder": "Attributes",
            "sourceColumn": "GRM_CTRY_CD",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM Cost Center",
            "displayFolder": "Attributes",
            "sourceColumn": "GRM_COST_CTR",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM Name",
            "displayFolder": "Attributes",
            "sourceColumn": "GRM_NM"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM_GRP_NM",
            "sourceColumn": "GRM_GRP_NM"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM Officer Code",
            "displayFolder": "Attributes",
            "sourceColumn": "GRM_OFICR_CD"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "Date",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Record Deleted Flag",
            "displayFolder": "Tech Fields",
            "sourceColumn": "RECORD_DELETED_FLAG",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Control ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "CTL_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "D GRM Officer",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_GWB_V\".\"D_GRM_OFICR_CM\".* FROM \"U01_EDW_SEM_GWB_V\".\"D_GRM_OFICR_CM\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "D_GRM_OFICR_CM"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "R_GWB_PRTY_GRP_CM",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_GWB_V\".\"R_GWB_PRTY_GRP_CM\".* FROM \"U01_EDW_SEM_GWB_V\".\"R_GWB_PRTY_GRP_CM\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [],
        "columns": [
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "CIF Party EDW ID",
            "displayFolder": "Attributes",
            "sourceColumn": "CIF_PRTY_EDW_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CIF Number",
            "displayFolder": "Attributes",
            "sourceColumn": "CIF_NUM"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CIF Site ID",
            "displayFolder": "Attributes",
            "sourceColumn": "CIF_SITE_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "Group Party Group EDW ID",
            "displayFolder": "Attributes",
            "sourceColumn": "GRP_PRTY_GRP_EDW_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Group Number",
            "displayFolder": "Attributes",
            "sourceColumn": "GRP_NUM"
          },
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "GRM Officer EDW ID",
            "displayFolder": "Attributes",
            "sourceColumn": "GRM_OFICR_EDW_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM CTO Code",
            "displayFolder": "Attributes",
            "sourceColumn": "GRM_CTO_CD",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM Country Code",
            "displayFolder": "Attributes",
            "sourceColumn": "GRM_CTRY_CD",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM Name",
            "displayFolder": "Attributes",
            "sourceColumn": "GRM_NM",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM Cost Center",
            "displayFolder": "Attributes",
            "sourceColumn": "GRM_COST_CTR",
            "isHidden": true
          },
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "Party Group EDW ID",
            "displayFolder": "Attributes",
            "sourceColumn": "PRTY_GRP_EDW_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GCIF",
            "displayFolder": "Attributes",
            "sourceColumn": "GCIF"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GCIF GRM CTO Code",
            "displayFolder": "Attributes",
            "sourceColumn": "GCIF_GRM_CTO_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GCIF GRM Name",
            "displayFolder": "Attributes",
            "sourceColumn": "GCIF_GRM_NM"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Group Name",
            "displayFolder": "Attributes",
            "sourceColumn": "GRP_NM"
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Record Deleted Flag",
            "displayFolder": "Tech Fields",
            "sourceColumn": "RECORD_DELETED_FLAG",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "Date",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "R GWB Party Group",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_GWB_V\".\"R_GWB_PRTY_GRP_CM\".* FROM \"U01_EDW_SEM_GWB_V\".\"R_GWB_PRTY_GRP_CM\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "R_GWB_PRTY_GRP_CM"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "D_GRM_OFICR_D",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_GWB_V\".\"D_GRM_OFICR_D\".* FROM \"U01_EDW_SEM_GWB_V\".\"D_GRM_OFICR_D\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [],
        "columns": [
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Business Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "BUSN_DT",
            "isHidden": true
          },
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "GRM Officer EDW ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "GRM_OFICR_EDW_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM Country Code",
            "displayFolder": "Attributes",
            "sourceColumn": "GRM_CTRY_CD",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM Cost Center",
            "displayFolder": "Attributes",
            "sourceColumn": "GRM_COST_CTR",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM Name",
            "displayFolder": "Attributes",
            "sourceColumn": "GRM_NM"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM_GRP_NM",
            "sourceColumn": "GRM_GRP_NM"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM Officer Code",
            "displayFolder": "Attributes",
            "sourceColumn": "GRM_OFICR_CD"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "Date",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Record Deleted Flag",
            "displayFolder": "Tech Fields",
            "sourceColumn": "RECORD_DELETED_FLAG",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Control ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "CTL_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "expression": "'X D GRM Officer Dated'[Business Date] & \"~\" &'X D GRM Officer Dated'[GRM Officer EDW ID]",
            "name": "BUSS_DT_GRM_OFICR_EDW_ID",
            "type": "calculated",
            "displayFolder": "Tech Fields",
            "isHidden": true
          },
          {
            "expression": "'X D GRM Officer Dated'[Business Date] & \"~\" &'X D GRM Officer Dated'[GRM Officer EDW ID]",
            "name": "BUSS_DT_PARTY_EDW_ID",
            "type": "calculated",
            "displayFolder": "Tech Fields",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "X D GRM Officer Dated",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_GWB_V\".\"D_GRM_OFICR_D\".* FROM \"U01_EDW_SEM_GWB_V\".\"D_GRM_OFICR_D\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "D_GRM_OFICR_D"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "H_PROD_RPTG_C",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_PROD_RPTG_C\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_PROD_RPTG_C\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [
          {
            "name": "H Product Reporting - Description",
            "levels": [
              {
                "name": "Level 01 Description",
                "column": "Level 01 Description",
                "ordinal": 0
              },
              {
                "name": "Level 02 Description",
                "column": "Level 02 Description",
                "ordinal": 1
              },
              {
                "name": "Level 03 Description",
                "column": "Level 03 Description",
                "ordinal": 2
              },
              {
                "name": "Level 04 Description",
                "column": "Level 04 Description",
                "ordinal": 3
              },
              {
                "name": "Level 05 Description",
                "column": "Level 05 Description",
                "ordinal": 4
              },
              {
                "name": "Level 06 Description",
                "column": "Level 06 Description",
                "ordinal": 5
              },
              {
                "name": "Level 07 Description",
                "column": "Level 07 Description",
                "ordinal": 6
              }
            ]
          },
          {
            "name": "H Product Reporting - Code",
            "levels": [
              {
                "name": "Level 01 Code",
                "column": "Level 01 Code",
                "ordinal": 0
              },
              {
                "name": "Level 02 Code",
                "column": "Level 02 Code",
                "ordinal": 1
              },
              {
                "name": "Level 03 Code",
                "column": "Level 03 Code",
                "ordinal": 2
              },
              {
                "name": "Level 04 Code",
                "column": "Level 04 Code",
                "ordinal": 3
              },
              {
                "name": "Level 05 Code",
                "column": "Level 05 Code",
                "ordinal": 4
              },
              {
                "name": "Level 06 Code",
                "column": "Level 06 Code",
                "ordinal": 5
              },
              {
                "name": "Level 07 Code",
                "column": "Level 07 Code",
                "ordinal": 6
              }
            ]
          }
        ],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 01 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_01_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 01 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_01_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 02 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_02_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 02 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_02_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 03 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_03_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 03 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_03_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 04 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_04_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 04 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_04_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 05 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_05_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 05 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_05_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 06 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_06_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 06 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_06_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 07 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_07_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 07 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_07_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Node",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_NODE"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Leaf Node Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LEAF_NODE_DESC"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Effective Date",
            "displayFolder": "Attributes",
            "sourceColumn": "EFF_DT"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Closed Date",
            "displayFolder": "Attributes",
            "sourceColumn": "CLS_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Closed Indicator",
            "displayFolder": "Attributes",
            "sourceColumn": "CLS_IND"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Business Date",
            "displayFolder": "Attributes",
            "sourceColumn": "BUSN_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "H Product Reporting",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_PROD_RPTG_C\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_PROD_RPTG_C\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "H_PROD_RPTG_C"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "H_MAS_INDUSTRY_C",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_MAS_INDUSTRY_C\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_MAS_INDUSTRY_C\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Industry Code",
            "displayFolder": "Attributes",
            "sourceColumn": "IDSTRY_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Industry Description",
            "displayFolder": "Attributes",
            "sourceColumn": "IDSTRY_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CCRM Industry Group Code",
            "displayFolder": "Attributes",
            "sourceColumn": "CCRM_IDSTRY_GRP_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CCRM Industry Group Description",
            "displayFolder": "Attributes",
            "sourceColumn": "CCRM_IDSTRY_GRP_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CCRM Industry Sector Code",
            "displayFolder": "Attributes",
            "sourceColumn": "CCRM_IDSTRY_SECTR_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CCRM Industry Sector Description",
            "displayFolder": "Attributes",
            "sourceColumn": "CCRM_IDSTRY_SECTR_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CCRM Top Level Code",
            "displayFolder": "Attributes",
            "sourceColumn": "CCRM_TOP_LVL_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CCRM Top Level Description",
            "displayFolder": "Attributes",
            "sourceColumn": "CCRM_TOP_LVL_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CCRM Industry Tag 1",
            "displayFolder": "Attributes",
            "sourceColumn": "CCRM_TAG1"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CCRM Industry Tag 2",
            "displayFolder": "Attributes",
            "sourceColumn": "CCRM_TAG2"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CCRM Industry Tag 3",
            "displayFolder": "Attributes",
            "sourceColumn": "CCRM_TAG3"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CCRM Industry Tag 4",
            "displayFolder": "Attributes",
            "sourceColumn": "CCRM_TAG4"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "CCRM Industry Tag 5",
            "displayFolder": "Attributes",
            "sourceColumn": "CCRM_TAG5"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Effective Date",
            "displayFolder": "Attributes",
            "sourceColumn": "EFF_DT"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Closed Date",
            "displayFolder": "Attributes",
            "sourceColumn": "CLSD_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Closed Indicator",
            "displayFolder": "Attributes",
            "sourceColumn": "CLSD_IND"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Business Date",
            "displayFolder": "Attributes",
            "sourceColumn": "BUSN_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "H MAS Industry",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_MAS_INDUSTRY_C\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_MAS_INDUSTRY_C\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "H_MAS_INDUSTRY_C"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "D_PRTY_GWB_CM",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_GWB_V\".\"D_PRTY_GWB_CM\".* FROM \"U01_EDW_SEM_GWB_V\".\"D_PRTY_GWB_CM\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [],
        "columns": [
          {
            "sourceProviderType": "Integer",
            "dataType": "int64",
            "name": "PARTY EDW ID",
            "displayFolder": "Attributes",
            "sourceColumn": "PRTY_EDW_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Customer Source Type",
            "displayFolder": "Attributes",
            "sourceColumn": "CUST_SRC_TYPE"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Customer Source Number",
            "displayFolder": "Attributes",
            "sourceColumn": "CUST_SRC_NUM"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Customer Segment Cd",
            "displayFolder": "Attributes",
            "sourceColumn": "CUST_SEGMT_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Customer Type Cd",
            "displayFolder": "Attributes",
            "sourceColumn": "CUST_TYPE_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "MAS industrial classification",
            "displayFolder": "Attributes",
            "sourceColumn": "MAS_INDRL_CLAS"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Party Name",
            "displayFolder": "Attributes",
            "sourceColumn": "PRTY_NM",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Attributes",
            "sourceColumn": "STRT_DT",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Record Deleted Flag",
            "displayFolder": "Attributes",
            "sourceColumn": "RECORD_DELETED_FLAG",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "Control Id",
            "displayFolder": "Attributes",
            "sourceColumn": "CTL_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Attributes",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Attributes",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Country of Incorporation",
            "displayFolder": "Attributes",
            "sourceColumn": "CTRY_OF_INC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Country of Business Operation",
            "displayFolder": "Attributes",
            "sourceColumn": "CTRY_OF_BUSN_OPR"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Local Name",
            "displayFolder": "Attributes",
            "sourceColumn": "LOCL_NM"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "English Name",
            "displayFolder": "Attributes",
            "sourceColumn": "ENGL_NM"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Country Of Operation Risk",
            "displayFolder": "Attributes",
            "sourceColumn": "CTRY_OF_OPR_RISK"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Bank Short Name",
            "displayFolder": "Attributes",
            "sourceColumn": "BANK_SHRT_NM"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM Cost Center",
            "displayFolder": "Attributes",
            "sourceColumn": "GRM_COST_CTR",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "GRM Country Code",
            "displayFolder": "Attributes",
            "sourceColumn": "GRM_CTRY_CD",
            "isHidden": true
          },
          {
            "expression": "IF(ISBLANK('D Party GWB'[English Name]), 'D Party GWB'[Local Name] ,'D Party GWB'[English Name])",
            "name": "Party Name Description",
            "type": "calculated",
            "displayFolder": "Attributes"
          }
        ],
        "dataCategory": "",
        "name": "D Party GWB",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_GWB_V\".\"D_PRTY_GWB_CM\".* FROM \"U01_EDW_SEM_GWB_V\".\"D_PRTY_GWB_CM\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "D_PRTY_GWB_CM"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "H_APEX_INDSTRY_C",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_APEX_INDSTRY_C\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_APEX_INDSTRY_C\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 01 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_01_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 01 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_01_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 02 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_02_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 02 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_02_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 03 Code",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_03_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Level 03 Description",
            "displayFolder": "Attributes",
            "sourceColumn": "LVL_03_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Industry Code",
            "displayFolder": "Attributes",
            "sourceColumn": "INDSTRY_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Industry Description",
            "displayFolder": "Attributes",
            "sourceColumn": "INDSRTY_DESC"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Effective Date",
            "displayFolder": "Attributes",
            "sourceColumn": "EFF_DT"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Closed Date",
            "displayFolder": "Attributes",
            "sourceColumn": "CLS_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Closed Indicator",
            "displayFolder": "Attributes",
            "sourceColumn": "CLS_IND"
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Business Date",
            "displayFolder": "Attributes",
            "sourceColumn": "BUSN_DT"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Site ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Source System",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "timestamp",
            "dataType": "dateTime",
            "name": "Start Date",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "H Apex Industry",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_OTH_V\".\"H_APEX_INDSTRY_C\".* FROM \"U01_EDW_SEM_OTH_V\".\"H_APEX_INDSTRY_C\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "H_APEX_INDSTRY_C"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "D_CROSS_BORDR_CAT",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_OTH_V\".\"D_CROSS_BORDR_CAT\".* FROM \"U01_EDW_SEM_OTH_V\".\"D_CROSS_BORDR_CAT\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Cross Border Category Code",
            "displayFolder": "Attributes",
            "sourceColumn": "CROSS_BORDR_CAT_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Cross Border Category Description",
            "displayFolder": "Attributes",
            "sourceColumn": "CROSS_BORDR_CAT_DESC"
          }
        ],
        "dataCategory": "",
        "name": "D Cross Border Category",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_OTH_V\".\"D_CROSS_BORDR_CAT\".* FROM \"U01_EDW_SEM_OTH_V\".\"D_CROSS_BORDR_CAT\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "D_CROSS_BORDR_CAT"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "D_ASIS_ASWAS_CAT",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_OTH_V\".\"D_ASIS_ASWAS_CAT\".* FROM \"U01_EDW_SEM_OTH_V\".\"D_ASIS_ASWAS_CAT\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Asis Aswas Category Code",
            "displayFolder": "Attributes",
            "sourceColumn": "ASIS_ASWAS_CAT_CD"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Asis Aswas Category Description",
            "displayFolder": "Attributes",
            "sourceColumn": "ASIS_ASWAS_CAT_DESC"
          }
        ],
        "dataCategory": "",
        "name": "D Asis Aswas Category",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_OTH_V\".\"D_ASIS_ASWAS_CAT\".* FROM \"U01_EDW_SEM_OTH_V\".\"D_ASIS_ASWAS_CAT\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "D_ASIS_ASWAS_CAT"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      },
      {
        "partitions": [{
          "name": "D_VALUT_TYPE",
          "source": {
            "query": " SELECT \"U01_EDW_SEM_OTH_V\".\"D_VALUT_TYPE\".* FROM \"U01_EDW_SEM_OTH_V\".\"D_VALUT_TYPE\" ",
            "dataSource": "T3 Source"
          },
          "dataView": "full"
        }],
        "measures": [],
        "hierarchies": [],
        "columns": [
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Valuation Type",
            "displayFolder": "Attributes",
            "sourceColumn": "VALUT_TYPE"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "Valuation Type Description",
            "displayFolder": "Attributes",
            "sourceColumn": "VALUT_TYPE_DESC"
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "SITE_ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SITE_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "RECORD_DELETED_FLAG",
            "displayFolder": "Tech Fields",
            "sourceColumn": "RECORD_DELETED_FLAG",
            "isHidden": true
          },
          {
            "formatString": "dd/MMM/yyyy",
            "sourceProviderType": "Date",
            "dataType": "dateTime",
            "name": "SNAPSHOT_DATE",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SNAPSHOT_DATE",
            "isHidden": true
          },
          {
            "sourceProviderType": "SmallInt",
            "dataType": "int64",
            "name": "CTL_ID",
            "displayFolder": "Tech Fields",
            "sourceColumn": "CTL_ID",
            "isHidden": true
          },
          {
            "sourceProviderType": "VarChar",
            "dataType": "string",
            "name": "SRC_SYS_NM",
            "displayFolder": "Tech Fields",
            "sourceColumn": "SRC_SYS_NM",
            "isHidden": true
          }
        ],
        "dataCategory": "",
        "name": "D Valuation Type",
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT \"U01_EDW_SEM_OTH_V\".\"D_VALUT_TYPE\".* FROM \"U01_EDW_SEM_OTH_V\".\"D_VALUT_TYPE\" "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "D_VALUT_TYPE"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "U01_EDW_SEM_V"
          }
        ],
        "description": ""
      }
    ],
    "defaultMode": "directQuery",
    "culture": "en-US",
    "roles": [{
      "modelPermission": "read",
      "members": [
        {"memberName": "NTSGPDOM\\uCTX_EDA_PBI_UAT"},
        {"memberName": "NTSGPDOM\\vendc8"},
        {"memberName": "NTSGPDOM\\veneza"},
        {"memberName": "NTSGPDOM\\tmpob2"},
        {"memberName": "NTSGPDOM\\uncsav"},
        {"memberName": "NTSGPDOM\\uncglt"},
        {"memberName": "NTSGPDOM\\vendm8"},
        {"memberName": "NTSGPDOM\\vendx1"},
        {"memberName": "NTSGPDOM\\venris"}
      ],
      "name": "Reader"
    }],
    "annotations": [{
      "name": "ClientCompatibilityLevel",
      "value": "400"
    }],
    "dataSources": [{
      "connectionString": "Data Encryption=True;Data Source=tdp;Persist Security Info=False;Session Character Set=UTF8;Session Mode=DEFAULT;Connection Pooling Timeout=30;Max Pool Size=1000;Integrated Security=True;Recovery=OFF;Command Timeout=120;Connection Timeout=120;",
      "provider": "Teradata.Client.Provider",
      "name": "T3 Source",
      "impersonationMode": "impersonateCurrentUser",
      "annotations": [{
        "name": "ConnectionEditUISource",
        "value": "Teradata"
      }],
      "maxConnections": 1000
    }]
  }
}
